package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * Announcement generated by hbm2java
 */
public class Announcement implements java.io.Serializable {

	// Fields    

	private AnnouncementId id;

	private AdministrativeMessageRef administrativeMessageRef;

	private String locationId;

	private String description;

	private String lastUpdateUserid;

	// Constructors

	/** default constructor */
	public Announcement() {
	}

	/** minimal constructor */
	public Announcement(AnnouncementId id,
			AdministrativeMessageRef administrativeMessageRef,
			String locationId, String lastUpdateUserid) {
		this.id = id;
		this.administrativeMessageRef = administrativeMessageRef;
		this.locationId = locationId;
		this.lastUpdateUserid = lastUpdateUserid;
	}

	/** full constructor */
	public Announcement(AnnouncementId id,
			AdministrativeMessageRef administrativeMessageRef,
			String locationId, String description, String lastUpdateUserid) {
		this.id = id;
		this.administrativeMessageRef = administrativeMessageRef;
		this.locationId = locationId;
		this.description = description;
		this.lastUpdateUserid = lastUpdateUserid;
	}

	// Property accessors
	public AnnouncementId getId() {
		return this.id;
	}

	public void setId(AnnouncementId id) {
		this.id = id;
	}

	public AdministrativeMessageRef getAdministrativeMessageRef() {
		return this.administrativeMessageRef;
	}

	public void setAdministrativeMessageRef(
			AdministrativeMessageRef administrativeMessageRef) {
		this.administrativeMessageRef = administrativeMessageRef;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

}
