package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CategoryClassificationRefId generated by hbm2java
 */
public class CategoryClassificationRefId implements java.io.Serializable {

	// Fields

	private String categoryId;

	private String classificationId;

	// Constructors

	/** default constructor */
	public CategoryClassificationRefId() {
	}

	/** full constructor */
	public CategoryClassificationRefId(String categoryId,
			String classificationId) {
		this.categoryId = categoryId;
		this.classificationId = classificationId;
	}

	// Property accessors
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(String classificationId) {
		this.classificationId = classificationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryClassificationRefId))
			return false;
		CategoryClassificationRefId castOther = (CategoryClassificationRefId) other;

		return ((this.getCategoryId() == castOther.getCategoryId()) || (this
				.getCategoryId() != null
				&& castOther.getCategoryId() != null && this
				.getCategoryId().equals(castOther.getCategoryId())))
				&& ((this.getClassificationId() == castOther
						.getClassificationId()) || (this
						.getClassificationId() != null
						&& castOther.getClassificationId() != null && this
						.getClassificationId().equals(
								castOther.getClassificationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCategoryId() == null ? 0 : this.getCategoryId()
						.hashCode());
		result = 37
				* result
				+ (getClassificationId() == null ? 0 : this
						.getClassificationId().hashCode());
		return result;
	}

}
