package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CbrProjectInformationId generated by hbm2java
 */
public class CbrProjectInformationId implements java.io.Serializable {

	// Fields

	private String cbrLoanInformationId;

	private String cbrProjectInformationId;

	// Constructors

	/** default constructor */
	public CbrProjectInformationId() {
	}

	/** full constructor */
	public CbrProjectInformationId(String cbrLoanInformationId,
			String cbrProjectInformationId) {
		this.cbrLoanInformationId = cbrLoanInformationId;
		this.cbrProjectInformationId = cbrProjectInformationId;
	}

	// Property accessors
	public String getCbrLoanInformationId() {
		return this.cbrLoanInformationId;
	}

	public void setCbrLoanInformationId(String cbrLoanInformationId) {
		this.cbrLoanInformationId = cbrLoanInformationId;
	}

	public String getCbrProjectInformationId() {
		return this.cbrProjectInformationId;
	}

	public void setCbrProjectInformationId(String cbrProjectInformationId) {
		this.cbrProjectInformationId = cbrProjectInformationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CbrProjectInformationId))
			return false;
		CbrProjectInformationId castOther = (CbrProjectInformationId) other;

		return ((this.getCbrLoanInformationId() == castOther
				.getCbrLoanInformationId()) || (this
				.getCbrLoanInformationId() != null
				&& castOther.getCbrLoanInformationId() != null && this
				.getCbrLoanInformationId().equals(
						castOther.getCbrLoanInformationId())))
				&& ((this.getCbrProjectInformationId() == castOther
						.getCbrProjectInformationId()) || (this
						.getCbrProjectInformationId() != null
						&& castOther.getCbrProjectInformationId() != null && this
						.getCbrProjectInformationId().equals(
								castOther.getCbrProjectInformationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCbrLoanInformationId() == null ? 0 : this
						.getCbrLoanInformationId().hashCode());
		result = 37
				* result
				+ (getCbrProjectInformationId() == null ? 0 : this
						.getCbrProjectInformationId().hashCode());
		return result;
	}

}
