package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClassificationRef generated by hbm2java
 */
public class ClassificationRef implements java.io.Serializable {

	// Fields    

	private String classificationId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set categoryClassificationRefs = new HashSet(0);

	private Set costs = new HashSet(0);

	// Constructors

	/** default constructor */
	public ClassificationRef() {
	}

	/** minimal constructor */
	public ClassificationRef(String classificationId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.classificationId = classificationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public ClassificationRef(String classificationId, String name,
			String lastUpdateUserid, Date lastUpdateTs,
			Set categoryClassificationRefs, Set costs) {
		this.classificationId = classificationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.categoryClassificationRefs = categoryClassificationRefs;
		this.costs = costs;
	}

	// Property accessors
	public String getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(String classificationId) {
		this.classificationId = classificationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCategoryClassificationRefs() {
		return this.categoryClassificationRefs;
	}

	public void setCategoryClassificationRefs(Set categoryClassificationRefs) {
		this.categoryClassificationRefs = categoryClassificationRefs;
	}

	public Set getCosts() {
		return this.costs;
	}

	public void setCosts(Set costs) {
		this.costs = costs;
	}

}
