package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CombinedSewerStatusRef generated by hbm2java
 */
public class CombinedSewerStatusRef implements java.io.Serializable {

	// Fields    

	private String combinedSewerStatusId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set combinedSewers = new HashSet(0);

	// Constructors

	/** default constructor */
	public CombinedSewerStatusRef() {
	}

	/** minimal constructor */
	public CombinedSewerStatusRef(String combinedSewerStatusId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.combinedSewerStatusId = combinedSewerStatusId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CombinedSewerStatusRef(String combinedSewerStatusId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set combinedSewers) {
		this.combinedSewerStatusId = combinedSewerStatusId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.combinedSewers = combinedSewers;
	}

	// Property accessors
	public String getCombinedSewerStatusId() {
		return this.combinedSewerStatusId;
	}

	public void setCombinedSewerStatusId(String combinedSewerStatusId) {
		this.combinedSewerStatusId = combinedSewerStatusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCombinedSewers() {
		return this.combinedSewers;
	}

	public void setCombinedSewers(Set combinedSewers) {
		this.combinedSewers = combinedSewers;
	}

}
