package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CwnsUserLocatnAccessLevelId generated by hbm2java
 */
public class CwnsUserLocatnAccessLevelId implements java.io.Serializable {

	// Fields

	private String cwnsUserId;

	private String locationTypeId;

	private String locationId;

	private long accessLevelId;

	// Constructors

	/** default constructor */
	public CwnsUserLocatnAccessLevelId() {
	}

	/** full constructor */
	public CwnsUserLocatnAccessLevelId(String cwnsUserId,
			String locationTypeId, String locationId, long accessLevelId) {
		this.cwnsUserId = cwnsUserId;
		this.locationTypeId = locationTypeId;
		this.locationId = locationId;
		this.accessLevelId = accessLevelId;
	}

	// Property accessors
	public String getCwnsUserId() {
		return this.cwnsUserId;
	}

	public void setCwnsUserId(String cwnsUserId) {
		this.cwnsUserId = cwnsUserId;
	}

	public String getLocationTypeId() {
		return this.locationTypeId;
	}

	public void setLocationTypeId(String locationTypeId) {
		this.locationTypeId = locationTypeId;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public long getAccessLevelId() {
		return this.accessLevelId;
	}

	public void setAccessLevelId(long accessLevelId) {
		this.accessLevelId = accessLevelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CwnsUserLocatnAccessLevelId))
			return false;
		CwnsUserLocatnAccessLevelId castOther = (CwnsUserLocatnAccessLevelId) other;

		return ((this.getCwnsUserId() == castOther.getCwnsUserId()) || (this
				.getCwnsUserId() != null
				&& castOther.getCwnsUserId() != null && this
				.getCwnsUserId().equals(castOther.getCwnsUserId())))
				&& ((this.getLocationTypeId() == castOther
						.getLocationTypeId()) || (this.getLocationTypeId() != null
						&& castOther.getLocationTypeId() != null && this
						.getLocationTypeId().equals(
								castOther.getLocationTypeId())))
				&& ((this.getLocationId() == castOther.getLocationId()) || (this
						.getLocationId() != null
						&& castOther.getLocationId() != null && this
						.getLocationId().equals(castOther.getLocationId())))
				&& (this.getAccessLevelId() == castOther.getAccessLevelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCwnsUserId() == null ? 0 : this.getCwnsUserId()
						.hashCode());
		result = 37
				* result
				+ (getLocationTypeId() == null ? 0 : this
						.getLocationTypeId().hashCode());
		result = 37
				* result
				+ (getLocationId() == null ? 0 : this.getLocationId()
						.hashCode());
		result = 37 * result + (int) this.getAccessLevelId();
		return result;
	}

}
