package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * CwnsInfoLocationRef generated by hbm2java
 */
public class CwnsInfoLocationRef implements java.io.Serializable {

	// Fields    

	private String locationId;

	private Date dataEntryEndDate;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public CwnsInfoLocationRef() {
	}

	/** full constructor */
	public CwnsInfoLocationRef(String locationId, Date dataEntryEndDate,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.locationId = locationId;
		this.dataEntryEndDate = dataEntryEndDate;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public Date getDataEntryEndDate() {
		return this.dataEntryEndDate;
	}

	public void setDataEntryEndDate(Date dataEntryEndDate) {
		this.dataEntryEndDate = dataEntryEndDate;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
