package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CwnsUserStatusRef generated by hbm2java
 */
public class CwnsUserStatusRef implements java.io.Serializable {

	// Fields    

	private String cwnsUserStatusId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set cwnsUsers = new HashSet(0);

	// Constructors

	/** default constructor */
	public CwnsUserStatusRef() {
	}

	/** minimal constructor */
	public CwnsUserStatusRef(String cwnsUserStatusId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.cwnsUserStatusId = cwnsUserStatusId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CwnsUserStatusRef(String cwnsUserStatusId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set cwnsUsers) {
		this.cwnsUserStatusId = cwnsUserStatusId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.cwnsUsers = cwnsUsers;
	}

	// Property accessors
	public String getCwnsUserStatusId() {
		return this.cwnsUserStatusId;
	}

	public void setCwnsUserStatusId(String cwnsUserStatusId) {
		this.cwnsUserStatusId = cwnsUserStatusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCwnsUsers() {
		return this.cwnsUsers;
	}

	public void setCwnsUsers(Set cwnsUsers) {
		this.cwnsUsers = cwnsUsers;
	}

}
