package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DischargeMethodRef generated by hbm2java
 */
public class DischargeMethodRef implements java.io.Serializable {

	// Fields    

	private long dischargeMethodId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityDischarges = new HashSet(0);

	private Set facilityTypeDischargeRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public DischargeMethodRef() {
	}

	/** minimal constructor */
	public DischargeMethodRef(long dischargeMethodId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.dischargeMethodId = dischargeMethodId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public DischargeMethodRef(long dischargeMethodId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set facilityDischarges,
			Set facilityTypeDischargeRefs) {
		this.dischargeMethodId = dischargeMethodId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityDischarges = facilityDischarges;
		this.facilityTypeDischargeRefs = facilityTypeDischargeRefs;
	}

	// Property accessors
	public long getDischargeMethodId() {
		return this.dischargeMethodId;
	}

	public void setDischargeMethodId(long dischargeMethodId) {
		this.dischargeMethodId = dischargeMethodId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityDischarges() {
		return this.facilityDischarges;
	}

	public void setFacilityDischarges(Set facilityDischarges) {
		this.facilityDischarges = facilityDischarges;
	}

	public Set getFacilityTypeDischargeRefs() {
		return this.facilityTypeDischargeRefs;
	}

	public void setFacilityTypeDischargeRefs(Set facilityTypeDischargeRefs) {
		this.facilityTypeDischargeRefs = facilityTypeDischargeRefs;
	}

}
