package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentTypeRef generated by hbm2java
 */
public class DocumentTypeRef implements java.io.Serializable {

	// Fields    

	private String documentTypeId;

	private String name;

	private char aprovedForNeedsFlag;

	private char aprovedForCostsFlag;

	private char allowFootnoteFlag;

	private String description;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set documents = new HashSet(0);

	private Set documentTypeGroupRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public DocumentTypeRef() {
	}

	/** minimal constructor */
	public DocumentTypeRef(String documentTypeId, String name,
			char aprovedForNeedsFlag, char aprovedForCostsFlag,
			char allowFootnoteFlag, String lastUpdateUserid, Date lastUpdateTs) {
		this.documentTypeId = documentTypeId;
		this.name = name;
		this.aprovedForNeedsFlag = aprovedForNeedsFlag;
		this.aprovedForCostsFlag = aprovedForCostsFlag;
		this.allowFootnoteFlag = allowFootnoteFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public DocumentTypeRef(String documentTypeId, String name,
			char aprovedForNeedsFlag, char aprovedForCostsFlag,
			char allowFootnoteFlag, String description,
			String lastUpdateUserid, Date lastUpdateTs, Set documents,
			Set documentTypeGroupRefs) {
		this.documentTypeId = documentTypeId;
		this.name = name;
		this.aprovedForNeedsFlag = aprovedForNeedsFlag;
		this.aprovedForCostsFlag = aprovedForCostsFlag;
		this.allowFootnoteFlag = allowFootnoteFlag;
		this.description = description;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.documents = documents;
		this.documentTypeGroupRefs = documentTypeGroupRefs;
	}

	// Property accessors
	public String getDocumentTypeId() {
		return this.documentTypeId;
	}

	public void setDocumentTypeId(String documentTypeId) {
		this.documentTypeId = documentTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getAprovedForNeedsFlag() {
		return this.aprovedForNeedsFlag;
	}

	public void setAprovedForNeedsFlag(char aprovedForNeedsFlag) {
		this.aprovedForNeedsFlag = aprovedForNeedsFlag;
	}

	public char getAprovedForCostsFlag() {
		return this.aprovedForCostsFlag;
	}

	public void setAprovedForCostsFlag(char aprovedForCostsFlag) {
		this.aprovedForCostsFlag = aprovedForCostsFlag;
	}

	public char getAllowFootnoteFlag() {
		return this.allowFootnoteFlag;
	}

	public void setAllowFootnoteFlag(char allowFootnoteFlag) {
		this.allowFootnoteFlag = allowFootnoteFlag;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	public Set getDocumentTypeGroupRefs() {
		return this.documentTypeGroupRefs;
	}

	public void setDocumentTypeGroupRefs(Set documentTypeGroupRefs) {
		this.documentTypeGroupRefs = documentTypeGroupRefs;
	}

}
