package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * EfEffluentLimitQty generated by hbm2java
 */
public class EfEffluentLimitQty implements java.io.Serializable {

	// Fields    

	private EfEffluentLimitQtyId id;

	private EfEffluentLimit efEffluentLimit;

	private String qtyMaxLimit;

	private String qtyAvgLimit;

	private String qtyUnitCode;

	// Constructors

	/** default constructor */
	public EfEffluentLimitQty() {
	}

	/** minimal constructor */
	public EfEffluentLimitQty(EfEffluentLimitQtyId id,
			EfEffluentLimit efEffluentLimit) {
		this.id = id;
		this.efEffluentLimit = efEffluentLimit;
	}

	/** full constructor */
	public EfEffluentLimitQty(EfEffluentLimitQtyId id,
			EfEffluentLimit efEffluentLimit, String qtyMaxLimit,
			String qtyAvgLimit, String qtyUnitCode) {
		this.id = id;
		this.efEffluentLimit = efEffluentLimit;
		this.qtyMaxLimit = qtyMaxLimit;
		this.qtyAvgLimit = qtyAvgLimit;
		this.qtyUnitCode = qtyUnitCode;
	}

	// Property accessors
	public EfEffluentLimitQtyId getId() {
		return this.id;
	}

	public void setId(EfEffluentLimitQtyId id) {
		this.id = id;
	}

	public EfEffluentLimit getEfEffluentLimit() {
		return this.efEffluentLimit;
	}

	public void setEfEffluentLimit(EfEffluentLimit efEffluentLimit) {
		this.efEffluentLimit = efEffluentLimit;
	}

	public String getQtyMaxLimit() {
		return this.qtyMaxLimit;
	}

	public void setQtyMaxLimit(String qtyMaxLimit) {
		this.qtyMaxLimit = qtyMaxLimit;
	}

	public String getQtyAvgLimit() {
		return this.qtyAvgLimit;
	}

	public void setQtyAvgLimit(String qtyAvgLimit) {
		this.qtyAvgLimit = qtyAvgLimit;
	}

	public String getQtyUnitCode() {
		return this.qtyUnitCode;
	}

	public void setQtyUnitCode(String qtyUnitCode) {
		this.qtyUnitCode = qtyUnitCode;
	}

}
