package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EfPermit generated by hbm2java
 */
public class EfPermit implements java.io.Serializable {

	// Fields    

	private String efNpdesPermitNumber;

	private HorizontalCllctnMethodRef horizontalCllctnMethodRef;

	private PermitTypeRef permitTypeRef;

	private LocationDescriptionRef locationDescriptionRef;

	private HorizontalCoordntDatumRef horizontalCoordntDatumRef;

	private String inactiveCode;

	private String countyName;

	private String facilityName;

	private String facilityLocationStreet1;

	private String facilityLocationStreet2;

	private String facilityLocationCity;

	private String facilityLocationStateId;

	private String facilityLocationZip;

	private String pointOfContactAuthorityNm;

	private String pointOfContactName;

	private String pointOfContactPhoneNumber;

	private String pointOfContactStreet1;

	private String pointOfContactStreet2;

	private String pointOfContactCity;

	private String pointOfContactStateId;

	private String pointOfContactZip;

	private BigDecimal latitudeDecimalDegree;

	private Character latitudeDirection;

	private BigDecimal longitudeDecimalDegree;

	private Character longitudeDirection;

	private String scale;

	private String codeOfAccuracy;

	private String receivingWaters;

	private BigDecimal presentDesignFlowRate;

	private String migrationUserid;

	private Date migrationTs;

	private Set efPipeScheds = new HashSet(0);

	private Set permits = new HashSet(0);

	// Constructors

	/** default constructor */
	public EfPermit() {
	}

	/** minimal constructor */
	public EfPermit(String efNpdesPermitNumber, String migrationUserid,
			Date migrationTs) {
		this.efNpdesPermitNumber = efNpdesPermitNumber;
		this.migrationUserid = migrationUserid;
		this.migrationTs = migrationTs;
	}

	/** full constructor */
	public EfPermit(String efNpdesPermitNumber,
			HorizontalCllctnMethodRef horizontalCllctnMethodRef,
			PermitTypeRef permitTypeRef,
			LocationDescriptionRef locationDescriptionRef,
			HorizontalCoordntDatumRef horizontalCoordntDatumRef,
			String inactiveCode, String countyName, String facilityName,
			String facilityLocationStreet1, String facilityLocationStreet2,
			String facilityLocationCity, String facilityLocationStateId,
			String facilityLocationZip, String pointOfContactAuthorityNm,
			String pointOfContactName, String pointOfContactPhoneNumber,
			String pointOfContactStreet1, String pointOfContactStreet2,
			String pointOfContactCity, String pointOfContactStateId,
			String pointOfContactZip, BigDecimal latitudeDecimalDegree,
			Character latitudeDirection, BigDecimal longitudeDecimalDegree,
			Character longitudeDirection, String scale, String codeOfAccuracy,
			String receivingWaters, BigDecimal presentDesignFlowRate,
			String migrationUserid, Date migrationTs, Set efPipeScheds,
			Set permits) {
		this.efNpdesPermitNumber = efNpdesPermitNumber;
		this.horizontalCllctnMethodRef = horizontalCllctnMethodRef;
		this.permitTypeRef = permitTypeRef;
		this.locationDescriptionRef = locationDescriptionRef;
		this.horizontalCoordntDatumRef = horizontalCoordntDatumRef;
		this.inactiveCode = inactiveCode;
		this.countyName = countyName;
		this.facilityName = facilityName;
		this.facilityLocationStreet1 = facilityLocationStreet1;
		this.facilityLocationStreet2 = facilityLocationStreet2;
		this.facilityLocationCity = facilityLocationCity;
		this.facilityLocationStateId = facilityLocationStateId;
		this.facilityLocationZip = facilityLocationZip;
		this.pointOfContactAuthorityNm = pointOfContactAuthorityNm;
		this.pointOfContactName = pointOfContactName;
		this.pointOfContactPhoneNumber = pointOfContactPhoneNumber;
		this.pointOfContactStreet1 = pointOfContactStreet1;
		this.pointOfContactStreet2 = pointOfContactStreet2;
		this.pointOfContactCity = pointOfContactCity;
		this.pointOfContactStateId = pointOfContactStateId;
		this.pointOfContactZip = pointOfContactZip;
		this.latitudeDecimalDegree = latitudeDecimalDegree;
		this.latitudeDirection = latitudeDirection;
		this.longitudeDecimalDegree = longitudeDecimalDegree;
		this.longitudeDirection = longitudeDirection;
		this.scale = scale;
		this.codeOfAccuracy = codeOfAccuracy;
		this.receivingWaters = receivingWaters;
		this.presentDesignFlowRate = presentDesignFlowRate;
		this.migrationUserid = migrationUserid;
		this.migrationTs = migrationTs;
		this.efPipeScheds = efPipeScheds;
		this.permits = permits;
	}

	// Property accessors
	public String getEfNpdesPermitNumber() {
		return this.efNpdesPermitNumber;
	}

	public void setEfNpdesPermitNumber(String efNpdesPermitNumber) {
		this.efNpdesPermitNumber = efNpdesPermitNumber;
	}

	public HorizontalCllctnMethodRef getHorizontalCllctnMethodRef() {
		return this.horizontalCllctnMethodRef;
	}

	public void setHorizontalCllctnMethodRef(
			HorizontalCllctnMethodRef horizontalCllctnMethodRef) {
		this.horizontalCllctnMethodRef = horizontalCllctnMethodRef;
	}

	public PermitTypeRef getPermitTypeRef() {
		return this.permitTypeRef;
	}

	public void setPermitTypeRef(PermitTypeRef permitTypeRef) {
		this.permitTypeRef = permitTypeRef;
	}

	public LocationDescriptionRef getLocationDescriptionRef() {
		return this.locationDescriptionRef;
	}

	public void setLocationDescriptionRef(
			LocationDescriptionRef locationDescriptionRef) {
		this.locationDescriptionRef = locationDescriptionRef;
	}

	public HorizontalCoordntDatumRef getHorizontalCoordntDatumRef() {
		return this.horizontalCoordntDatumRef;
	}

	public void setHorizontalCoordntDatumRef(
			HorizontalCoordntDatumRef horizontalCoordntDatumRef) {
		this.horizontalCoordntDatumRef = horizontalCoordntDatumRef;
	}

	public String getInactiveCode() {
		return this.inactiveCode;
	}

	public void setInactiveCode(String inactiveCode) {
		this.inactiveCode = inactiveCode;
	}

	public String getCountyName() {
		return this.countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	public String getFacilityName() {
		return this.facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getFacilityLocationStreet1() {
		return this.facilityLocationStreet1;
	}

	public void setFacilityLocationStreet1(String facilityLocationStreet1) {
		this.facilityLocationStreet1 = facilityLocationStreet1;
	}

	public String getFacilityLocationStreet2() {
		return this.facilityLocationStreet2;
	}

	public void setFacilityLocationStreet2(String facilityLocationStreet2) {
		this.facilityLocationStreet2 = facilityLocationStreet2;
	}

	public String getFacilityLocationCity() {
		return this.facilityLocationCity;
	}

	public void setFacilityLocationCity(String facilityLocationCity) {
		this.facilityLocationCity = facilityLocationCity;
	}

	public String getFacilityLocationStateId() {
		return this.facilityLocationStateId;
	}

	public void setFacilityLocationStateId(String facilityLocationStateId) {
		this.facilityLocationStateId = facilityLocationStateId;
	}

	public String getFacilityLocationZip() {
		return this.facilityLocationZip;
	}

	public void setFacilityLocationZip(String facilityLocationZip) {
		this.facilityLocationZip = facilityLocationZip;
	}

	public String getPointOfContactAuthorityNm() {
		return this.pointOfContactAuthorityNm;
	}

	public void setPointOfContactAuthorityNm(String pointOfContactAuthorityNm) {
		this.pointOfContactAuthorityNm = pointOfContactAuthorityNm;
	}

	public String getPointOfContactName() {
		return this.pointOfContactName;
	}

	public void setPointOfContactName(String pointOfContactName) {
		this.pointOfContactName = pointOfContactName;
	}

	public String getPointOfContactPhoneNumber() {
		return this.pointOfContactPhoneNumber;
	}

	public void setPointOfContactPhoneNumber(String pointOfContactPhoneNumber) {
		this.pointOfContactPhoneNumber = pointOfContactPhoneNumber;
	}

	public String getPointOfContactStreet1() {
		return this.pointOfContactStreet1;
	}

	public void setPointOfContactStreet1(String pointOfContactStreet1) {
		this.pointOfContactStreet1 = pointOfContactStreet1;
	}

	public String getPointOfContactStreet2() {
		return this.pointOfContactStreet2;
	}

	public void setPointOfContactStreet2(String pointOfContactStreet2) {
		this.pointOfContactStreet2 = pointOfContactStreet2;
	}

	public String getPointOfContactCity() {
		return this.pointOfContactCity;
	}

	public void setPointOfContactCity(String pointOfContactCity) {
		this.pointOfContactCity = pointOfContactCity;
	}

	public String getPointOfContactStateId() {
		return this.pointOfContactStateId;
	}

	public void setPointOfContactStateId(String pointOfContactStateId) {
		this.pointOfContactStateId = pointOfContactStateId;
	}

	public String getPointOfContactZip() {
		return this.pointOfContactZip;
	}

	public void setPointOfContactZip(String pointOfContactZip) {
		this.pointOfContactZip = pointOfContactZip;
	}

	public BigDecimal getLatitudeDecimalDegree() {
		return this.latitudeDecimalDegree;
	}

	public void setLatitudeDecimalDegree(BigDecimal latitudeDecimalDegree) {
		this.latitudeDecimalDegree = latitudeDecimalDegree;
	}

	public Character getLatitudeDirection() {
		return this.latitudeDirection;
	}

	public void setLatitudeDirection(Character latitudeDirection) {
		this.latitudeDirection = latitudeDirection;
	}

	public BigDecimal getLongitudeDecimalDegree() {
		return this.longitudeDecimalDegree;
	}

	public void setLongitudeDecimalDegree(BigDecimal longitudeDecimalDegree) {
		this.longitudeDecimalDegree = longitudeDecimalDegree;
	}

	public Character getLongitudeDirection() {
		return this.longitudeDirection;
	}

	public void setLongitudeDirection(Character longitudeDirection) {
		this.longitudeDirection = longitudeDirection;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getCodeOfAccuracy() {
		return this.codeOfAccuracy;
	}

	public void setCodeOfAccuracy(String codeOfAccuracy) {
		this.codeOfAccuracy = codeOfAccuracy;
	}

	public String getReceivingWaters() {
		return this.receivingWaters;
	}

	public void setReceivingWaters(String receivingWaters) {
		this.receivingWaters = receivingWaters;
	}

	public BigDecimal getPresentDesignFlowRate() {
		return this.presentDesignFlowRate;
	}

	public void setPresentDesignFlowRate(BigDecimal presentDesignFlowRate) {
		this.presentDesignFlowRate = presentDesignFlowRate;
	}

	public String getMigrationUserid() {
		return this.migrationUserid;
	}

	public void setMigrationUserid(String migrationUserid) {
		this.migrationUserid = migrationUserid;
	}

	public Date getMigrationTs() {
		return this.migrationTs;
	}

	public void setMigrationTs(Date migrationTs) {
		this.migrationTs = migrationTs;
	}

	public Set getEfPipeScheds() {
		return this.efPipeScheds;
	}

	public void setEfPipeScheds(Set efPipeScheds) {
		this.efPipeScheds = efPipeScheds;
	}

	public Set getPermits() {
		return this.permits;
	}

	public void setPermits(Set permits) {
		this.permits = permits;
	}

}
