package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * EfPipeSched generated by hbm2java
 */
public class EfPipeSched implements java.io.Serializable {

	// Fields    

	private EfPipeSchedId id;

	private EfPermit efPermit;

	private String outfallTypeCode;

	private String pipeDesc;

	private String pipeInactiveCode;

	private Set efEffluentLimits = new HashSet(0);

	// Constructors

	/** default constructor */
	public EfPipeSched() {
	}

	/** minimal constructor */
	public EfPipeSched(EfPipeSchedId id, EfPermit efPermit) {
		this.id = id;
		this.efPermit = efPermit;
	}

	/** full constructor */
	public EfPipeSched(EfPipeSchedId id, EfPermit efPermit,
			String outfallTypeCode, String pipeDesc, String pipeInactiveCode,
			Set efEffluentLimits) {
		this.id = id;
		this.efPermit = efPermit;
		this.outfallTypeCode = outfallTypeCode;
		this.pipeDesc = pipeDesc;
		this.pipeInactiveCode = pipeInactiveCode;
		this.efEffluentLimits = efEffluentLimits;
	}

	// Property accessors
	public EfPipeSchedId getId() {
		return this.id;
	}

	public void setId(EfPipeSchedId id) {
		this.id = id;
	}

	public EfPermit getEfPermit() {
		return this.efPermit;
	}

	public void setEfPermit(EfPermit efPermit) {
		this.efPermit = efPermit;
	}

	public String getOutfallTypeCode() {
		return this.outfallTypeCode;
	}

	public void setOutfallTypeCode(String outfallTypeCode) {
		this.outfallTypeCode = outfallTypeCode;
	}

	public String getPipeDesc() {
		return this.pipeDesc;
	}

	public void setPipeDesc(String pipeDesc) {
		this.pipeDesc = pipeDesc;
	}

	public String getPipeInactiveCode() {
		return this.pipeInactiveCode;
	}

	public void setPipeInactiveCode(String pipeInactiveCode) {
		this.pipeInactiveCode = pipeInactiveCode;
	}

	public Set getEfEffluentLimits() {
		return this.efEffluentLimits;
	}

	public void setEfEffluentLimits(Set efEffluentLimits) {
		this.efEffluentLimits = efEffluentLimits;
	}

}
