package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityPointOfContact generated by hbm2java
 */
public class FacilityPointOfContact implements java.io.Serializable {

	// Fields    

	private FacilityPointOfContactId id;

	private PointOfContact pointOfContact;

	private Facility facility;

	private char primaryFlag;

	private char superfundRespPartyFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public FacilityPointOfContact() {
	}

	/** full constructor */
	public FacilityPointOfContact(FacilityPointOfContactId id,
			PointOfContact pointOfContact, Facility facility, char primaryFlag,
			char superfundRespPartyFlag, String lastUpdateUserid,
			Date lastUpdateTs, char feedbackDeleteFlag) {
		this.id = id;
		this.pointOfContact = pointOfContact;
		this.facility = facility;
		this.primaryFlag = primaryFlag;
		this.superfundRespPartyFlag = superfundRespPartyFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public FacilityPointOfContactId getId() {
		return this.id;
	}

	public void setId(FacilityPointOfContactId id) {
		this.id = id;
	}

	public PointOfContact getPointOfContact() {
		return this.pointOfContact;
	}

	public void setPointOfContact(PointOfContact pointOfContact) {
		this.pointOfContact = pointOfContact;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public char getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(char primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	public char getSuperfundRespPartyFlag() {
		return this.superfundRespPartyFlag;
	}

	public void setSuperfundRespPartyFlag(char superfundRespPartyFlag) {
		this.superfundRespPartyFlag = superfundRespPartyFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
