package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityCostCurve generated by hbm2java
 */
public class FacilityCostCurve implements java.io.Serializable {

	// Fields    

	private long facilityCostCurveId;

	private CostCurveRef costCurveRef;

	private FacilityDocument facilityDocument;

	private char assignedOrRunCode;

	private char curveRerunFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set costs = new HashSet(0);

	private Set facilityCostCurveDataAreas = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityCostCurve() {
	}

	/** minimal constructor */
	public FacilityCostCurve(long facilityCostCurveId,
			CostCurveRef costCurveRef, FacilityDocument facilityDocument,
			char assignedOrRunCode, char curveRerunFlag,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.facilityCostCurveId = facilityCostCurveId;
		this.costCurveRef = costCurveRef;
		this.facilityDocument = facilityDocument;
		this.assignedOrRunCode = assignedOrRunCode;
		this.curveRerunFlag = curveRerunFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityCostCurve(long facilityCostCurveId,
			CostCurveRef costCurveRef, FacilityDocument facilityDocument,
			char assignedOrRunCode, char curveRerunFlag,
			String lastUpdateUserid, Date lastUpdateTs, Set costs,
			Set facilityCostCurveDataAreas) {
		this.facilityCostCurveId = facilityCostCurveId;
		this.costCurveRef = costCurveRef;
		this.facilityDocument = facilityDocument;
		this.assignedOrRunCode = assignedOrRunCode;
		this.curveRerunFlag = curveRerunFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.costs = costs;
		this.facilityCostCurveDataAreas = facilityCostCurveDataAreas;
	}

	// Property accessors
	public long getFacilityCostCurveId() {
		return this.facilityCostCurveId;
	}

	public void setFacilityCostCurveId(long facilityCostCurveId) {
		this.facilityCostCurveId = facilityCostCurveId;
	}

	public CostCurveRef getCostCurveRef() {
		return this.costCurveRef;
	}

	public void setCostCurveRef(CostCurveRef costCurveRef) {
		this.costCurveRef = costCurveRef;
	}

	public FacilityDocument getFacilityDocument() {
		return this.facilityDocument;
	}

	public void setFacilityDocument(FacilityDocument facilityDocument) {
		this.facilityDocument = facilityDocument;
	}

	public char getAssignedOrRunCode() {
		return this.assignedOrRunCode;
	}

	public void setAssignedOrRunCode(char assignedOrRunCode) {
		this.assignedOrRunCode = assignedOrRunCode;
	}

	public char getCurveRerunFlag() {
		return this.curveRerunFlag;
	}

	public void setCurveRerunFlag(char curveRerunFlag) {
		this.curveRerunFlag = curveRerunFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCosts() {
		return this.costs;
	}

	public void setCosts(Set costs) {
		this.costs = costs;
	}

	public Set getFacilityCostCurveDataAreas() {
		return this.facilityCostCurveDataAreas;
	}

	public void setFacilityCostCurveDataAreas(Set facilityCostCurveDataAreas) {
		this.facilityCostCurveDataAreas = facilityCostCurveDataAreas;
	}

}
