package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityPopulationUnitId generated by hbm2java
 */
public class FacilityPopulationUnitId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long populationId;

	// Constructors

	/** default constructor */
	public FacilityPopulationUnitId() {
	}

	/** full constructor */
	public FacilityPopulationUnitId(long facilityId, long populationId) {
		this.facilityId = facilityId;
		this.populationId = populationId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getPopulationId() {
		return this.populationId;
	}

	public void setPopulationId(long populationId) {
		this.populationId = populationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityPopulationUnitId))
			return false;
		FacilityPopulationUnitId castOther = (FacilityPopulationUnitId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getPopulationId() == castOther.getPopulationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getPopulationId();
		return result;
	}

}
