package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityUnitProcess generated by hbm2java
 */
public class FacilityUnitProcess implements java.io.Serializable {

	// Fields    

	private FacilityUnitProcessId id;

	private TreatmentTypeUnitprocessRef treatmentTypeUnitprocessRef;

	private Facility facility;

	private char presentFlag;

	private char projectedFlag;

	private char backupFlag;

	private Short plannedYear;

	private String description;

	private Byte sortSequence;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityUnitProcessChanges = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityUnitProcess() {
	}

	/** minimal constructor */
	public FacilityUnitProcess(FacilityUnitProcessId id,
			TreatmentTypeUnitprocessRef treatmentTypeUnitprocessRef,
			Facility facility, char presentFlag, char projectedFlag,
			char backupFlag, String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.treatmentTypeUnitprocessRef = treatmentTypeUnitprocessRef;
		this.facility = facility;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.backupFlag = backupFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityUnitProcess(FacilityUnitProcessId id,
			TreatmentTypeUnitprocessRef treatmentTypeUnitprocessRef,
			Facility facility, char presentFlag, char projectedFlag,
			char backupFlag, Short plannedYear, String description,
			Byte sortSequence, String lastUpdateUserid, Date lastUpdateTs,
			Set facilityUnitProcessChanges) {
		this.id = id;
		this.treatmentTypeUnitprocessRef = treatmentTypeUnitprocessRef;
		this.facility = facility;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.backupFlag = backupFlag;
		this.plannedYear = plannedYear;
		this.description = description;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityUnitProcessChanges = facilityUnitProcessChanges;
	}

	// Property accessors
	public FacilityUnitProcessId getId() {
		return this.id;
	}

	public void setId(FacilityUnitProcessId id) {
		this.id = id;
	}

	public TreatmentTypeUnitprocessRef getTreatmentTypeUnitprocessRef() {
		return this.treatmentTypeUnitprocessRef;
	}

	public void setTreatmentTypeUnitprocessRef(
			TreatmentTypeUnitprocessRef treatmentTypeUnitprocessRef) {
		this.treatmentTypeUnitprocessRef = treatmentTypeUnitprocessRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public char getPresentFlag() {
		return this.presentFlag;
	}

	public void setPresentFlag(char presentFlag) {
		this.presentFlag = presentFlag;
	}

	public char getProjectedFlag() {
		return this.projectedFlag;
	}

	public void setProjectedFlag(char projectedFlag) {
		this.projectedFlag = projectedFlag;
	}

	public char getBackupFlag() {
		return this.backupFlag;
	}

	public void setBackupFlag(char backupFlag) {
		this.backupFlag = backupFlag;
	}

	public Short getPlannedYear() {
		return this.plannedYear;
	}

	public void setPlannedYear(Short plannedYear) {
		this.plannedYear = plannedYear;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(Byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityUnitProcessChanges() {
		return this.facilityUnitProcessChanges;
	}

	public void setFacilityUnitProcessChanges(Set facilityUnitProcessChanges) {
		this.facilityUnitProcessChanges = facilityUnitProcessChanges;
	}

}
