package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityReviewStatusId generated by hbm2java
 */
public class FacilityReviewStatusId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private String reviewStatusId;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityReviewStatusId() {
	}

	/** full constructor */
	public FacilityReviewStatusId(long facilityId, String reviewStatusId,
			Date lastUpdateTs) {
		this.facilityId = facilityId;
		this.reviewStatusId = reviewStatusId;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public String getReviewStatusId() {
		return this.reviewStatusId;
	}

	public void setReviewStatusId(String reviewStatusId) {
		this.reviewStatusId = reviewStatusId;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityReviewStatusId))
			return false;
		FacilityReviewStatusId castOther = (FacilityReviewStatusId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& ((this.getReviewStatusId() == castOther
						.getReviewStatusId()) || (this.getReviewStatusId() != null
						&& castOther.getReviewStatusId() != null && this
						.getReviewStatusId().equals(
								castOther.getReviewStatusId())))
				&& ((this.getLastUpdateTs() == castOther.getLastUpdateTs()) || (this
						.getLastUpdateTs() != null
						&& castOther.getLastUpdateTs() != null && this
						.getLastUpdateTs().equals(castOther.getLastUpdateTs())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37
				* result
				+ (getReviewStatusId() == null ? 0 : this
						.getReviewStatusId().hashCode());
		result = 37
				* result
				+ (getLastUpdateTs() == null ? 0 : this.getLastUpdateTs()
						.hashCode());
		return result;
	}

}
