package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityUnitProcessChangeId generated by hbm2java
 */
public class FacilityUnitProcessChangeId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long treatmentTypeId;

	private long unitProcessId;

	private long changeTypeId;

	// Constructors

	/** default constructor */
	public FacilityUnitProcessChangeId() {
	}

	/** full constructor */
	public FacilityUnitProcessChangeId(long facilityId,
			long treatmentTypeId, long unitProcessId, long changeTypeId) {
		this.facilityId = facilityId;
		this.treatmentTypeId = treatmentTypeId;
		this.unitProcessId = unitProcessId;
		this.changeTypeId = changeTypeId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getTreatmentTypeId() {
		return this.treatmentTypeId;
	}

	public void setTreatmentTypeId(long treatmentTypeId) {
		this.treatmentTypeId = treatmentTypeId;
	}

	public long getUnitProcessId() {
		return this.unitProcessId;
	}

	public void setUnitProcessId(long unitProcessId) {
		this.unitProcessId = unitProcessId;
	}

	public long getChangeTypeId() {
		return this.changeTypeId;
	}

	public void setChangeTypeId(long changeTypeId) {
		this.changeTypeId = changeTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityUnitProcessChangeId))
			return false;
		FacilityUnitProcessChangeId castOther = (FacilityUnitProcessChangeId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getTreatmentTypeId() == castOther
						.getTreatmentTypeId())
				&& (this.getUnitProcessId() == castOther.getUnitProcessId())
				&& (this.getChangeTypeId() == castOther.getChangeTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getTreatmentTypeId();
		result = 37 * result + (int) this.getUnitProcessId();
		result = 37 * result + (int) this.getChangeTypeId();
		return result;
	}

}
