package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityDocumentId generated by hbm2java
 */
public class FacilityDocumentId implements java.io.Serializable {

	// Fields

	private long documentId;

	private long facilityId;

	// Constructors

	/** default constructor */
	public FacilityDocumentId() {
	}

	/** full constructor */
	public FacilityDocumentId(long documentId, long facilityId) {
		this.documentId = documentId;
		this.facilityId = facilityId;
	}

	// Property accessors
	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityDocumentId))
			return false;
		FacilityDocumentId castOther = (FacilityDocumentId) other;

		return (this.getDocumentId() == castOther.getDocumentId())
				&& (this.getFacilityId() == castOther.getFacilityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDocumentId();
		result = 37 * result + (int) this.getFacilityId();
		return result;
	}

}
