package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityOverallTypeRef generated by hbm2java
 */
public class FacilityOverallTypeRef implements java.io.Serializable {

	// Fields    

	private long facilityOverallTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityTypeRefs = new HashSet(0);

	private Set treatmentTypeRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityOverallTypeRef() {
	}

	/** minimal constructor */
	public FacilityOverallTypeRef(long facilityOverallTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.facilityOverallTypeId = facilityOverallTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityOverallTypeRef(long facilityOverallTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set facilityTypeRefs,
			Set treatmentTypeRefs) {
		this.facilityOverallTypeId = facilityOverallTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityTypeRefs = facilityTypeRefs;
		this.treatmentTypeRefs = treatmentTypeRefs;
	}

	// Property accessors
	public long getFacilityOverallTypeId() {
		return this.facilityOverallTypeId;
	}

	public void setFacilityOverallTypeId(long facilityOverallTypeId) {
		this.facilityOverallTypeId = facilityOverallTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityTypeRefs() {
		return this.facilityTypeRefs;
	}

	public void setFacilityTypeRefs(Set facilityTypeRefs) {
		this.facilityTypeRefs = facilityTypeRefs;
	}

	public Set getTreatmentTypeRefs() {
		return this.treatmentTypeRefs;
	}

	public void setTreatmentTypeRefs(Set treatmentTypeRefs) {
		this.treatmentTypeRefs = treatmentTypeRefs;
	}

}
