package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityAdvancedTreatmentId generated by hbm2java
 */
public class FacilityAdvancedTreatmentId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long effluentTreatmentLevelId;

	private char presentOrProjectedCode;

	private long advancedTreatmentTypeId;

	// Constructors

	/** default constructor */
	public FacilityAdvancedTreatmentId() {
	}

	/** full constructor */
	public FacilityAdvancedTreatmentId(long facilityId,
			long effluentTreatmentLevelId, char presentOrProjectedCode,
			long advancedTreatmentTypeId) {
		this.facilityId = facilityId;
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
		this.presentOrProjectedCode = presentOrProjectedCode;
		this.advancedTreatmentTypeId = advancedTreatmentTypeId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getEffluentTreatmentLevelId() {
		return this.effluentTreatmentLevelId;
	}

	public void setEffluentTreatmentLevelId(long effluentTreatmentLevelId) {
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
	}

	public char getPresentOrProjectedCode() {
		return this.presentOrProjectedCode;
	}

	public void setPresentOrProjectedCode(char presentOrProjectedCode) {
		this.presentOrProjectedCode = presentOrProjectedCode;
	}

	public long getAdvancedTreatmentTypeId() {
		return this.advancedTreatmentTypeId;
	}

	public void setAdvancedTreatmentTypeId(long advancedTreatmentTypeId) {
		this.advancedTreatmentTypeId = advancedTreatmentTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityAdvancedTreatmentId))
			return false;
		FacilityAdvancedTreatmentId castOther = (FacilityAdvancedTreatmentId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getEffluentTreatmentLevelId() == castOther
						.getEffluentTreatmentLevelId())
				&& (this.getPresentOrProjectedCode() == castOther
						.getPresentOrProjectedCode())
				&& (this.getAdvancedTreatmentTypeId() == castOther
						.getAdvancedTreatmentTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getEffluentTreatmentLevelId();
		result = 37 * result + this.getPresentOrProjectedCode();
		result = 37 * result + (int) this.getAdvancedTreatmentTypeId();
		return result;
	}

}
