package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityAdvancedTreatment generated by hbm2java
 */
public class FacilityAdvancedTreatment implements java.io.Serializable {

	// Fields    

	private FacilityAdvancedTreatmentId id;

	private FacilityEffluent facilityEffluent;

	private AdvancedTreatmentTypeRef advancedTreatmentTypeRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityAdvancedTreatment() {
	}

	/** full constructor */
	public FacilityAdvancedTreatment(FacilityAdvancedTreatmentId id,
			FacilityEffluent facilityEffluent,
			AdvancedTreatmentTypeRef advancedTreatmentTypeRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facilityEffluent = facilityEffluent;
		this.advancedTreatmentTypeRef = advancedTreatmentTypeRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityAdvancedTreatmentId getId() {
		return this.id;
	}

	public void setId(FacilityAdvancedTreatmentId id) {
		this.id = id;
	}

	public FacilityEffluent getFacilityEffluent() {
		return this.facilityEffluent;
	}

	public void setFacilityEffluent(FacilityEffluent facilityEffluent) {
		this.facilityEffluent = facilityEffluent;
	}

	public AdvancedTreatmentTypeRef getAdvancedTreatmentTypeRef() {
		return this.advancedTreatmentTypeRef;
	}

	public void setAdvancedTreatmentTypeRef(
			AdvancedTreatmentTypeRef advancedTreatmentTypeRef) {
		this.advancedTreatmentTypeRef = advancedTreatmentTypeRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
