package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityTypeDischargeRefId generated by hbm2java
 */
public class FacilityTypeDischargeRefId implements java.io.Serializable {

	// Fields

	private long facilityTypeId;

	private long dischargeMethodId;

	// Constructors

	/** default constructor */
	public FacilityTypeDischargeRefId() {
	}

	/** full constructor */
	public FacilityTypeDischargeRefId(long facilityTypeId,
			long dischargeMethodId) {
		this.facilityTypeId = facilityTypeId;
		this.dischargeMethodId = dischargeMethodId;
	}

	// Property accessors
	public long getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(long facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public long getDischargeMethodId() {
		return this.dischargeMethodId;
	}

	public void setDischargeMethodId(long dischargeMethodId) {
		this.dischargeMethodId = dischargeMethodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityTypeDischargeRefId))
			return false;
		FacilityTypeDischargeRefId castOther = (FacilityTypeDischargeRefId) other;

		return (this.getFacilityTypeId() == castOther.getFacilityTypeId())
				&& (this.getDischargeMethodId() == castOther
						.getDischargeMethodId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityTypeId();
		result = 37 * result + (int) this.getDischargeMethodId();
		return result;
	}

}
