package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityUtilMgmtPracticeId generated by hbm2java
 */
public class FacilityUtilMgmtPracticeId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long utilMgmtPracticeId;

	// Constructors

	/** default constructor */
	public FacilityUtilMgmtPracticeId() {
	}

	/** full constructor */
	public FacilityUtilMgmtPracticeId(long facilityId,
			long utilMgmtPracticeId) {
		this.facilityId = facilityId;
		this.utilMgmtPracticeId = utilMgmtPracticeId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getUtilMgmtPracticeId() {
		return this.utilMgmtPracticeId;
	}

	public void setUtilMgmtPracticeId(long utilMgmtPracticeId) {
		this.utilMgmtPracticeId = utilMgmtPracticeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityUtilMgmtPracticeId))
			return false;
		FacilityUtilMgmtPracticeId castOther = (FacilityUtilMgmtPracticeId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getUtilMgmtPracticeId() == castOther
						.getUtilMgmtPracticeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getUtilMgmtPracticeId();
		return result;
	}

}
