package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityTypeRuleRef generated by hbm2java
 */
public class FacilityTypeRuleRef implements java.io.Serializable {

	// Fields

	private FacilityTypeRuleRefId id;

	private FacilityTypeRef facilityTypeRefByFacilityTypeId1;

	private FacilityTypeRef facilityTypeRefByFacilityTypeId2;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityTypeRuleRef() {
	}

	/** full constructor */
	public FacilityTypeRuleRef(FacilityTypeRuleRefId id,
			FacilityTypeRef facilityTypeRefByFacilityTypeId1,
			FacilityTypeRef facilityTypeRefByFacilityTypeId2,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facilityTypeRefByFacilityTypeId1 = facilityTypeRefByFacilityTypeId1;
		this.facilityTypeRefByFacilityTypeId2 = facilityTypeRefByFacilityTypeId2;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityTypeRuleRefId getId() {
		return this.id;
	}

	public void setId(FacilityTypeRuleRefId id) {
		this.id = id;
	}

	public FacilityTypeRef getFacilityTypeRefByFacilityTypeId1() {
		return this.facilityTypeRefByFacilityTypeId1;
	}

	public void setFacilityTypeRefByFacilityTypeId1(
			FacilityTypeRef facilityTypeRefByFacilityTypeId1) {
		this.facilityTypeRefByFacilityTypeId1 = facilityTypeRefByFacilityTypeId1;
	}

	public FacilityTypeRef getFacilityTypeRefByFacilityTypeId2() {
		return this.facilityTypeRefByFacilityTypeId2;
	}

	public void setFacilityTypeRefByFacilityTypeId2(
			FacilityTypeRef facilityTypeRefByFacilityTypeId2) {
		this.facilityTypeRefByFacilityTypeId2 = facilityTypeRefByFacilityTypeId2;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
