package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityEntryStatusId generated by hbm2java
 */
public class FacilityEntryStatusId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long dataAreaId;

	// Constructors

	/** default constructor */
	public FacilityEntryStatusId() {
	}

	/** full constructor */
	public FacilityEntryStatusId(long facilityId, long dataAreaId) {
		this.facilityId = facilityId;
		this.dataAreaId = dataAreaId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getDataAreaId() {
		return this.dataAreaId;
	}

	public void setDataAreaId(long dataAreaId) {
		this.dataAreaId = dataAreaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityEntryStatusId))
			return false;
		FacilityEntryStatusId castOther = (FacilityEntryStatusId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getDataAreaId() == castOther.getDataAreaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getDataAreaId();
		return result;
	}

}
