package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityEffluent generated by hbm2java
 */
public class FacilityEffluent implements java.io.Serializable {

	// Fields    

	private FacilityEffluentId id;

	private Facility facility;

	private EffluentTreatmentLevelRef effluentTreatmentLevelRef;

	private char disinfectionFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityAdvancedTreatments = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityEffluent() {
	}

	/** minimal constructor */
	public FacilityEffluent(FacilityEffluentId id, Facility facility,
			EffluentTreatmentLevelRef effluentTreatmentLevelRef,
			char disinfectionFlag, String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facility = facility;
		this.effluentTreatmentLevelRef = effluentTreatmentLevelRef;
		this.disinfectionFlag = disinfectionFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityEffluent(FacilityEffluentId id, Facility facility,
			EffluentTreatmentLevelRef effluentTreatmentLevelRef,
			char disinfectionFlag, String lastUpdateUserid, Date lastUpdateTs,
			Set facilityAdvancedTreatments) {
		this.id = id;
		this.facility = facility;
		this.effluentTreatmentLevelRef = effluentTreatmentLevelRef;
		this.disinfectionFlag = disinfectionFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityAdvancedTreatments = facilityAdvancedTreatments;
	}

	// Property accessors
	public FacilityEffluentId getId() {
		return this.id;
	}

	public void setId(FacilityEffluentId id) {
		this.id = id;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public EffluentTreatmentLevelRef getEffluentTreatmentLevelRef() {
		return this.effluentTreatmentLevelRef;
	}

	public void setEffluentTreatmentLevelRef(
			EffluentTreatmentLevelRef effluentTreatmentLevelRef) {
		this.effluentTreatmentLevelRef = effluentTreatmentLevelRef;
	}

	public char getDisinfectionFlag() {
		return this.disinfectionFlag;
	}

	public void setDisinfectionFlag(char disinfectionFlag) {
		this.disinfectionFlag = disinfectionFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityAdvancedTreatments() {
		return this.facilityAdvancedTreatments;
	}

	public void setFacilityAdvancedTreatments(Set facilityAdvancedTreatments) {
		this.facilityAdvancedTreatments = facilityAdvancedTreatments;
	}

}
