package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityCostCurveDataAreaId generated by hbm2java
 */
public class FacilityCostCurveDataAreaId implements java.io.Serializable {

	// Fields

	private long facilityCostCurveId;

	private long dataAreaId;

	// Constructors

	/** default constructor */
	public FacilityCostCurveDataAreaId() {
	}

	/** full constructor */
	public FacilityCostCurveDataAreaId(long facilityCostCurveId,
			long dataAreaId) {
		this.facilityCostCurveId = facilityCostCurveId;
		this.dataAreaId = dataAreaId;
	}

	// Property accessors
	public long getFacilityCostCurveId() {
		return this.facilityCostCurveId;
	}

	public void setFacilityCostCurveId(long facilityCostCurveId) {
		this.facilityCostCurveId = facilityCostCurveId;
	}

	public long getDataAreaId() {
		return this.dataAreaId;
	}

	public void setDataAreaId(long dataAreaId) {
		this.dataAreaId = dataAreaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityCostCurveDataAreaId))
			return false;
		FacilityCostCurveDataAreaId castOther = (FacilityCostCurveDataAreaId) other;

		return (this.getFacilityCostCurveId() == castOther
				.getFacilityCostCurveId())
				&& (this.getDataAreaId() == castOther.getDataAreaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityCostCurveId();
		result = 37 * result + (int) this.getDataAreaId();
		return result;
	}

}
