package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityImpairedWater generated by hbm2java
 */
public class FacilityImpairedWater implements java.io.Serializable {

	// Fields    

	private FacilityImpairedWaterId id;

	private ImpairedWater impairedWater;

	private Facility facility;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public FacilityImpairedWater() {
	}

	/** full constructor */
	public FacilityImpairedWater(FacilityImpairedWaterId id,
			ImpairedWater impairedWater, Facility facility,
			String lastUpdateUserid, Date lastUpdateTs, char feedbackDeleteFlag) {
		this.id = id;
		this.impairedWater = impairedWater;
		this.facility = facility;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public FacilityImpairedWaterId getId() {
		return this.id;
	}

	public void setId(FacilityImpairedWaterId id) {
		this.id = id;
	}

	public ImpairedWater getImpairedWater() {
		return this.impairedWater;
	}

	public void setImpairedWater(ImpairedWater impairedWater) {
		this.impairedWater = impairedWater;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
