package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityTypeChangeCcRefId generated by hbm2java
 */
public class FacilityTypeChangeCcRefId implements java.io.Serializable {

	// Fields

	private long costCurveId;

	private long facilityTypeId;

	private long changeTypeId;

	// Constructors

	/** default constructor */
	public FacilityTypeChangeCcRefId() {
	}

	/** full constructor */
	public FacilityTypeChangeCcRefId(long costCurveId, long facilityTypeId,
			long changeTypeId) {
		this.costCurveId = costCurveId;
		this.facilityTypeId = facilityTypeId;
		this.changeTypeId = changeTypeId;
	}

	// Property accessors
	public long getCostCurveId() {
		return this.costCurveId;
	}

	public void setCostCurveId(long costCurveId) {
		this.costCurveId = costCurveId;
	}

	public long getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(long facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public long getChangeTypeId() {
		return this.changeTypeId;
	}

	public void setChangeTypeId(long changeTypeId) {
		this.changeTypeId = changeTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityTypeChangeCcRefId))
			return false;
		FacilityTypeChangeCcRefId castOther = (FacilityTypeChangeCcRefId) other;

		return (this.getCostCurveId() == castOther.getCostCurveId())
				&& (this.getFacilityTypeId() == castOther
						.getFacilityTypeId())
				&& (this.getChangeTypeId() == castOther.getChangeTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCostCurveId();
		result = 37 * result + (int) this.getFacilityTypeId();
		result = 37 * result + (int) this.getChangeTypeId();
		return result;
	}

}
