package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityImpairedWaterId generated by hbm2java
 */
public class FacilityImpairedWaterId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private String listId;

	// Constructors

	/** default constructor */
	public FacilityImpairedWaterId() {
	}

	/** full constructor */
	public FacilityImpairedWaterId(long facilityId, String listId) {
		this.facilityId = facilityId;
		this.listId = listId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public String getListId() {
		return this.listId;
	}

	public void setListId(String listId) {
		this.listId = listId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityImpairedWaterId))
			return false;
		FacilityImpairedWaterId castOther = (FacilityImpairedWaterId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& ((this.getListId() == castOther.getListId()) || (this
						.getListId() != null
						&& castOther.getListId() != null && this
						.getListId().equals(castOther.getListId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result
				+ (getListId() == null ? 0 : this.getListId().hashCode());
		return result;
	}

}
