package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityEffluentId generated by hbm2java
 */
public class FacilityEffluentId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long effluentTreatmentLevelId;

	private char presentOrProjectedCode;

	// Constructors

	/** default constructor */
	public FacilityEffluentId() {
	}

	/** full constructor */
	public FacilityEffluentId(long facilityId,
			long effluentTreatmentLevelId, char presentOrProjectedCode) {
		this.facilityId = facilityId;
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
		this.presentOrProjectedCode = presentOrProjectedCode;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getEffluentTreatmentLevelId() {
		return this.effluentTreatmentLevelId;
	}

	public void setEffluentTreatmentLevelId(long effluentTreatmentLevelId) {
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
	}

	public char getPresentOrProjectedCode() {
		return this.presentOrProjectedCode;
	}

	public void setPresentOrProjectedCode(char presentOrProjectedCode) {
		this.presentOrProjectedCode = presentOrProjectedCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityEffluentId))
			return false;
		FacilityEffluentId castOther = (FacilityEffluentId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getEffluentTreatmentLevelId() == castOther
						.getEffluentTreatmentLevelId())
				&& (this.getPresentOrProjectedCode() == castOther
						.getPresentOrProjectedCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getEffluentTreatmentLevelId();
		result = 37 * result + this.getPresentOrProjectedCode();
		return result;
	}

}
