package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityUnitProcessChange generated by hbm2java
 */
public class FacilityUnitProcessChange implements java.io.Serializable {

	// Fields    

	private FacilityUnitProcessChangeId id;

	private FacilityUnitProcess facilityUnitProcess;

	private ChangeTypeRef changeTypeRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityUnitProcessChange() {
	}

	/** full constructor */
	public FacilityUnitProcessChange(FacilityUnitProcessChangeId id,
			FacilityUnitProcess facilityUnitProcess,
			ChangeTypeRef changeTypeRef, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.facilityUnitProcess = facilityUnitProcess;
		this.changeTypeRef = changeTypeRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityUnitProcessChangeId getId() {
		return this.id;
	}

	public void setId(FacilityUnitProcessChangeId id) {
		this.id = id;
	}

	public FacilityUnitProcess getFacilityUnitProcess() {
		return this.facilityUnitProcess;
	}

	public void setFacilityUnitProcess(FacilityUnitProcess facilityUnitProcess) {
		this.facilityUnitProcess = facilityUnitProcess;
	}

	public ChangeTypeRef getChangeTypeRef() {
		return this.changeTypeRef;
	}

	public void setChangeTypeRef(ChangeTypeRef changeTypeRef) {
		this.changeTypeRef = changeTypeRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
