package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FundingSourceTypeRef generated by hbm2java
 */
public class FundingSourceTypeRef implements java.io.Serializable {

	// Fields    

	private String fundingSourceTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set fundingSources = new HashSet(0);

	// Constructors

	/** default constructor */
	public FundingSourceTypeRef() {
	}

	/** minimal constructor */
	public FundingSourceTypeRef(String fundingSourceTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.fundingSourceTypeId = fundingSourceTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FundingSourceTypeRef(String fundingSourceTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set fundingSources) {
		this.fundingSourceTypeId = fundingSourceTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.fundingSources = fundingSources;
	}

	// Property accessors
	public String getFundingSourceTypeId() {
		return this.fundingSourceTypeId;
	}

	public void setFundingSourceTypeId(String fundingSourceTypeId) {
		this.fundingSourceTypeId = fundingSourceTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFundingSources() {
		return this.fundingSources;
	}

	public void setFundingSources(Set fundingSources) {
		this.fundingSources = fundingSources;
	}

}
