package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * GeographicAreaBoundary generated by hbm2java
 */
public class GeographicAreaBoundary implements java.io.Serializable {

	// Fields    

	private GeographicAreaBoundaryId id;

	private BoundaryRef boundaryRef;

	private GeographicArea geographicArea;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public GeographicAreaBoundary() {
	}

	/** full constructor */
	public GeographicAreaBoundary(GeographicAreaBoundaryId id,
			BoundaryRef boundaryRef, GeographicArea geographicArea,
			String lastUpdateUserid, Date lastUpdateTs, char feedbackDeleteFlag) {
		this.id = id;
		this.boundaryRef = boundaryRef;
		this.geographicArea = geographicArea;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public GeographicAreaBoundaryId getId() {
		return this.id;
	}

	public void setId(GeographicAreaBoundaryId id) {
		this.id = id;
	}

	public BoundaryRef getBoundaryRef() {
		return this.boundaryRef;
	}

	public void setBoundaryRef(BoundaryRef boundaryRef) {
		this.boundaryRef = boundaryRef;
	}

	public GeographicArea getGeographicArea() {
		return this.geographicArea;
	}

	public void setGeographicArea(GeographicArea geographicArea) {
		this.geographicArea = geographicArea;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
