package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * GeographicAreaCounty generated by hbm2java
 */
public class GeographicAreaCounty implements java.io.Serializable {

	// Fields    

	private GeographicAreaCountyId id;

	private GeographicArea geographicArea;

	private CountyRef countyRef;

	private char primaryFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public GeographicAreaCounty() {
	}

	/** full constructor */
	public GeographicAreaCounty(GeographicAreaCountyId id,
			GeographicArea geographicArea, CountyRef countyRef,
			char primaryFlag, String lastUpdateUserid, Date lastUpdateTs,
			char feedbackDeleteFlag) {
		this.id = id;
		this.geographicArea = geographicArea;
		this.countyRef = countyRef;
		this.primaryFlag = primaryFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public GeographicAreaCountyId getId() {
		return this.id;
	}

	public void setId(GeographicAreaCountyId id) {
		this.id = id;
	}

	public GeographicArea getGeographicArea() {
		return this.geographicArea;
	}

	public void setGeographicArea(GeographicArea geographicArea) {
		this.geographicArea = geographicArea;
	}

	public CountyRef getCountyRef() {
		return this.countyRef;
	}

	public void setCountyRef(CountyRef countyRef) {
		this.countyRef = countyRef;
	}

	public char getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(char primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
