package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * GeographicAreaWatershed generated by hbm2java
 */
public class GeographicAreaWatershed implements java.io.Serializable {

	// Fields    

	private GeographicAreaWatershedId id;

	private GeographicArea geographicArea;

	private WatershedRef watershedRef;

	private char primaryFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public GeographicAreaWatershed() {
	}

	/** full constructor */
	public GeographicAreaWatershed(GeographicAreaWatershedId id,
			GeographicArea geographicArea, WatershedRef watershedRef,
			char primaryFlag, String lastUpdateUserid, Date lastUpdateTs,
			char feedbackDeleteFlag) {
		this.id = id;
		this.geographicArea = geographicArea;
		this.watershedRef = watershedRef;
		this.primaryFlag = primaryFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public GeographicAreaWatershedId getId() {
		return this.id;
	}

	public void setId(GeographicAreaWatershedId id) {
		this.id = id;
	}

	public GeographicArea getGeographicArea() {
		return this.geographicArea;
	}

	public void setGeographicArea(GeographicArea geographicArea) {
		this.geographicArea = geographicArea;
	}

	public WatershedRef getWatershedRef() {
		return this.watershedRef;
	}

	public void setWatershedRef(WatershedRef watershedRef) {
		this.watershedRef = watershedRef;
	}

	public char getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(char primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
