package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * ImportCbrProjectinformatn generated by hbm2java
 */
public class ImportCbrProjectinformatn implements java.io.Serializable {

	// Fields    

	private ImportCbrProjectinformatnId id;

	// Constructors

	/** default constructor */
	public ImportCbrProjectinformatn() {
	}

	/** full constructor */
	public ImportCbrProjectinformatn(ImportCbrProjectinformatnId id) {
		this.id = id;
	}

	// Property accessors
	public ImportCbrProjectinformatnId getId() {
		return this.id;
	}

	public void setId(ImportCbrProjectinformatnId id) {
		this.id = id;
	}

}
