package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * MtDomainValueMap generated by hbm2java
 */
public class MtDomainValueMap implements java.io.Serializable {

	// Fields    

	private MtDomainValueMapId id;

	// Constructors

	/** default constructor */
	public MtDomainValueMap() {
	}

	/** full constructor */
	public MtDomainValueMap(MtDomainValueMapId id) {
		this.id = id;
	}

	// Property accessors
	public MtDomainValueMapId getId() {
		return this.id;
	}

	public void setId(MtDomainValueMapId id) {
		this.id = id;
	}

}
