package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsEffluentLimitConcentr generated by hbm2java
 */
public class PcsEffluentLimitConcentr implements java.io.Serializable {

	// Fields    

	private PcsEffluentLimitConcentrId id;

	private PcsEffluentLimit pcsEffluentLimit;

	private String concentrMaxLimit;

	private String concentrAvgLimit;

	private String concentrMinLimit;

	private String concentrUnitCode;

	private String statLimAvgOverride;

	private String statLimMinOverride;

	private String concentrMinLimStatBase;

	private String concentrAvgLimStatBase;

	private String concentrMaxLimStatBase;

	// Constructors

	/** default constructor */
	public PcsEffluentLimitConcentr() {
	}

	/** minimal constructor */
	public PcsEffluentLimitConcentr(PcsEffluentLimitConcentrId id,
			PcsEffluentLimit pcsEffluentLimit) {
		this.id = id;
		this.pcsEffluentLimit = pcsEffluentLimit;
	}

	/** full constructor */
	public PcsEffluentLimitConcentr(PcsEffluentLimitConcentrId id,
			PcsEffluentLimit pcsEffluentLimit, String concentrMaxLimit,
			String concentrAvgLimit, String concentrMinLimit,
			String concentrUnitCode, String statLimAvgOverride,
			String statLimMinOverride, String concentrMinLimStatBase,
			String concentrAvgLimStatBase, String concentrMaxLimStatBase) {
		this.id = id;
		this.pcsEffluentLimit = pcsEffluentLimit;
		this.concentrMaxLimit = concentrMaxLimit;
		this.concentrAvgLimit = concentrAvgLimit;
		this.concentrMinLimit = concentrMinLimit;
		this.concentrUnitCode = concentrUnitCode;
		this.statLimAvgOverride = statLimAvgOverride;
		this.statLimMinOverride = statLimMinOverride;
		this.concentrMinLimStatBase = concentrMinLimStatBase;
		this.concentrAvgLimStatBase = concentrAvgLimStatBase;
		this.concentrMaxLimStatBase = concentrMaxLimStatBase;
	}

	// Property accessors
	public PcsEffluentLimitConcentrId getId() {
		return this.id;
	}

	public void setId(PcsEffluentLimitConcentrId id) {
		this.id = id;
	}

	public PcsEffluentLimit getPcsEffluentLimit() {
		return this.pcsEffluentLimit;
	}

	public void setPcsEffluentLimit(PcsEffluentLimit pcsEffluentLimit) {
		this.pcsEffluentLimit = pcsEffluentLimit;
	}

	public String getConcentrMaxLimit() {
		return this.concentrMaxLimit;
	}

	public void setConcentrMaxLimit(String concentrMaxLimit) {
		this.concentrMaxLimit = concentrMaxLimit;
	}

	public String getConcentrAvgLimit() {
		return this.concentrAvgLimit;
	}

	public void setConcentrAvgLimit(String concentrAvgLimit) {
		this.concentrAvgLimit = concentrAvgLimit;
	}

	public String getConcentrMinLimit() {
		return this.concentrMinLimit;
	}

	public void setConcentrMinLimit(String concentrMinLimit) {
		this.concentrMinLimit = concentrMinLimit;
	}

	public String getConcentrUnitCode() {
		return this.concentrUnitCode;
	}

	public void setConcentrUnitCode(String concentrUnitCode) {
		this.concentrUnitCode = concentrUnitCode;
	}

	public String getStatLimAvgOverride() {
		return this.statLimAvgOverride;
	}

	public void setStatLimAvgOverride(String statLimAvgOverride) {
		this.statLimAvgOverride = statLimAvgOverride;
	}

	public String getStatLimMinOverride() {
		return this.statLimMinOverride;
	}

	public void setStatLimMinOverride(String statLimMinOverride) {
		this.statLimMinOverride = statLimMinOverride;
	}

	public String getConcentrMinLimStatBase() {
		return this.concentrMinLimStatBase;
	}

	public void setConcentrMinLimStatBase(String concentrMinLimStatBase) {
		this.concentrMinLimStatBase = concentrMinLimStatBase;
	}

	public String getConcentrAvgLimStatBase() {
		return this.concentrAvgLimStatBase;
	}

	public void setConcentrAvgLimStatBase(String concentrAvgLimStatBase) {
		this.concentrAvgLimStatBase = concentrAvgLimStatBase;
	}

	public String getConcentrMaxLimStatBase() {
		return this.concentrMaxLimStatBase;
	}

	public void setConcentrMaxLimStatBase(String concentrMaxLimStatBase) {
		this.concentrMaxLimStatBase = concentrMaxLimStatBase;
	}

}
