package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsEffluentLimitQtyId generated by hbm2java
 */
public class PcsEffluentLimitQtyId implements java.io.Serializable {

	// Fields    

	private String npdes;

	private String dischargeNum;

	private String reportDesig;

	private char pipeSetQualifier;

	private String limitType;

	private String paramCode;

	private String monitoringLoc;

	private String seasonNum;

	private String modifNum;

	// Constructors

	/** default constructor */
	public PcsEffluentLimitQtyId() {
	}

	/** full constructor */
	public PcsEffluentLimitQtyId(String npdes, String dischargeNum,
			String reportDesig, char pipeSetQualifier, String limitType,
			String paramCode, String monitoringLoc, String seasonNum,
			String modifNum) {
		this.npdes = npdes;
		this.dischargeNum = dischargeNum;
		this.reportDesig = reportDesig;
		this.pipeSetQualifier = pipeSetQualifier;
		this.limitType = limitType;
		this.paramCode = paramCode;
		this.monitoringLoc = monitoringLoc;
		this.seasonNum = seasonNum;
		this.modifNum = modifNum;
	}

	// Property accessors
	public String getNpdes() {
		return this.npdes;
	}

	public void setNpdes(String npdes) {
		this.npdes = npdes;
	}

	public String getDischargeNum() {
		return this.dischargeNum;
	}

	public void setDischargeNum(String dischargeNum) {
		this.dischargeNum = dischargeNum;
	}

	public String getReportDesig() {
		return this.reportDesig;
	}

	public void setReportDesig(String reportDesig) {
		this.reportDesig = reportDesig;
	}

	public char getPipeSetQualifier() {
		return this.pipeSetQualifier;
	}

	public void setPipeSetQualifier(char pipeSetQualifier) {
		this.pipeSetQualifier = pipeSetQualifier;
	}

	public String getLimitType() {
		return this.limitType;
	}

	public void setLimitType(String limitType) {
		this.limitType = limitType;
	}

	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}

	public String getMonitoringLoc() {
		return this.monitoringLoc;
	}

	public void setMonitoringLoc(String monitoringLoc) {
		this.monitoringLoc = monitoringLoc;
	}

	public String getSeasonNum() {
		return this.seasonNum;
	}

	public void setSeasonNum(String seasonNum) {
		this.seasonNum = seasonNum;
	}

	public String getModifNum() {
		return this.modifNum;
	}

	public void setModifNum(String modifNum) {
		this.modifNum = modifNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PcsEffluentLimitQtyId))
			return false;
		PcsEffluentLimitQtyId castOther = (PcsEffluentLimitQtyId) other;

		return ((this.getNpdes() == castOther.getNpdes()) || (this.getNpdes() != null
				&& castOther.getNpdes() != null && this.getNpdes().equals(
				castOther.getNpdes())))
				&& ((this.getDischargeNum() == castOther.getDischargeNum()) || (this
						.getDischargeNum() != null
						&& castOther.getDischargeNum() != null && this
						.getDischargeNum().equals(castOther.getDischargeNum())))
				&& ((this.getReportDesig() == castOther.getReportDesig()) || (this
						.getReportDesig() != null
						&& castOther.getReportDesig() != null && this
						.getReportDesig().equals(castOther.getReportDesig())))
				&& (this.getPipeSetQualifier() == castOther
						.getPipeSetQualifier())
				&& ((this.getLimitType() == castOther.getLimitType()) || (this
						.getLimitType() != null
						&& castOther.getLimitType() != null && this
						.getLimitType().equals(castOther.getLimitType())))
				&& ((this.getParamCode() == castOther.getParamCode()) || (this
						.getParamCode() != null
						&& castOther.getParamCode() != null && this
						.getParamCode().equals(castOther.getParamCode())))
				&& ((this.getMonitoringLoc() == castOther.getMonitoringLoc()) || (this
						.getMonitoringLoc() != null
						&& castOther.getMonitoringLoc() != null && this
						.getMonitoringLoc()
						.equals(castOther.getMonitoringLoc())))
				&& ((this.getSeasonNum() == castOther.getSeasonNum()) || (this
						.getSeasonNum() != null
						&& castOther.getSeasonNum() != null && this
						.getSeasonNum().equals(castOther.getSeasonNum())))
				&& ((this.getModifNum() == castOther.getModifNum()) || (this
						.getModifNum() != null
						&& castOther.getModifNum() != null && this
						.getModifNum().equals(castOther.getModifNum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNpdes() == null ? 0 : this.getNpdes().hashCode());
		result = 37
				* result
				+ (getDischargeNum() == null ? 0 : this.getDischargeNum()
						.hashCode());
		result = 37
				* result
				+ (getReportDesig() == null ? 0 : this.getReportDesig()
						.hashCode());
		result = 37 * result + this.getPipeSetQualifier();
		result = 37 * result
				+ (getLimitType() == null ? 0 : this.getLimitType().hashCode());
		result = 37 * result
				+ (getParamCode() == null ? 0 : this.getParamCode().hashCode());
		result = 37
				* result
				+ (getMonitoringLoc() == null ? 0 : this.getMonitoringLoc()
						.hashCode());
		result = 37 * result
				+ (getSeasonNum() == null ? 0 : this.getSeasonNum().hashCode());
		result = 37 * result
				+ (getModifNum() == null ? 0 : this.getModifNum().hashCode());
		return result;
	}

}
