package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PermitTypeRef generated by hbm2java
 */
public class PermitTypeRef implements java.io.Serializable {

	// Fields    

	private long permitTypeId;

	private String code;

	private String name;

	private char npdesFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set permits = new HashSet(0);

	private Set efPermits = new HashSet(0);

	// Constructors

	/** default constructor */
	public PermitTypeRef() {
	}

	/** minimal constructor */
	public PermitTypeRef(long permitTypeId, String code, String name,
			char npdesFlag, String lastUpdateUserid, Date lastUpdateTs) {
		this.permitTypeId = permitTypeId;
		this.code = code;
		this.name = name;
		this.npdesFlag = npdesFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public PermitTypeRef(long permitTypeId, String code, String name,
			char npdesFlag, String lastUpdateUserid, Date lastUpdateTs,
			Set permits, Set efPermits) {
		this.permitTypeId = permitTypeId;
		this.code = code;
		this.name = name;
		this.npdesFlag = npdesFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.permits = permits;
		this.efPermits = efPermits;
	}

	// Property accessors
	public long getPermitTypeId() {
		return this.permitTypeId;
	}

	public void setPermitTypeId(long permitTypeId) {
		this.permitTypeId = permitTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getNpdesFlag() {
		return this.npdesFlag;
	}

	public void setNpdesFlag(char npdesFlag) {
		this.npdesFlag = npdesFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getPermits() {
		return this.permits;
	}

	public void setPermits(Set permits) {
		this.permits = permits;
	}

	public Set getEfPermits() {
		return this.efPermits;
	}

	public void setEfPermits(Set efPermits) {
		this.efPermits = efPermits;
	}

}
