package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PointOfContact generated by hbm2java
 */
public class PointOfContact implements java.io.Serializable {

	// Fields    

	private long pointOfContactId;

	private char sourcedFromNpdesFlag;

	private String name;

	private String authorityName;

	private String roleTitle;

	private String streetAddress1;

	private String streetAddress2;

	private String city;

	private String county;

	private String stateId;

	private String zip;

	private String phone;

	private String fax;

	private String email;

	private char tribeFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityPointOfContacts = new HashSet(0);

	// Constructors

	/** default constructor */
	public PointOfContact() {
	}

	/** minimal constructor */
	public PointOfContact(long pointOfContactId, char sourcedFromNpdesFlag,
			String authorityName, String stateId, char tribeFlag,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.pointOfContactId = pointOfContactId;
		this.sourcedFromNpdesFlag = sourcedFromNpdesFlag;
		this.authorityName = authorityName;
		this.stateId = stateId;
		this.tribeFlag = tribeFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public PointOfContact(long pointOfContactId, char sourcedFromNpdesFlag,
			String name, String authorityName, String roleTitle,
			String streetAddress1, String streetAddress2, String city,
			String county, String stateId, String zip, String phone,
			String fax, String email, char tribeFlag, String lastUpdateUserid,
			Date lastUpdateTs, Set facilityPointOfContacts) {
		this.pointOfContactId = pointOfContactId;
		this.sourcedFromNpdesFlag = sourcedFromNpdesFlag;
		this.name = name;
		this.authorityName = authorityName;
		this.roleTitle = roleTitle;
		this.streetAddress1 = streetAddress1;
		this.streetAddress2 = streetAddress2;
		this.city = city;
		this.county = county;
		this.stateId = stateId;
		this.zip = zip;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.tribeFlag = tribeFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityPointOfContacts = facilityPointOfContacts;
	}

	// Property accessors
	public long getPointOfContactId() {
		return this.pointOfContactId;
	}

	public void setPointOfContactId(long pointOfContactId) {
		this.pointOfContactId = pointOfContactId;
	}

	public char getSourcedFromNpdesFlag() {
		return this.sourcedFromNpdesFlag;
	}

	public void setSourcedFromNpdesFlag(char sourcedFromNpdesFlag) {
		this.sourcedFromNpdesFlag = sourcedFromNpdesFlag;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAuthorityName() {
		return this.authorityName;
	}

	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName;
	}

	public String getRoleTitle() {
		return this.roleTitle;
	}

	public void setRoleTitle(String roleTitle) {
		this.roleTitle = roleTitle;
	}

	public String getStreetAddress1() {
		return this.streetAddress1;
	}

	public void setStreetAddress1(String streetAddress1) {
		this.streetAddress1 = streetAddress1;
	}

	public String getStreetAddress2() {
		return this.streetAddress2;
	}

	public void setStreetAddress2(String streetAddress2) {
		this.streetAddress2 = streetAddress2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getStateId() {
		return this.stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public char getTribeFlag() {
		return this.tribeFlag;
	}

	public void setTribeFlag(char tribeFlag) {
		this.tribeFlag = tribeFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityPointOfContacts() {
		return this.facilityPointOfContacts;
	}

	public void setFacilityPointOfContacts(Set facilityPointOfContacts) {
		this.facilityPointOfContacts = facilityPointOfContacts;
	}

}
