package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * System generated by hbm2java
 */
public class System implements java.io.Serializable {

	// Fields    

	private long systemId;

	private String locationId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilities = new HashSet(0);

	// Constructors

	/** default constructor */
	public System() {
	}

	/** minimal constructor */
	public System(long systemId, String locationId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.systemId = systemId;
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public System(long systemId, String locationId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set facilities) {
		this.systemId = systemId;
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilities = facilities;
	}

	// Property accessors
	public long getSystemId() {
		return this.systemId;
	}

	public void setSystemId(long systemId) {
		this.systemId = systemId;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilities() {
		return this.facilities;
	}

	public void setFacilities(Set facilities) {
		this.facilities = facilities;
	}

}
