package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * TreatmentTypeUnitprocessRefId generated by hbm2java
 */
public class TreatmentTypeUnitprocessRefId implements java.io.Serializable {

	// Fields

	private long treatmentTypeId;

	private long unitProcessId;

	// Constructors

	/** default constructor */
	public TreatmentTypeUnitprocessRefId() {
	}

	/** full constructor */
	public TreatmentTypeUnitprocessRefId(long treatmentTypeId,
			long unitProcessId) {
		this.treatmentTypeId = treatmentTypeId;
		this.unitProcessId = unitProcessId;
	}

	// Property accessors
	public long getTreatmentTypeId() {
		return this.treatmentTypeId;
	}

	public void setTreatmentTypeId(long treatmentTypeId) {
		this.treatmentTypeId = treatmentTypeId;
	}

	public long getUnitProcessId() {
		return this.unitProcessId;
	}

	public void setUnitProcessId(long unitProcessId) {
		this.unitProcessId = unitProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TreatmentTypeUnitprocessRefId))
			return false;
		TreatmentTypeUnitprocessRefId castOther = (TreatmentTypeUnitprocessRefId) other;

		return (this.getTreatmentTypeId() == castOther.getTreatmentTypeId())
				&& (this.getUnitProcessId() == castOther.getUnitProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTreatmentTypeId();
		result = 37 * result + (int) this.getUnitProcessId();
		return result;
	}

}
