package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * WatershedLocationRefId generated by hbm2java
 */
public class WatershedLocationRefId implements java.io.Serializable {

	// Fields

	private String watershedId;

	private String locationId;

	// Constructors

	/** default constructor */
	public WatershedLocationRefId() {
	}

	/** full constructor */
	public WatershedLocationRefId(String watershedId, String locationId) {
		this.watershedId = watershedId;
		this.locationId = locationId;
	}

	// Property accessors
	public String getWatershedId() {
		return this.watershedId;
	}

	public void setWatershedId(String watershedId) {
		this.watershedId = watershedId;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WatershedLocationRefId))
			return false;
		WatershedLocationRefId castOther = (WatershedLocationRefId) other;

		return (this.getWatershedId() == castOther.getWatershedId())
				&& ((this.getLocationId() == castOther.getLocationId()) || (this
						.getLocationId() != null
						&& castOther.getLocationId() != null && this
						.getLocationId().equals(castOther.getLocationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + getWatershedId() == null ? 0 : this.getWatershedId().hashCode();
		result = 37
				* result
				+ (getLocationId() == null ? 0 : this.getLocationId()
						.hashCode());
		return result;
	}

}
