package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * WatershedLocationRef generated by hbm2java
 */
public class WatershedLocationRef implements java.io.Serializable {

	// Fields    

	private WatershedLocationRefId id;

	private WatershedRef watershedRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public WatershedLocationRef() {
	}

	/** full constructor */
	public WatershedLocationRef(WatershedLocationRefId id,
			WatershedRef watershedRef, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.watershedRef = watershedRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public WatershedLocationRefId getId() {
		return this.id;
	}

	public void setId(WatershedLocationRefId id) {
		this.id = id;
	}

	public WatershedRef getWatershedRef() {
		return this.watershedRef;
	}

	public void setWatershedRef(WatershedRef watershedRef) {
		this.watershedRef = watershedRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
