package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * AccessLevelAssignedByRefId generated by hbm2java
 */
public class AccessLevelAssignedByRefId implements java.io.Serializable {

	// Fields

	private long accessLevelId;

	private String locationTypeId;

	// Constructors

	/** default constructor */
	public AccessLevelAssignedByRefId() {
	}

	/** full constructor */
	public AccessLevelAssignedByRefId(long accessLevelId,
			String locationTypeId) {
		this.accessLevelId = accessLevelId;
		this.locationTypeId = locationTypeId;
	}

	// Property accessors
	public long getAccessLevelId() {
		return this.accessLevelId;
	}

	public void setAccessLevelId(long accessLevelId) {
		this.accessLevelId = accessLevelId;
	}

	public String getLocationTypeId() {
		return this.locationTypeId;
	}

	public void setLocationTypeId(String locationTypeId) {
		this.locationTypeId = locationTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccessLevelAssignedByRefId))
			return false;
		AccessLevelAssignedByRefId castOther = (AccessLevelAssignedByRefId) other;

		return (this.getAccessLevelId() == castOther.getAccessLevelId())
				&& ((this.getLocationTypeId() == castOther
						.getLocationTypeId()) || (this.getLocationTypeId() != null
						&& castOther.getLocationTypeId() != null && this
						.getLocationTypeId().equals(
								castOther.getLocationTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAccessLevelId();
		result = 37
				* result
				+ (getLocationTypeId() == null ? 0 : this
						.getLocationTypeId().hashCode());
		return result;
	}

}
