package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AccessLevelRef generated by hbm2java
 */
public class AccessLevelRef implements java.io.Serializable {

	// Fields    

	private long accessLevelId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set cwnsUserLocatnAccessLevels = new HashSet(0);

	private Set accessLevelAppliesToRefs = new HashSet(0);

	private Set accessLevelAssignedByRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public AccessLevelRef() {
	}

	/** minimal constructor */
	public AccessLevelRef(long accessLevelId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.accessLevelId = accessLevelId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public AccessLevelRef(long accessLevelId, String name,
			String lastUpdateUserid, Date lastUpdateTs,
			Set cwnsUserLocatnAccessLevels, Set accessLevelAppliesToRefs,
			Set accessLevelAssignedByRefs) {
		this.accessLevelId = accessLevelId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.cwnsUserLocatnAccessLevels = cwnsUserLocatnAccessLevels;
		this.accessLevelAppliesToRefs = accessLevelAppliesToRefs;
		this.accessLevelAssignedByRefs = accessLevelAssignedByRefs;
	}

	// Property accessors
	public long getAccessLevelId() {
		return this.accessLevelId;
	}

	public void setAccessLevelId(long accessLevelId) {
		this.accessLevelId = accessLevelId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCwnsUserLocatnAccessLevels() {
		return this.cwnsUserLocatnAccessLevels;
	}

	public void setCwnsUserLocatnAccessLevels(Set cwnsUserLocatnAccessLevels) {
		this.cwnsUserLocatnAccessLevels = cwnsUserLocatnAccessLevels;
	}

	public Set getAccessLevelAppliesToRefs() {
		return this.accessLevelAppliesToRefs;
	}

	public void setAccessLevelAppliesToRefs(Set accessLevelAppliesToRefs) {
		this.accessLevelAppliesToRefs = accessLevelAppliesToRefs;
	}

	public Set getAccessLevelAssignedByRefs() {
		return this.accessLevelAssignedByRefs;
	}

	public void setAccessLevelAssignedByRefs(Set accessLevelAssignedByRefs) {
		this.accessLevelAssignedByRefs = accessLevelAssignedByRefs;
	}

}
