package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdministrativeMessageRef generated by hbm2java
 */
public class AdministrativeMessageRef implements java.io.Serializable {

	// Fields    

	private long administrativeMessageId;

	private String code;

	private String description;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set announcements = new HashSet(0);

	// Constructors

	/** default constructor */
	public AdministrativeMessageRef() {
	}

	/** minimal constructor */
	public AdministrativeMessageRef(long administrativeMessageId, String code,
			String description, String lastUpdateUserid, Date lastUpdateTs) {
		this.administrativeMessageId = administrativeMessageId;
		this.code = code;
		this.description = description;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public AdministrativeMessageRef(long administrativeMessageId, String code,
			String description, String lastUpdateUserid, Date lastUpdateTs,
			Set announcements) {
		this.administrativeMessageId = administrativeMessageId;
		this.code = code;
		this.description = description;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.announcements = announcements;
	}

	// Property accessors
	public long getAdministrativeMessageId() {
		return this.administrativeMessageId;
	}

	public void setAdministrativeMessageId(long administrativeMessageId) {
		this.administrativeMessageId = administrativeMessageId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getAnnouncements() {
		return this.announcements;
	}

	public void setAnnouncements(Set announcements) {
		this.announcements = announcements;
	}

}
