package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AdvancedTreatmentTypeRef generated by hbm2java
 */
public class AdvancedTreatmentTypeRef implements java.io.Serializable {

	// Fields    

	private long advancedTreatmentTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityAdvancedTreatments = new HashSet(0);

	// Constructors

	/** default constructor */
	public AdvancedTreatmentTypeRef() {
	}

	/** minimal constructor */
	public AdvancedTreatmentTypeRef(long advancedTreatmentTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.advancedTreatmentTypeId = advancedTreatmentTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public AdvancedTreatmentTypeRef(long advancedTreatmentTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs,
			Set facilityAdvancedTreatments) {
		this.advancedTreatmentTypeId = advancedTreatmentTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityAdvancedTreatments = facilityAdvancedTreatments;
	}

	// Property accessors
	public long getAdvancedTreatmentTypeId() {
		return this.advancedTreatmentTypeId;
	}

	public void setAdvancedTreatmentTypeId(long advancedTreatmentTypeId) {
		this.advancedTreatmentTypeId = advancedTreatmentTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityAdvancedTreatments() {
		return this.facilityAdvancedTreatments;
	}

	public void setFacilityAdvancedTreatments(Set facilityAdvancedTreatments) {
		this.facilityAdvancedTreatments = facilityAdvancedTreatments;
	}

}
