package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BoundaryTypeRef generated by hbm2java
 */
public class BoundaryTypeRef implements java.io.Serializable {

	// Fields    

	private long boundaryTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set boundaryRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public BoundaryTypeRef() {
	}

	/** minimal constructor */
	public BoundaryTypeRef(long boundaryTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.boundaryTypeId = boundaryTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public BoundaryTypeRef(long boundaryTypeId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set boundaryRefs) {
		this.boundaryTypeId = boundaryTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.boundaryRefs = boundaryRefs;
	}

	// Property accessors
	public long getBoundaryTypeId() {
		return this.boundaryTypeId;
	}

	public void setBoundaryTypeId(long boundaryTypeId) {
		this.boundaryTypeId = boundaryTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getBoundaryRefs() {
		return this.boundaryRefs;
	}

	public void setBoundaryRefs(Set boundaryRefs) {
		this.boundaryRefs = boundaryRefs;
	}

}
