package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * BoundaryLocationRefId generated by hbm2java
 */
public class BoundaryLocationRefId implements java.io.Serializable {

	// Fields

	private long boundaryId;

	private String locationId;

	// Constructors

	/** default constructor */
	public BoundaryLocationRefId() {
	}

	/** full constructor */
	public BoundaryLocationRefId(long boundaryId, String locationId) {
		this.boundaryId = boundaryId;
		this.locationId = locationId;
	}

	// Property accessors
	public long getBoundaryId() {
		return this.boundaryId;
	}

	public void setBoundaryId(long boundaryId) {
		this.boundaryId = boundaryId;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoundaryLocationRefId))
			return false;
		BoundaryLocationRefId castOther = (BoundaryLocationRefId) other;

		return (this.getBoundaryId() == castOther.getBoundaryId())
				&& ((this.getLocationId() == castOther.getLocationId()) || (this
						.getLocationId() != null
						&& castOther.getLocationId() != null && this
						.getLocationId().equals(castOther.getLocationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBoundaryId();
		result = 37
				* result
				+ (getLocationId() == null ? 0 : this.getLocationId()
						.hashCode());
		return result;
	}

}
