package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CategoryRef generated by hbm2java
 */
public class CategoryRef implements java.io.Serializable {

	// Fields    

	private String categoryId;

	private String name;

	private char validForSsoFlag;

	private byte sortSequence;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityTypeCategoryRefs = new HashSet(0);

	private Set costCurveCategoryRefs = new HashSet(0);

	private Set categoryClassificationRefs = new HashSet(0);

	private Set costs = new HashSet(0);

	// Constructors

	/** default constructor */
	public CategoryRef() {
	}

	/** minimal constructor */
	public CategoryRef(String categoryId, String name, char validForSsoFlag,
			byte sortSequence, String lastUpdateUserid, Date lastUpdateTs) {
		this.categoryId = categoryId;
		this.name = name;
		this.validForSsoFlag = validForSsoFlag;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CategoryRef(String categoryId, String name, char validForSsoFlag,
			byte sortSequence, String lastUpdateUserid, Date lastUpdateTs,
			Set facilityTypeCategoryRefs, Set costCurveCategoryRefs,
			Set categoryClassificationRefs, Set costs) {
		this.categoryId = categoryId;
		this.name = name;
		this.validForSsoFlag = validForSsoFlag;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityTypeCategoryRefs = facilityTypeCategoryRefs;
		this.costCurveCategoryRefs = costCurveCategoryRefs;
		this.categoryClassificationRefs = categoryClassificationRefs;
		this.costs = costs;
	}

	// Property accessors
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getValidForSsoFlag() {
		return this.validForSsoFlag;
	}

	public void setValidForSsoFlag(char validForSsoFlag) {
		this.validForSsoFlag = validForSsoFlag;
	}

	public byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityTypeCategoryRefs() {
		return this.facilityTypeCategoryRefs;
	}

	public void setFacilityTypeCategoryRefs(Set facilityTypeCategoryRefs) {
		this.facilityTypeCategoryRefs = facilityTypeCategoryRefs;
	}

	public Set getCostCurveCategoryRefs() {
		return this.costCurveCategoryRefs;
	}

	public void setCostCurveCategoryRefs(Set costCurveCategoryRefs) {
		this.costCurveCategoryRefs = costCurveCategoryRefs;
	}

	public Set getCategoryClassificationRefs() {
		return this.categoryClassificationRefs;
	}

	public void setCategoryClassificationRefs(Set categoryClassificationRefs) {
		this.categoryClassificationRefs = categoryClassificationRefs;
	}

	public Set getCosts() {
		return this.costs;
	}

	public void setCosts(Set costs) {
		this.costs = costs;
	}

}
