package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * CategoryClassificationRef generated by hbm2java
 */
public class CategoryClassificationRef implements java.io.Serializable {

	// Fields    

	private CategoryClassificationRefId id;

	private CategoryRef categoryRef;

	private ClassificationRef classificationRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public CategoryClassificationRef() {
	}

	/** full constructor */
	public CategoryClassificationRef(CategoryClassificationRefId id,
			CategoryRef categoryRef, ClassificationRef classificationRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.categoryRef = categoryRef;
		this.classificationRef = classificationRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public CategoryClassificationRefId getId() {
		return this.id;
	}

	public void setId(CategoryClassificationRefId id) {
		this.id = id;
	}

	public CategoryRef getCategoryRef() {
		return this.categoryRef;
	}

	public void setCategoryRef(CategoryRef categoryRef) {
		this.categoryRef = categoryRef;
	}

	public ClassificationRef getClassificationRef() {
		return this.classificationRef;
	}

	public void setClassificationRef(ClassificationRef classificationRef) {
		this.classificationRef = classificationRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
