package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CbrAmountInformationId generated by hbm2java
 */
public class CbrAmountInformationId implements java.io.Serializable {

	// Fields

	private String cbrLoanInformationId;

	private String cbrProjectInformationId;

	private String cbrCategoryId;

	// Constructors

	/** default constructor */
	public CbrAmountInformationId() {
	}

	/** full constructor */
	public CbrAmountInformationId(String cbrLoanInformationId,
			String cbrProjectInformationId, String cbrCategoryId) {
		this.cbrLoanInformationId = cbrLoanInformationId;
		this.cbrProjectInformationId = cbrProjectInformationId;
		this.cbrCategoryId = cbrCategoryId;
	}

	// Property accessors
	public String getCbrLoanInformationId() {
		return this.cbrLoanInformationId;
	}

	public void setCbrLoanInformationId(String cbrLoanInformationId) {
		this.cbrLoanInformationId = cbrLoanInformationId;
	}

	public String getCbrProjectInformationId() {
		return this.cbrProjectInformationId;
	}

	public void setCbrProjectInformationId(String cbrProjectInformationId) {
		this.cbrProjectInformationId = cbrProjectInformationId;
	}

	public String getCbrCategoryId() {
		return this.cbrCategoryId;
	}

	public void setCbrCategoryId(String cbrCategoryId) {
		this.cbrCategoryId = cbrCategoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CbrAmountInformationId))
			return false;
		CbrAmountInformationId castOther = (CbrAmountInformationId) other;

		return ((this.getCbrLoanInformationId() == castOther
				.getCbrLoanInformationId()) || (this
				.getCbrLoanInformationId() != null
				&& castOther.getCbrLoanInformationId() != null && this
				.getCbrLoanInformationId().equals(
						castOther.getCbrLoanInformationId())))
				&& ((this.getCbrProjectInformationId() == castOther
						.getCbrProjectInformationId()) || (this
						.getCbrProjectInformationId() != null
						&& castOther.getCbrProjectInformationId() != null && this
						.getCbrProjectInformationId().equals(
								castOther.getCbrProjectInformationId())))
				&& ((this.getCbrCategoryId() == castOther.getCbrCategoryId()) || (this
						.getCbrCategoryId() != null
						&& castOther.getCbrCategoryId() != null && this
						.getCbrCategoryId()
						.equals(castOther.getCbrCategoryId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCbrLoanInformationId() == null ? 0 : this
						.getCbrLoanInformationId().hashCode());
		result = 37
				* result
				+ (getCbrProjectInformationId() == null ? 0 : this
						.getCbrProjectInformationId().hashCode());
		result = 37
				* result
				+ (getCbrCategoryId() == null ? 0 : this.getCbrCategoryId()
						.hashCode());
		return result;
	}

}
