package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CbrProjectInformation generated by hbm2java
 */
public class CbrProjectInformation implements java.io.Serializable {

	// Fields    

	private CbrProjectInformationId id;

	private CbrLoanInformation cbrLoanInformation;

	private int projectNumber;

	private String cwnsNumber;

	private String description;

	private String facilityName;

	private String npdesPermitNumber;

	private String permitType;

	private String permitNumber;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set cbrAmountInformations = new HashSet(0);

	// Constructors

	/** default constructor */
	public CbrProjectInformation() {
	}

	/** minimal constructor */
	public CbrProjectInformation(CbrProjectInformationId id,
			CbrLoanInformation cbrLoanInformation, int projectNumber,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.cbrLoanInformation = cbrLoanInformation;
		this.projectNumber = projectNumber;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CbrProjectInformation(CbrProjectInformationId id,
			CbrLoanInformation cbrLoanInformation, int projectNumber,
			String cwnsNumber, String description, String facilityName,
			String npdesPermitNumber, String permitType, String permitNumber,
			String lastUpdateUserid, Date lastUpdateTs,
			Set cbrAmountInformations) {
		this.id = id;
		this.cbrLoanInformation = cbrLoanInformation;
		this.projectNumber = projectNumber;
		this.cwnsNumber = cwnsNumber;
		this.description = description;
		this.facilityName = facilityName;
		this.npdesPermitNumber = npdesPermitNumber;
		this.permitType = permitType;
		this.permitNumber = permitNumber;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.cbrAmountInformations = cbrAmountInformations;
	}

	// Property accessors
	public CbrProjectInformationId getId() {
		return this.id;
	}

	public void setId(CbrProjectInformationId id) {
		this.id = id;
	}

	public CbrLoanInformation getCbrLoanInformation() {
		return this.cbrLoanInformation;
	}

	public void setCbrLoanInformation(CbrLoanInformation cbrLoanInformation) {
		this.cbrLoanInformation = cbrLoanInformation;
	}

	public int getProjectNumber() {
		return this.projectNumber;
	}

	public void setProjectNumber(int projectNumber) {
		this.projectNumber = projectNumber;
	}

	public String getCwnsNumber() {
		return this.cwnsNumber;
	}

	public void setCwnsNumber(String cwnsNumber) {
		this.cwnsNumber = cwnsNumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFacilityName() {
		return this.facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getNpdesPermitNumber() {
		return this.npdesPermitNumber;
	}

	public void setNpdesPermitNumber(String npdesPermitNumber) {
		this.npdesPermitNumber = npdesPermitNumber;
	}

	public String getPermitType() {
		return this.permitType;
	}

	public void setPermitType(String permitType) {
		this.permitType = permitType;
	}

	public String getPermitNumber() {
		return this.permitNumber;
	}

	public void setPermitNumber(String permitNumber) {
		this.permitNumber = permitNumber;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCbrAmountInformations() {
		return this.cbrAmountInformations;
	}

	public void setCbrAmountInformations(Set cbrAmountInformations) {
		this.cbrAmountInformations = cbrAmountInformations;
	}

}
