package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * ChangeTypeRuleRef generated by hbm2java
 */
public class ChangeTypeRuleRef implements java.io.Serializable {

	// Fields

	private ChangeTypeRuleRefId id;

	private ChangeTypeRef changeTypeRefByChangeTypeId1;

	private ChangeTypeRef changeTypeRefByChangeTypeId2;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public ChangeTypeRuleRef() {
	}

	/** full constructor */
	public ChangeTypeRuleRef(ChangeTypeRuleRefId id,
			ChangeTypeRef changeTypeRefByChangeTypeId1,
			ChangeTypeRef changeTypeRefByChangeTypeId2,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.changeTypeRefByChangeTypeId1 = changeTypeRefByChangeTypeId1;
		this.changeTypeRefByChangeTypeId2 = changeTypeRefByChangeTypeId2;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public ChangeTypeRuleRefId getId() {
		return this.id;
	}

	public void setId(ChangeTypeRuleRefId id) {
		this.id = id;
	}

	public ChangeTypeRef getChangeTypeRefByChangeTypeId1() {
		return this.changeTypeRefByChangeTypeId1;
	}

	public void setChangeTypeRefByChangeTypeId1(
			ChangeTypeRef changeTypeRefByChangeTypeId1) {
		this.changeTypeRefByChangeTypeId1 = changeTypeRefByChangeTypeId1;
	}

	public ChangeTypeRef getChangeTypeRefByChangeTypeId2() {
		return this.changeTypeRefByChangeTypeId2;
	}

	public void setChangeTypeRefByChangeTypeId2(
			ChangeTypeRef changeTypeRefByChangeTypeId2) {
		this.changeTypeRefByChangeTypeId2 = changeTypeRefByChangeTypeId2;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
