package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ChangeTypeRef generated by hbm2java
 */
public class ChangeTypeRef implements java.io.Serializable {

	// Fields

	private long changeTypeId;

	private String name;

	private byte sortSequence;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityUnitProcessChanges = new HashSet(0);

	private Set facilityTypeChangeRefs = new HashSet(0);

	private Set changeTypeRuleRefsForChangeTypeId1 = new HashSet(0);

	private Set facilityTypeChanges = new HashSet(0);

	private Set changeTypeRuleRefsForChangeTypeId2 = new HashSet(0);

	// Constructors

	/** default constructor */
	public ChangeTypeRef() {
	}

	/** minimal constructor */
	public ChangeTypeRef(long changeTypeId, String name, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.changeTypeId = changeTypeId;
		this.name = name;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public ChangeTypeRef(long changeTypeId, String name, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs,
			Set facilityUnitProcessChanges, Set facilityTypeChangeRefs,
			Set changeTypeRuleRefsForChangeTypeId1, Set facilityTypeChanges,
			Set changeTypeRuleRefsForChangeTypeId2) {
		this.changeTypeId = changeTypeId;
		this.name = name;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityUnitProcessChanges = facilityUnitProcessChanges;
		this.facilityTypeChangeRefs = facilityTypeChangeRefs;
		this.changeTypeRuleRefsForChangeTypeId1 = changeTypeRuleRefsForChangeTypeId1;
		this.facilityTypeChanges = facilityTypeChanges;
		this.changeTypeRuleRefsForChangeTypeId2 = changeTypeRuleRefsForChangeTypeId2;
	}

	// Property accessors
	public long getChangeTypeId() {
		return this.changeTypeId;
	}

	public void setChangeTypeId(long changeTypeId) {
		this.changeTypeId = changeTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityUnitProcessChanges() {
		return this.facilityUnitProcessChanges;
	}

	public void setFacilityUnitProcessChanges(Set facilityUnitProcessChanges) {
		this.facilityUnitProcessChanges = facilityUnitProcessChanges;
	}

	public Set getFacilityTypeChangeRefs() {
		return this.facilityTypeChangeRefs;
	}

	public void setFacilityTypeChangeRefs(Set facilityTypeChangeRefs) {
		this.facilityTypeChangeRefs = facilityTypeChangeRefs;
	}

	public Set getChangeTypeRuleRefsForChangeTypeId1() {
		return this.changeTypeRuleRefsForChangeTypeId1;
	}

	public void setChangeTypeRuleRefsForChangeTypeId1(
			Set changeTypeRuleRefsForChangeTypeId1) {
		this.changeTypeRuleRefsForChangeTypeId1 = changeTypeRuleRefsForChangeTypeId1;
	}

	public Set getFacilityTypeChanges() {
		return this.facilityTypeChanges;
	}

	public void setFacilityTypeChanges(Set facilityTypeChanges) {
		this.facilityTypeChanges = facilityTypeChanges;
	}

	public Set getChangeTypeRuleRefsForChangeTypeId2() {
		return this.changeTypeRuleRefsForChangeTypeId2;
	}

	public void setChangeTypeRuleRefsForChangeTypeId2(
			Set changeTypeRuleRefsForChangeTypeId2) {
		this.changeTypeRuleRefsForChangeTypeId2 = changeTypeRuleRefsForChangeTypeId2;
	}

}
