package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * ChangeTypeRuleRefId generated by hbm2java
 */
public class ChangeTypeRuleRefId implements java.io.Serializable {

	// Fields

	private long changeTypeId1;

	private long changeTypeId2;

	// Constructors

	/** default constructor */
	public ChangeTypeRuleRefId() {
	}

	/** full constructor */
	public ChangeTypeRuleRefId(long changeTypeId1, long changeTypeId2) {
		this.changeTypeId1 = changeTypeId1;
		this.changeTypeId2 = changeTypeId2;
	}

	// Property accessors
	public long getChangeTypeId1() {
		return this.changeTypeId1;
	}

	public void setChangeTypeId1(long changeTypeId1) {
		this.changeTypeId1 = changeTypeId1;
	}

	public long getChangeTypeId2() {
		return this.changeTypeId2;
	}

	public void setChangeTypeId2(long changeTypeId2) {
		this.changeTypeId2 = changeTypeId2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChangeTypeRuleRefId))
			return false;
		ChangeTypeRuleRefId castOther = (ChangeTypeRuleRefId) other;

		return (this.getChangeTypeId1() == castOther.getChangeTypeId1())
				&& (this.getChangeTypeId2() == castOther.getChangeTypeId2());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getChangeTypeId1();
		result = 37 * result + (int) this.getChangeTypeId2();
		return result;
	}

}
