package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CostTemp generated by hbm2java
 */
public class CostTemp implements java.io.Serializable {

	// Fields    

	private CostTempId id;

	// Constructors

	/** default constructor */
	public CostTemp() {
	}

	/** full constructor */
	public CostTemp(CostTempId id) {
		this.id = id;
	}

	// Property accessors
	public CostTempId getId() {
		return this.id;
	}

	public void setId(CostTempId id) {
		this.id = id;
	}

}
