package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * CostIndexRef generated by hbm2java
 */
public class CostIndexRef implements java.io.Serializable {

	// Fields    

	private long costIndexId;

	private short indexYear;

	private byte indexMonth;

	private int monthlyIndex;

	private char baseMonthFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public CostIndexRef() {
	}

	/** full constructor */
	public CostIndexRef(long costIndexId, short indexYear, byte indexMonth,
			int monthlyIndex, char baseMonthFlag, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.costIndexId = costIndexId;
		this.indexYear = indexYear;
		this.indexMonth = indexMonth;
		this.monthlyIndex = monthlyIndex;
		this.baseMonthFlag = baseMonthFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public long getCostIndexId() {
		return this.costIndexId;
	}

	public void setCostIndexId(long costIndexId) {
		this.costIndexId = costIndexId;
	}

	public short getIndexYear() {
		return this.indexYear;
	}

	public void setIndexYear(short indexYear) {
		this.indexYear = indexYear;
	}

	public byte getIndexMonth() {
		return this.indexMonth;
	}

	public void setIndexMonth(byte indexMonth) {
		this.indexMonth = indexMonth;
	}

	public int getMonthlyIndex() {
		return this.monthlyIndex;
	}

	public void setMonthlyIndex(int monthlyIndex) {
		this.monthlyIndex = monthlyIndex;
	}

	public char getBaseMonthFlag() {
		return this.baseMonthFlag;
	}

	public void setBaseMonthFlag(char baseMonthFlag) {
		this.baseMonthFlag = baseMonthFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
