package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CostCurveRef generated by hbm2java
 */
public class CostCurveRef implements java.io.Serializable {

	// Fields    

	private long costCurveId;

	private String code;

	private String name;

	private Date baseDesignDate;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set costCurveCategoryRefs = new HashSet(0);

	private Set facilityTypeChangeCcRefs = new HashSet(0);

	private Set facilityCostCurves = new HashSet(0);

	private Set populationRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public CostCurveRef() {
	}

	/** minimal constructor */
	public CostCurveRef(long costCurveId, String code, String name,
			Date baseDesignDate, String lastUpdateUserid, Date lastUpdateTs) {
		this.costCurveId = costCurveId;
		this.code = code;
		this.name = name;
		this.baseDesignDate = baseDesignDate;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CostCurveRef(long costCurveId, String code, String name,
			Date baseDesignDate, String lastUpdateUserid, Date lastUpdateTs,
			Set costCurveCategoryRefs, Set facilityTypeChangeCcRefs,
			Set facilityCostCurves, Set populationRefs) {
		this.costCurveId = costCurveId;
		this.code = code;
		this.name = name;
		this.baseDesignDate = baseDesignDate;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.costCurveCategoryRefs = costCurveCategoryRefs;
		this.facilityTypeChangeCcRefs = facilityTypeChangeCcRefs;
		this.facilityCostCurves = facilityCostCurves;
		this.populationRefs = populationRefs;
	}

	// Property accessors
	public long getCostCurveId() {
		return this.costCurveId;
	}

	public void setCostCurveId(long costCurveId) {
		this.costCurveId = costCurveId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBaseDesignDate() {
		return this.baseDesignDate;
	}

	public void setBaseDesignDate(Date baseDesignDate) {
		this.baseDesignDate = baseDesignDate;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCostCurveCategoryRefs() {
		return this.costCurveCategoryRefs;
	}

	public void setCostCurveCategoryRefs(Set costCurveCategoryRefs) {
		this.costCurveCategoryRefs = costCurveCategoryRefs;
	}

	public Set getFacilityTypeChangeCcRefs() {
		return this.facilityTypeChangeCcRefs;
	}

	public void setFacilityTypeChangeCcRefs(Set facilityTypeChangeCcRefs) {
		this.facilityTypeChangeCcRefs = facilityTypeChangeCcRefs;
	}

	public Set getFacilityCostCurves() {
		return this.facilityCostCurves;
	}

	public void setFacilityCostCurves(Set facilityCostCurves) {
		this.facilityCostCurves = facilityCostCurves;
	}

	public Set getPopulationRefs() {
		return this.populationRefs;
	}

	public void setPopulationRefs(Set populationRefs) {
		this.populationRefs = populationRefs;
	}

}
