package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * CostRecalculationControlRef generated by hbm2java
 */
public class CostRecalculationControlRef implements java.io.Serializable {

	// Fields    

	private CostRecalculationControlRefId id;

	private String lastUpdateUserid;

	// Constructors

	/** default constructor */
	public CostRecalculationControlRef() {
	}

	/** full constructor */
	public CostRecalculationControlRef(CostRecalculationControlRefId id,
			String lastUpdateUserid) {
		this.id = id;
		this.lastUpdateUserid = lastUpdateUserid;
	}

	// Property accessors
	public CostRecalculationControlRefId getId() {
		return this.id;
	}

	public void setId(CostRecalculationControlRefId id) {
		this.id = id;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

}
