package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CountyRef generated by hbm2java
 */
public class CountyRef implements java.io.Serializable {

	// Fields    

	private long countyId;

	private String name;

	private String locationId;

	private String fipsCode;

	private BigDecimal treatmentMultiplierRatio;

	private BigDecimal sewerMultiplierRatio;

	private BigDecimal onsiteMultiplierRatio;

	private BigDecimal resPopulationPerUnit;

	private BigDecimal nonresPopulationPerUnit;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set geographicAreaCounties = new HashSet(0);

	// Constructors

	/** default constructor */
	public CountyRef() {
	}

	/** minimal constructor */
	public CountyRef(long countyId, String name, String locationId,
			String fipsCode, BigDecimal treatmentMultiplierRatio,
			BigDecimal sewerMultiplierRatio, BigDecimal onsiteMultiplierRatio,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.countyId = countyId;
		this.name = name;
		this.locationId = locationId;
		this.fipsCode = fipsCode;
		this.treatmentMultiplierRatio = treatmentMultiplierRatio;
		this.sewerMultiplierRatio = sewerMultiplierRatio;
		this.onsiteMultiplierRatio = onsiteMultiplierRatio;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CountyRef(long countyId, String name, String locationId,
			String fipsCode, BigDecimal treatmentMultiplierRatio,
			BigDecimal sewerMultiplierRatio, BigDecimal onsiteMultiplierRatio,
			BigDecimal resPopulationPerUnit,
			BigDecimal nonresPopulationPerUnit, String lastUpdateUserid,
			Date lastUpdateTs, Set geographicAreaCounties) {
		this.countyId = countyId;
		this.name = name;
		this.locationId = locationId;
		this.fipsCode = fipsCode;
		this.treatmentMultiplierRatio = treatmentMultiplierRatio;
		this.sewerMultiplierRatio = sewerMultiplierRatio;
		this.onsiteMultiplierRatio = onsiteMultiplierRatio;
		this.resPopulationPerUnit = resPopulationPerUnit;
		this.nonresPopulationPerUnit = nonresPopulationPerUnit;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.geographicAreaCounties = geographicAreaCounties;
	}

	// Property accessors
	public long getCountyId() {
		return this.countyId;
	}

	public void setCountyId(long countyId) {
		this.countyId = countyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getFipsCode() {
		return this.fipsCode;
	}

	public void setFipsCode(String fipsCode) {
		this.fipsCode = fipsCode;
	}

	public BigDecimal getTreatmentMultiplierRatio() {
		return this.treatmentMultiplierRatio;
	}

	public void setTreatmentMultiplierRatio(BigDecimal treatmentMultiplierRatio) {
		this.treatmentMultiplierRatio = treatmentMultiplierRatio;
	}

	public BigDecimal getSewerMultiplierRatio() {
		return this.sewerMultiplierRatio;
	}

	public void setSewerMultiplierRatio(BigDecimal sewerMultiplierRatio) {
		this.sewerMultiplierRatio = sewerMultiplierRatio;
	}

	public BigDecimal getOnsiteMultiplierRatio() {
		return this.onsiteMultiplierRatio;
	}

	public void setOnsiteMultiplierRatio(BigDecimal onsiteMultiplierRatio) {
		this.onsiteMultiplierRatio = onsiteMultiplierRatio;
	}

	public BigDecimal getResPopulationPerUnit() {
		return this.resPopulationPerUnit;
	}

	public void setResPopulationPerUnit(BigDecimal resPopulationPerUnit) {
		this.resPopulationPerUnit = resPopulationPerUnit;
	}

	public BigDecimal getNonresPopulationPerUnit() {
		return this.nonresPopulationPerUnit;
	}

	public void setNonresPopulationPerUnit(BigDecimal nonresPopulationPerUnit) {
		this.nonresPopulationPerUnit = nonresPopulationPerUnit;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getGeographicAreaCounties() {
		return this.geographicAreaCounties;
	}

	public void setGeographicAreaCounties(Set geographicAreaCounties) {
		this.geographicAreaCounties = geographicAreaCounties;
	}

}
