package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CwnsUserLocation generated by hbm2java
 */
public class CwnsUserLocation implements java.io.Serializable {

	// Fields    

	private CwnsUserLocationId id;

	private CwnsUser cwnsUser;

	private RoleRef roleRef;

	private char primaryFlag;

	private char limitedFacilitiesFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set cwnsUserLocationFacilities = new HashSet(0);

	private Set cwnsUserLocatnAccessLevels = new HashSet(0);

	// Constructors

	/** default constructor */
	public CwnsUserLocation() {
	}

	/** minimal constructor */
	public CwnsUserLocation(CwnsUserLocationId id, CwnsUser cwnsUser,
			RoleRef roleRef, char primaryFlag, char limitedFacilitiesFlag,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.cwnsUser = cwnsUser;
		this.roleRef = roleRef;
		this.primaryFlag = primaryFlag;
		this.limitedFacilitiesFlag = limitedFacilitiesFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public CwnsUserLocation(CwnsUserLocationId id, CwnsUser cwnsUser,
			RoleRef roleRef, char primaryFlag, char limitedFacilitiesFlag,
			String lastUpdateUserid, Date lastUpdateTs,
			Set cwnsUserLocationFacilities, Set cwnsUserLocatnAccessLevels) {
		this.id = id;
		this.cwnsUser = cwnsUser;
		this.roleRef = roleRef;
		this.primaryFlag = primaryFlag;
		this.limitedFacilitiesFlag = limitedFacilitiesFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.cwnsUserLocationFacilities = cwnsUserLocationFacilities;
		this.cwnsUserLocatnAccessLevels = cwnsUserLocatnAccessLevels;
	}

	// Property accessors
	public CwnsUserLocationId getId() {
		return this.id;
	}

	public void setId(CwnsUserLocationId id) {
		this.id = id;
	}

	public CwnsUser getCwnsUser() {
		return this.cwnsUser;
	}

	public void setCwnsUser(CwnsUser cwnsUser) {
		this.cwnsUser = cwnsUser;
	}

	public RoleRef getRoleRef() {
		return this.roleRef;
	}

	public void setRoleRef(RoleRef roleRef) {
		this.roleRef = roleRef;
	}

	public char getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(char primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	public char getLimitedFacilitiesFlag() {
		return this.limitedFacilitiesFlag;
	}

	public void setLimitedFacilitiesFlag(char limitedFacilitiesFlag) {
		this.limitedFacilitiesFlag = limitedFacilitiesFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCwnsUserLocationFacilities() {
		return this.cwnsUserLocationFacilities;
	}

	public void setCwnsUserLocationFacilities(Set cwnsUserLocationFacilities) {
		this.cwnsUserLocationFacilities = cwnsUserLocationFacilities;
	}

	public Set getCwnsUserLocatnAccessLevels() {
		return this.cwnsUserLocatnAccessLevels;
	}

	public void setCwnsUserLocatnAccessLevels(Set cwnsUserLocatnAccessLevels) {
		this.cwnsUserLocatnAccessLevels = cwnsUserLocatnAccessLevels;
	}

}
