package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * CwnsUserLocatnAccessLevel generated by hbm2java
 */
public class CwnsUserLocatnAccessLevel implements java.io.Serializable {

	// Fields    

	private CwnsUserLocatnAccessLevelId id;

	private CwnsUserLocation cwnsUserLocation;

	private AccessLevelRef accessLevelRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public CwnsUserLocatnAccessLevel() {
	}

	/** full constructor */
	public CwnsUserLocatnAccessLevel(CwnsUserLocatnAccessLevelId id,
			CwnsUserLocation cwnsUserLocation, AccessLevelRef accessLevelRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.cwnsUserLocation = cwnsUserLocation;
		this.accessLevelRef = accessLevelRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public CwnsUserLocatnAccessLevelId getId() {
		return this.id;
	}

	public void setId(CwnsUserLocatnAccessLevelId id) {
		this.id = id;
	}

	public CwnsUserLocation getCwnsUserLocation() {
		return this.cwnsUserLocation;
	}

	public void setCwnsUserLocation(CwnsUserLocation cwnsUserLocation) {
		this.cwnsUserLocation = cwnsUserLocation;
	}

	public AccessLevelRef getAccessLevelRef() {
		return this.accessLevelRef;
	}

	public void setAccessLevelRef(AccessLevelRef accessLevelRef) {
		this.accessLevelRef = accessLevelRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
