package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * CwnsInfoRef generated by hbm2java
 */
public class CwnsInfoRef implements java.io.Serializable {

	// Fields    

	private short surveyYear;

	private long fax;

	private long footnotableMaximumAmount;

	private long submitDocNeedsAmount;

	private short submitDocNeedsNpsYear;

	private short submitDocNeedsNNpsYear;

	private short submitDocNpsYear;

	private short submitDocNNpsYear;

	private short populationMaxProjectionYear;

	private BigDecimal flowRatioNonResMultiplier;

	private short flowHighRatio;

	private short flowLowRatio;

	private BigDecimal presentDesignFlowMultiplier;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public CwnsInfoRef() {
	}

	/** full constructor */
	public CwnsInfoRef(short surveyYear, long fax,
			long footnotableMaximumAmount, long submitDocNeedsAmount,
			short submitDocNeedsNpsYear, short submitDocNeedsNNpsYear,
			short submitDocNpsYear, short submitDocNNpsYear,
			short populationMaxProjectionYear,
			BigDecimal flowRatioNonResMultiplier, short flowHighRatio,
			short flowLowRatio, BigDecimal presentDesignFlowMultiplier,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.surveyYear = surveyYear;
		this.fax = fax;
		this.footnotableMaximumAmount = footnotableMaximumAmount;
		this.submitDocNeedsAmount = submitDocNeedsAmount;
		this.submitDocNeedsNpsYear = submitDocNeedsNpsYear;
		this.submitDocNeedsNNpsYear = submitDocNeedsNNpsYear;
		this.submitDocNpsYear = submitDocNpsYear;
		this.submitDocNNpsYear = submitDocNNpsYear;
		this.populationMaxProjectionYear = populationMaxProjectionYear;
		this.flowRatioNonResMultiplier = flowRatioNonResMultiplier;
		this.flowHighRatio = flowHighRatio;
		this.flowLowRatio = flowLowRatio;
		this.presentDesignFlowMultiplier = presentDesignFlowMultiplier;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public short getSurveyYear() {
		return this.surveyYear;
	}

	public void setSurveyYear(short surveyYear) {
		this.surveyYear = surveyYear;
	}

	public long getFax() {
		return this.fax;
	}

	public void setFax(long fax) {
		this.fax = fax;
	}

	public long getFootnotableMaximumAmount() {
		return this.footnotableMaximumAmount;
	}

	public void setFootnotableMaximumAmount(long footnotableMaximumAmount) {
		this.footnotableMaximumAmount = footnotableMaximumAmount;
	}

	public long getSubmitDocNeedsAmount() {
		return this.submitDocNeedsAmount;
	}

	public void setSubmitDocNeedsAmount(long submitDocNeedsAmount) {
		this.submitDocNeedsAmount = submitDocNeedsAmount;
	}

	public short getSubmitDocNeedsNpsYear() {
		return this.submitDocNeedsNpsYear;
	}

	public void setSubmitDocNeedsNpsYear(short submitDocNeedsNpsYear) {
		this.submitDocNeedsNpsYear = submitDocNeedsNpsYear;
	}

	public short getSubmitDocNeedsNNpsYear() {
		return this.submitDocNeedsNNpsYear;
	}

	public void setSubmitDocNeedsNNpsYear(short submitDocNeedsNNpsYear) {
		this.submitDocNeedsNNpsYear = submitDocNeedsNNpsYear;
	}

	public short getSubmitDocNpsYear() {
		return this.submitDocNpsYear;
	}

	public void setSubmitDocNpsYear(short submitDocNpsYear) {
		this.submitDocNpsYear = submitDocNpsYear;
	}

	public short getSubmitDocNNpsYear() {
		return this.submitDocNNpsYear;
	}

	public void setSubmitDocNNpsYear(short submitDocNNpsYear) {
		this.submitDocNNpsYear = submitDocNNpsYear;
	}

	public short getPopulationMaxProjectionYear() {
		return this.populationMaxProjectionYear;
	}

	public void setPopulationMaxProjectionYear(short populationMaxProjectionYear) {
		this.populationMaxProjectionYear = populationMaxProjectionYear;
	}

	public BigDecimal getFlowRatioNonResMultiplier() {
		return this.flowRatioNonResMultiplier;
	}

	public void setFlowRatioNonResMultiplier(
			BigDecimal flowRatioNonResMultiplier) {
		this.flowRatioNonResMultiplier = flowRatioNonResMultiplier;
	}

	public short getFlowHighRatio() {
		return this.flowHighRatio;
	}

	public void setFlowHighRatio(short flowHighRatio) {
		this.flowHighRatio = flowHighRatio;
	}

	public short getFlowLowRatio() {
		return this.flowLowRatio;
	}

	public void setFlowLowRatio(short flowLowRatio) {
		this.flowLowRatio = flowLowRatio;
	}

	public BigDecimal getPresentDesignFlowMultiplier() {
		return this.presentDesignFlowMultiplier;
	}

	public void setPresentDesignFlowMultiplier(
			BigDecimal presentDesignFlowMultiplier) {
		this.presentDesignFlowMultiplier = presentDesignFlowMultiplier;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
