package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * DocumentTypeGroupRef generated by hbm2java
 */
public class DocumentTypeGroupRef implements java.io.Serializable {

	// Fields    

	private DocumentTypeGroupRefId id;

	private DocumentGroupRef documentGroupRef;

	private DocumentTypeRef documentTypeRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public DocumentTypeGroupRef() {
	}

	/** full constructor */
	public DocumentTypeGroupRef(DocumentTypeGroupRefId id,
			DocumentGroupRef documentGroupRef, DocumentTypeRef documentTypeRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.documentGroupRef = documentGroupRef;
		this.documentTypeRef = documentTypeRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public DocumentTypeGroupRefId getId() {
		return this.id;
	}

	public void setId(DocumentTypeGroupRefId id) {
		this.id = id;
	}

	public DocumentGroupRef getDocumentGroupRef() {
		return this.documentGroupRef;
	}

	public void setDocumentGroupRef(DocumentGroupRef documentGroupRef) {
		this.documentGroupRef = documentGroupRef;
	}

	public DocumentTypeRef getDocumentTypeRef() {
		return this.documentTypeRef;
	}

	public void setDocumentTypeRef(DocumentTypeRef documentTypeRef) {
		this.documentTypeRef = documentTypeRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
