package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EfEffluentLimit generated by hbm2java
 */
public class EfEffluentLimit implements java.io.Serializable {

	// Fields    

	private EfEffluentLimitId id;

	private EfPipeSched efPipeSched;

	private Date modifPeriodEndDate;

	private Set efDmrMeasurements = new HashSet(0);

	private Set efEffluentLimitQties = new HashSet(0);

	private Set efEffluentLimitConcentrs = new HashSet(0);

	// Constructors

	/** default constructor */
	public EfEffluentLimit() {
	}

	/** minimal constructor */
	public EfEffluentLimit(EfEffluentLimitId id, EfPipeSched efPipeSched) {
		this.id = id;
		this.efPipeSched = efPipeSched;
	}

	/** full constructor */
	public EfEffluentLimit(EfEffluentLimitId id, EfPipeSched efPipeSched,
			Date modifPeriodEndDate, Set efDmrMeasurements,
			Set efEffluentLimitQties, Set efEffluentLimitConcentrs) {
		this.id = id;
		this.efPipeSched = efPipeSched;
		this.modifPeriodEndDate = modifPeriodEndDate;
		this.efDmrMeasurements = efDmrMeasurements;
		this.efEffluentLimitQties = efEffluentLimitQties;
		this.efEffluentLimitConcentrs = efEffluentLimitConcentrs;
	}

	// Property accessors
	public EfEffluentLimitId getId() {
		return this.id;
	}

	public void setId(EfEffluentLimitId id) {
		this.id = id;
	}

	public EfPipeSched getEfPipeSched() {
		return this.efPipeSched;
	}

	public void setEfPipeSched(EfPipeSched efPipeSched) {
		this.efPipeSched = efPipeSched;
	}

	public Date getModifPeriodEndDate() {
		return this.modifPeriodEndDate;
	}

	public void setModifPeriodEndDate(Date modifPeriodEndDate) {
		this.modifPeriodEndDate = modifPeriodEndDate;
	}

	public Set getEfDmrMeasurements() {
		return this.efDmrMeasurements;
	}

	public void setEfDmrMeasurements(Set efDmrMeasurements) {
		this.efDmrMeasurements = efDmrMeasurements;
	}

	public Set getEfEffluentLimitQties() {
		return this.efEffluentLimitQties;
	}

	public void setEfEffluentLimitQties(Set efEffluentLimitQties) {
		this.efEffluentLimitQties = efEffluentLimitQties;
	}

	public Set getEfEffluentLimitConcentrs() {
		return this.efEffluentLimitConcentrs;
	}

	public void setEfEffluentLimitConcentrs(Set efEffluentLimitConcentrs) {
		this.efEffluentLimitConcentrs = efEffluentLimitConcentrs;
	}

}
