package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * EfEffluentLimitConcentr generated by hbm2java
 */
public class EfEffluentLimitConcentr implements java.io.Serializable {

	// Fields    

	private EfEffluentLimitConcentrId id;

	private EfEffluentLimit efEffluentLimit;

	private String concentrMaxLimit;

	private String concentrAvgLimit;

	private String concentrMinLimit;

	private String concentrUnitCode;

	// Constructors

	/** default constructor */
	public EfEffluentLimitConcentr() {
	}

	/** minimal constructor */
	public EfEffluentLimitConcentr(EfEffluentLimitConcentrId id,
			EfEffluentLimit efEffluentLimit) {
		this.id = id;
		this.efEffluentLimit = efEffluentLimit;
	}

	/** full constructor */
	public EfEffluentLimitConcentr(EfEffluentLimitConcentrId id,
			EfEffluentLimit efEffluentLimit, String concentrMaxLimit,
			String concentrAvgLimit, String concentrMinLimit,
			String concentrUnitCode) {
		this.id = id;
		this.efEffluentLimit = efEffluentLimit;
		this.concentrMaxLimit = concentrMaxLimit;
		this.concentrAvgLimit = concentrAvgLimit;
		this.concentrMinLimit = concentrMinLimit;
		this.concentrUnitCode = concentrUnitCode;
	}

	// Property accessors
	public EfEffluentLimitConcentrId getId() {
		return this.id;
	}

	public void setId(EfEffluentLimitConcentrId id) {
		this.id = id;
	}

	public EfEffluentLimit getEfEffluentLimit() {
		return this.efEffluentLimit;
	}

	public void setEfEffluentLimit(EfEffluentLimit efEffluentLimit) {
		this.efEffluentLimit = efEffluentLimit;
	}

	public String getConcentrMaxLimit() {
		return this.concentrMaxLimit;
	}

	public void setConcentrMaxLimit(String concentrMaxLimit) {
		this.concentrMaxLimit = concentrMaxLimit;
	}

	public String getConcentrAvgLimit() {
		return this.concentrAvgLimit;
	}

	public void setConcentrAvgLimit(String concentrAvgLimit) {
		this.concentrAvgLimit = concentrAvgLimit;
	}

	public String getConcentrMinLimit() {
		return this.concentrMinLimit;
	}

	public void setConcentrMinLimit(String concentrMinLimit) {
		this.concentrMinLimit = concentrMinLimit;
	}

	public String getConcentrUnitCode() {
		return this.concentrUnitCode;
	}

	public void setConcentrUnitCode(String concentrUnitCode) {
		this.concentrUnitCode = concentrUnitCode;
	}

}
