package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EffluentTreatmentLevelRef generated by hbm2java
 */
public class EffluentTreatmentLevelRef implements java.io.Serializable {

	// Fields    

	private long effluentTreatmentLevelId;

	private String name;

	private byte effluentLotNbr;

	private byte sortSequence;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityEffluents = new HashSet(0);

	// Constructors

	/** default constructor */
	public EffluentTreatmentLevelRef() {
	}

	/** minimal constructor */
	public EffluentTreatmentLevelRef(long effluentTreatmentLevelId,
			String name, byte effluentLotNbr, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
		this.name = name;
		this.effluentLotNbr = effluentLotNbr;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public EffluentTreatmentLevelRef(long effluentTreatmentLevelId,
			String name, byte effluentLotNbr, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs, Set facilityEffluents) {
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
		this.name = name;
		this.effluentLotNbr = effluentLotNbr;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityEffluents = facilityEffluents;
	}

	// Property accessors
	public long getEffluentTreatmentLevelId() {
		return this.effluentTreatmentLevelId;
	}

	public void setEffluentTreatmentLevelId(long effluentTreatmentLevelId) {
		this.effluentTreatmentLevelId = effluentTreatmentLevelId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getEffluentLotNbr() {
		return this.effluentLotNbr;
	}

	public void setEffluentLotNbr(byte effluentLotNbr) {
		this.effluentLotNbr = effluentLotNbr;
	}

	public byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityEffluents() {
		return this.facilityEffluents;
	}

	public void setFacilityEffluents(Set facilityEffluents) {
		this.facilityEffluents = facilityEffluents;
	}

}
