package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * EfPipeSchedId generated by hbm2java
 */
public class EfPipeSchedId implements java.io.Serializable {

	// Fields

	private String efNpdesPermitNumber;

	private String efDischargeNum;

	private String efReportDesig;

	private char efPipeSetQualifier;

	// Constructors

	/** default constructor */
	public EfPipeSchedId() {
	}

	/** full constructor */
	public EfPipeSchedId(String efNpdesPermitNumber, String efDischargeNum,
			String efReportDesig, char efPipeSetQualifier) {
		this.efNpdesPermitNumber = efNpdesPermitNumber;
		this.efDischargeNum = efDischargeNum;
		this.efReportDesig = efReportDesig;
		this.efPipeSetQualifier = efPipeSetQualifier;
	}

	// Property accessors
	public String getEfNpdesPermitNumber() {
		return this.efNpdesPermitNumber;
	}

	public void setEfNpdesPermitNumber(String efNpdesPermitNumber) {
		this.efNpdesPermitNumber = efNpdesPermitNumber;
	}

	public String getEfDischargeNum() {
		return this.efDischargeNum;
	}

	public void setEfDischargeNum(String efDischargeNum) {
		this.efDischargeNum = efDischargeNum;
	}

	public String getEfReportDesig() {
		return this.efReportDesig;
	}

	public void setEfReportDesig(String efReportDesig) {
		this.efReportDesig = efReportDesig;
	}

	public char getEfPipeSetQualifier() {
		return this.efPipeSetQualifier;
	}

	public void setEfPipeSetQualifier(char efPipeSetQualifier) {
		this.efPipeSetQualifier = efPipeSetQualifier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EfPipeSchedId))
			return false;
		EfPipeSchedId castOther = (EfPipeSchedId) other;

		return ((this.getEfNpdesPermitNumber() == castOther
				.getEfNpdesPermitNumber()) || (this
				.getEfNpdesPermitNumber() != null
				&& castOther.getEfNpdesPermitNumber() != null && this
				.getEfNpdesPermitNumber().equals(
						castOther.getEfNpdesPermitNumber())))
				&& ((this.getEfDischargeNum() == castOther.getEfDischargeNum()) || (this
						.getEfDischargeNum() != null
						&& castOther.getEfDischargeNum() != null && this
						.getEfDischargeNum().equals(
								castOther.getEfDischargeNum())))
				&& ((this.getEfReportDesig() == castOther.getEfReportDesig()) || (this
						.getEfReportDesig() != null
						&& castOther.getEfReportDesig() != null && this
						.getEfReportDesig()
						.equals(castOther.getEfReportDesig())))
				&& (this.getEfPipeSetQualifier() == castOther
						.getEfPipeSetQualifier());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEfNpdesPermitNumber() == null ? 0 : this
						.getEfNpdesPermitNumber().hashCode());
		result = 37
				* result
				+ (getEfDischargeNum() == null ? 0 : this.getEfDischargeNum()
						.hashCode());
		result = 37
				* result
				+ (getEfReportDesig() == null ? 0 : this.getEfReportDesig()
						.hashCode());
		result = 37 * result + this.getEfPipeSetQualifier();
		return result;
	}

}
