package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityPermit generated by hbm2java
 */
public class FacilityPermit implements java.io.Serializable {

	// Fields    

	private FacilityPermitId id;

	private Facility facility;

	private Permit permit;

	private char usedForFacilityLocatnFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	// Constructors

	/** default constructor */
	public FacilityPermit() {
	}

	/** full constructor */
	public FacilityPermit(FacilityPermitId id, Facility facility,
			Permit permit, char usedForFacilityLocatnFlag,
			String lastUpdateUserid, Date lastUpdateTs, char feedbackDeleteFlag) {
		this.id = id;
		this.facility = facility;
		this.permit = permit;
		this.usedForFacilityLocatnFlag = usedForFacilityLocatnFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	// Property accessors
	public FacilityPermitId getId() {
		return this.id;
	}

	public void setId(FacilityPermitId id) {
		this.id = id;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public Permit getPermit() {
		return this.permit;
	}

	public void setPermit(Permit permit) {
		this.permit = permit;
	}

	public char getUsedForFacilityLocatnFlag() {
		return this.usedForFacilityLocatnFlag;
	}

	public void setUsedForFacilityLocatnFlag(char usedForFacilityLocatnFlag) {
		this.usedForFacilityLocatnFlag = usedForFacilityLocatnFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

}
