package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityUnitProcessId generated by hbm2java
 */
public class FacilityUnitProcessId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long treatmentTypeId;

	private long unitProcessId;

	// Constructors

	/** default constructor */
	public FacilityUnitProcessId() {
	}

	/** full constructor */
	public FacilityUnitProcessId(long facilityId, long treatmentTypeId,
			long unitProcessId) {
		this.facilityId = facilityId;
		this.treatmentTypeId = treatmentTypeId;
		this.unitProcessId = unitProcessId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getTreatmentTypeId() {
		return this.treatmentTypeId;
	}

	public void setTreatmentTypeId(long treatmentTypeId) {
		this.treatmentTypeId = treatmentTypeId;
	}

	public long getUnitProcessId() {
		return this.unitProcessId;
	}

	public void setUnitProcessId(long unitProcessId) {
		this.unitProcessId = unitProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityUnitProcessId))
			return false;
		FacilityUnitProcessId castOther = (FacilityUnitProcessId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getTreatmentTypeId() == castOther
						.getTreatmentTypeId())
				&& (this.getUnitProcessId() == castOther.getUnitProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getTreatmentTypeId();
		result = 37 * result + (int) this.getUnitProcessId();
		return result;
	}

}
