package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityTypeChangeRef generated by hbm2java
 */
public class FacilityTypeChangeRef implements java.io.Serializable {

	// Fields    

	private FacilityTypeChangeRefId id;

	private FacilityTypeRef facilityTypeRef;

	private ChangeTypeRef changeTypeRef;

	private char presentFutureCode;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityTypeChangeCcRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityTypeChangeRef() {
	}

	/** minimal constructor */
	public FacilityTypeChangeRef(FacilityTypeChangeRefId id,
			FacilityTypeRef facilityTypeRef, ChangeTypeRef changeTypeRef,
			char presentFutureCode, String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facilityTypeRef = facilityTypeRef;
		this.changeTypeRef = changeTypeRef;
		this.presentFutureCode = presentFutureCode;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityTypeChangeRef(FacilityTypeChangeRefId id,
			FacilityTypeRef facilityTypeRef, ChangeTypeRef changeTypeRef,
			char presentFutureCode, String lastUpdateUserid, Date lastUpdateTs,
			Set facilityTypeChangeCcRefs) {
		this.id = id;
		this.facilityTypeRef = facilityTypeRef;
		this.changeTypeRef = changeTypeRef;
		this.presentFutureCode = presentFutureCode;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityTypeChangeCcRefs = facilityTypeChangeCcRefs;
	}

	// Property accessors
	public FacilityTypeChangeRefId getId() {
		return this.id;
	}

	public void setId(FacilityTypeChangeRefId id) {
		this.id = id;
	}

	public FacilityTypeRef getFacilityTypeRef() {
		return this.facilityTypeRef;
	}

	public void setFacilityTypeRef(FacilityTypeRef facilityTypeRef) {
		this.facilityTypeRef = facilityTypeRef;
	}

	public ChangeTypeRef getChangeTypeRef() {
		return this.changeTypeRef;
	}

	public void setChangeTypeRef(ChangeTypeRef changeTypeRef) {
		this.changeTypeRef = changeTypeRef;
	}

	public char getPresentFutureCode() {
		return this.presentFutureCode;
	}

	public void setPresentFutureCode(char presentFutureCode) {
		this.presentFutureCode = presentFutureCode;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityTypeChangeCcRefs() {
		return this.facilityTypeChangeCcRefs;
	}

	public void setFacilityTypeChangeCcRefs(Set facilityTypeChangeCcRefs) {
		this.facilityTypeChangeCcRefs = facilityTypeChangeCcRefs;
	}

}
