package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityTypeDischargeRef generated by hbm2java
 */
public class FacilityTypeDischargeRef implements java.io.Serializable {

	// Fields    

	private FacilityTypeDischargeRefId id;

	private FacilityTypeRef facilityTypeRef;

	private DischargeMethodRef dischargeMethodRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityTypeDischargeRef() {
	}

	/** full constructor */
	public FacilityTypeDischargeRef(FacilityTypeDischargeRefId id,
			FacilityTypeRef facilityTypeRef,
			DischargeMethodRef dischargeMethodRef, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.facilityTypeRef = facilityTypeRef;
		this.dischargeMethodRef = dischargeMethodRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityTypeDischargeRefId getId() {
		return this.id;
	}

	public void setId(FacilityTypeDischargeRefId id) {
		this.id = id;
	}

	public FacilityTypeRef getFacilityTypeRef() {
		return this.facilityTypeRef;
	}

	public void setFacilityTypeRef(FacilityTypeRef facilityTypeRef) {
		this.facilityTypeRef = facilityTypeRef;
	}

	public DischargeMethodRef getDischargeMethodRef() {
		return this.dischargeMethodRef;
	}

	public void setDischargeMethodRef(DischargeMethodRef dischargeMethodRef) {
		this.dischargeMethodRef = dischargeMethodRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
