package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityTypeChange generated by hbm2java
 */
public class FacilityTypeChange implements java.io.Serializable {

	// Fields    

	private FacilityTypeChangeId id;

	private FacilityType facilityType;

	private ChangeTypeRef changeTypeRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityTypeChange() {
	}

	/** full constructor */
	public FacilityTypeChange(FacilityTypeChangeId id,
			FacilityType facilityType, ChangeTypeRef changeTypeRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facilityType = facilityType;
		this.changeTypeRef = changeTypeRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityTypeChangeId getId() {
		return this.id;
	}

	public void setId(FacilityTypeChangeId id) {
		this.id = id;
	}

	public FacilityType getFacilityType() {
		return this.facilityType;
	}

	public void setFacilityType(FacilityType facilityType) {
		this.facilityType = facilityType;
	}

	public ChangeTypeRef getChangeTypeRef() {
		return this.changeTypeRef;
	}

	public void setChangeTypeRef(ChangeTypeRef changeTypeRef) {
		this.changeTypeRef = changeTypeRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
