package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityEntryStatus generated by hbm2java
 */
public class FacilityEntryStatus implements java.io.Serializable {

	// Fields    

	private FacilityEntryStatusId id;

	private DataAreaRef dataAreaRef;

	private Facility facility;

	private char requiredFlag;

	private char enteredFlag;

	private char errorFlag;

	private Date dataAreaLastUpdateTs;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	//private Set facilityDataAreaMessages = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityEntryStatus() {
	}

	/** minimal constructor */
	public FacilityEntryStatus(FacilityEntryStatusId id,
			DataAreaRef dataAreaRef, Facility facility, char requiredFlag,
			char enteredFlag, char errorFlag, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.dataAreaRef = dataAreaRef;
		this.facility = facility;
		this.requiredFlag = requiredFlag;
		this.enteredFlag = enteredFlag;
		this.errorFlag = errorFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityEntryStatus(FacilityEntryStatusId id,
			DataAreaRef dataAreaRef, Facility facility, char requiredFlag,
			char enteredFlag, char errorFlag, Date dataAreaLastUpdateTs,
			String lastUpdateUserid, Date lastUpdateTs) {
//			Set facilityDataAreaMessages) {
		this.id = id;
		this.dataAreaRef = dataAreaRef;
		this.facility = facility;
		this.requiredFlag = requiredFlag;
		this.enteredFlag = enteredFlag;
		this.errorFlag = errorFlag;
		this.dataAreaLastUpdateTs = dataAreaLastUpdateTs;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		//this.facilityDataAreaMessages = facilityDataAreaMessages;
	}

	// Property accessors
	public FacilityEntryStatusId getId() {
		return this.id;
	}

	public void setId(FacilityEntryStatusId id) {
		this.id = id;
	}

	public DataAreaRef getDataAreaRef() {
		return this.dataAreaRef;
	}

	public void setDataAreaRef(DataAreaRef dataAreaRef) {
		this.dataAreaRef = dataAreaRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public char getRequiredFlag() {
		return this.requiredFlag;
	}

	public void setRequiredFlag(char requiredFlag) {
		this.requiredFlag = requiredFlag;
	}

	public char getEnteredFlag() {
		return this.enteredFlag;
	}

	public void setEnteredFlag(char enteredFlag) {
		this.enteredFlag = enteredFlag;
	}

	public char getErrorFlag() {
		return this.errorFlag;
	}

	public void setErrorFlag(char errorFlag) {
		this.errorFlag = errorFlag;
	}

	public Date getDataAreaLastUpdateTs() {
		return this.dataAreaLastUpdateTs;
	}

	public void setDataAreaLastUpdateTs(Date dataAreaLastUpdateTs) {
		this.dataAreaLastUpdateTs = dataAreaLastUpdateTs;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}
/*
	public Set getFacilityDataAreaMessages() {
		return this.facilityDataAreaMessages;
	}

	public void setFacilityDataAreaMessages(Set facilityDataAreaMessages) {
		this.facilityDataAreaMessages = facilityDataAreaMessages;
	}
*/
}
