package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityUtilMgmtPractice generated by hbm2java
 */
public class FacilityUtilMgmtPractice implements java.io.Serializable {

	// Fields    

	private FacilityUtilMgmtPracticeId id;

	private UtilMgmtPracticeRef utilMgmtPracticeRef;

	private Facility facility;

	private UtilMgmtImplmntStatusRef utilMgmtImplmntStatusRef;

	private Long remainingCostToImplement;

	private Long annualCostToOperate;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityUtilMgmtPractice() {
	}

	/** minimal constructor */
	public FacilityUtilMgmtPractice(FacilityUtilMgmtPracticeId id,
			UtilMgmtPracticeRef utilMgmtPracticeRef, Facility facility,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.utilMgmtPracticeRef = utilMgmtPracticeRef;
		this.facility = facility;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityUtilMgmtPractice(FacilityUtilMgmtPracticeId id,
			UtilMgmtPracticeRef utilMgmtPracticeRef, Facility facility,
			UtilMgmtImplmntStatusRef utilMgmtImplmntStatusRef,
			Long remainingCostToImplement, Long annualCostToOperate,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.utilMgmtPracticeRef = utilMgmtPracticeRef;
		this.facility = facility;
		this.utilMgmtImplmntStatusRef = utilMgmtImplmntStatusRef;
		this.remainingCostToImplement = remainingCostToImplement;
		this.annualCostToOperate = annualCostToOperate;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityUtilMgmtPracticeId getId() {
		return this.id;
	}

	public void setId(FacilityUtilMgmtPracticeId id) {
		this.id = id;
	}

	public UtilMgmtPracticeRef getUtilMgmtPracticeRef() {
		return this.utilMgmtPracticeRef;
	}

	public void setUtilMgmtPracticeRef(UtilMgmtPracticeRef utilMgmtPracticeRef) {
		this.utilMgmtPracticeRef = utilMgmtPracticeRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public UtilMgmtImplmntStatusRef getUtilMgmtImplmntStatusRef() {
		return this.utilMgmtImplmntStatusRef;
	}

	public void setUtilMgmtImplmntStatusRef(
			UtilMgmtImplmntStatusRef utilMgmtImplmntStatusRef) {
		this.utilMgmtImplmntStatusRef = utilMgmtImplmntStatusRef;
	}

	public Long getRemainingCostToImplement() {
		return this.remainingCostToImplement;
	}

	public void setRemainingCostToImplement(Long remainingCostToImplement) {
		this.remainingCostToImplement = remainingCostToImplement;
	}

	public Long getAnnualCostToOperate() {
		return this.annualCostToOperate;
	}

	public void setAnnualCostToOperate(Long annualCostToOperate) {
		this.annualCostToOperate = annualCostToOperate;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
