package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityType generated by hbm2java
 */
public class FacilityType implements java.io.Serializable {

	// Fields    

	private FacilityTypeId id;

	private FacilityTypeRef facilityTypeRef;

	private Facility facility;

	private char presentFlag;

	private char projectedFlag;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	private Set facilityTypeChanges = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityType() {
	}

	/** minimal constructor */
	public FacilityType(FacilityTypeId id, FacilityTypeRef facilityTypeRef,
			Facility facility, char presentFlag, char projectedFlag,
			String lastUpdateUserid, Date lastUpdateTs, char feedbackDeleteFlag) {
		this.id = id;
		this.facilityTypeRef = facilityTypeRef;
		this.facility = facility;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	/** full constructor */
	public FacilityType(FacilityTypeId id, FacilityTypeRef facilityTypeRef,
			Facility facility, char presentFlag, char projectedFlag,
			String lastUpdateUserid, Date lastUpdateTs,
			char feedbackDeleteFlag, Set facilityTypeChanges) {
		this.id = id;
		this.facilityTypeRef = facilityTypeRef;
		this.facility = facility;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
		this.facilityTypeChanges = facilityTypeChanges;
	}

	// Property accessors
	public FacilityTypeId getId() {
		return this.id;
	}

	public void setId(FacilityTypeId id) {
		this.id = id;
	}

	public FacilityTypeRef getFacilityTypeRef() {
		return this.facilityTypeRef;
	}

	public void setFacilityTypeRef(FacilityTypeRef facilityTypeRef) {
		this.facilityTypeRef = facilityTypeRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public char getPresentFlag() {
		return this.presentFlag;
	}

	public void setPresentFlag(char presentFlag) {
		this.presentFlag = presentFlag;
	}

	public char getProjectedFlag() {
		return this.projectedFlag;
	}

	public void setProjectedFlag(char projectedFlag) {
		this.projectedFlag = projectedFlag;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	public Set getFacilityTypeChanges() {
		return this.facilityTypeChanges;
	}

	public void setFacilityTypeChanges(Set facilityTypeChanges) {
		this.facilityTypeChanges = facilityTypeChanges;
	}

}
