package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityTypeRef generated by hbm2java
 */
public class FacilityTypeRef implements java.io.Serializable {

	// Fields

	private long facilityTypeId;

	private FacilityOverallTypeRef facilityOverallTypeRef;

	private String name;

	private char validForPopulationFlag;

	private char validForFlowFlag;

	private char validForDischargeFlag;

	private char validForEffluentFlag;

	private char validForPollutionFlag;

	private char validForCsoFlag;

	private char validForUnitProcessFlag;

	private char validForUtilMgmtFlag;

	private char validForRespnsblePartyFlag;

	private char popRecCollectionFlag;

	private char popTreatmentFlag;

	private char popOwtsFlag;

	private char popClusteredFlag;

	private char federalNeedsForPrivateFlag;

	private byte sortSequence;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityTypes = new HashSet(0);

	private Set facilityTypeRuleRefsForFacilityTypeId2 = new HashSet(0);

	private Set facilityTypeChangeRefs = new HashSet(0);

	private Set facilityTypeDischargeRefs = new HashSet(0);

	private Set facilityTypeCategoryRefs = new HashSet(0);

	private Set facilityTypeRuleRefsForFacilityTypeId1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityTypeRef() {
	}

	/** minimal constructor */
	public FacilityTypeRef(long facilityTypeId,
			FacilityOverallTypeRef facilityOverallTypeRef, String name,
			char validForPopulationFlag, char validForFlowFlag,
			char validForDischargeFlag, char validForEffluentFlag,
			char validForPollutionFlag, char validForCsoFlag,
			char validForUnitProcessFlag, char validForUtilMgmtFlag,
			char validForRespnsblePartyFlag, char popRecCollectionFlag,
			char popTreatmentFlag, char popOwtsFlag, char popClusteredFlag,
			char federalNeedsForPrivateFlag, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.facilityTypeId = facilityTypeId;
		this.facilityOverallTypeRef = facilityOverallTypeRef;
		this.name = name;
		this.validForPopulationFlag = validForPopulationFlag;
		this.validForFlowFlag = validForFlowFlag;
		this.validForDischargeFlag = validForDischargeFlag;
		this.validForEffluentFlag = validForEffluentFlag;
		this.validForPollutionFlag = validForPollutionFlag;
		this.validForCsoFlag = validForCsoFlag;
		this.validForUnitProcessFlag = validForUnitProcessFlag;
		this.validForUtilMgmtFlag = validForUtilMgmtFlag;
		this.validForRespnsblePartyFlag = validForRespnsblePartyFlag;
		this.popRecCollectionFlag = popRecCollectionFlag;
		this.popTreatmentFlag = popTreatmentFlag;
		this.popOwtsFlag = popOwtsFlag;
		this.popClusteredFlag = popClusteredFlag;
		this.federalNeedsForPrivateFlag = federalNeedsForPrivateFlag;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityTypeRef(long facilityTypeId,
			FacilityOverallTypeRef facilityOverallTypeRef, String name,
			char validForPopulationFlag, char validForFlowFlag,
			char validForDischargeFlag, char validForEffluentFlag,
			char validForPollutionFlag, char validForCsoFlag,
			char validForUnitProcessFlag, char validForUtilMgmtFlag,
			char validForRespnsblePartyFlag, char popRecCollectionFlag,
			char popTreatmentFlag, char popOwtsFlag, char popClusteredFlag,
			char federalNeedsForPrivateFlag, byte sortSequence,
			String lastUpdateUserid, Date lastUpdateTs, Set facilityTypes,
			Set facilityTypeRuleRefsForFacilityTypeId2,
			Set facilityTypeChangeRefs, Set facilityTypeDischargeRefs,
			Set facilityTypeCategoryRefs,
			Set facilityTypeRuleRefsForFacilityTypeId1) {
		this.facilityTypeId = facilityTypeId;
		this.facilityOverallTypeRef = facilityOverallTypeRef;
		this.name = name;
		this.validForPopulationFlag = validForPopulationFlag;
		this.validForFlowFlag = validForFlowFlag;
		this.validForDischargeFlag = validForDischargeFlag;
		this.validForEffluentFlag = validForEffluentFlag;
		this.validForPollutionFlag = validForPollutionFlag;
		this.validForCsoFlag = validForCsoFlag;
		this.validForUnitProcessFlag = validForUnitProcessFlag;
		this.validForUtilMgmtFlag = validForUtilMgmtFlag;
		this.validForRespnsblePartyFlag = validForRespnsblePartyFlag;
		this.popRecCollectionFlag = popRecCollectionFlag;
		this.popTreatmentFlag = popTreatmentFlag;
		this.popOwtsFlag = popOwtsFlag;
		this.popClusteredFlag = popClusteredFlag;
		this.federalNeedsForPrivateFlag = federalNeedsForPrivateFlag;
		this.sortSequence = sortSequence;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityTypes = facilityTypes;
		this.facilityTypeRuleRefsForFacilityTypeId2 = facilityTypeRuleRefsForFacilityTypeId2;
		this.facilityTypeChangeRefs = facilityTypeChangeRefs;
		this.facilityTypeDischargeRefs = facilityTypeDischargeRefs;
		this.facilityTypeCategoryRefs = facilityTypeCategoryRefs;
		this.facilityTypeRuleRefsForFacilityTypeId1 = facilityTypeRuleRefsForFacilityTypeId1;
	}

	// Property accessors
	public long getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(long facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public FacilityOverallTypeRef getFacilityOverallTypeRef() {
		return this.facilityOverallTypeRef;
	}

	public void setFacilityOverallTypeRef(
			FacilityOverallTypeRef facilityOverallTypeRef) {
		this.facilityOverallTypeRef = facilityOverallTypeRef;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public char getValidForPopulationFlag() {
		return this.validForPopulationFlag;
	}

	public void setValidForPopulationFlag(char validForPopulationFlag) {
		this.validForPopulationFlag = validForPopulationFlag;
	}

	public char getValidForFlowFlag() {
		return this.validForFlowFlag;
	}

	public void setValidForFlowFlag(char validForFlowFlag) {
		this.validForFlowFlag = validForFlowFlag;
	}

	public char getValidForDischargeFlag() {
		return this.validForDischargeFlag;
	}

	public void setValidForDischargeFlag(char validForDischargeFlag) {
		this.validForDischargeFlag = validForDischargeFlag;
	}

	public char getValidForEffluentFlag() {
		return this.validForEffluentFlag;
	}

	public void setValidForEffluentFlag(char validForEffluentFlag) {
		this.validForEffluentFlag = validForEffluentFlag;
	}

	public char getValidForPollutionFlag() {
		return this.validForPollutionFlag;
	}

	public void setValidForPollutionFlag(char validForPollutionFlag) {
		this.validForPollutionFlag = validForPollutionFlag;
	}

	public char getValidForCsoFlag() {
		return this.validForCsoFlag;
	}

	public void setValidForCsoFlag(char validForCsoFlag) {
		this.validForCsoFlag = validForCsoFlag;
	}

	public char getValidForUnitProcessFlag() {
		return this.validForUnitProcessFlag;
	}

	public void setValidForUnitProcessFlag(char validForUnitProcessFlag) {
		this.validForUnitProcessFlag = validForUnitProcessFlag;
	}

	public char getValidForUtilMgmtFlag() {
		return this.validForUtilMgmtFlag;
	}

	public void setValidForUtilMgmtFlag(char validForUtilMgmtFlag) {
		this.validForUtilMgmtFlag = validForUtilMgmtFlag;
	}

	public char getValidForRespnsblePartyFlag() {
		return this.validForRespnsblePartyFlag;
	}

	public void setValidForRespnsblePartyFlag(char validForRespnsblePartyFlag) {
		this.validForRespnsblePartyFlag = validForRespnsblePartyFlag;
	}

	public char getPopRecCollectionFlag() {
		return this.popRecCollectionFlag;
	}

	public void setPopRecCollectionFlag(char popRecCollectionFlag) {
		this.popRecCollectionFlag = popRecCollectionFlag;
	}

	public char getPopTreatmentFlag() {
		return this.popTreatmentFlag;
	}

	public void setPopTreatmentFlag(char popTreatmentFlag) {
		this.popTreatmentFlag = popTreatmentFlag;
	}

	public char getPopOwtsFlag() {
		return this.popOwtsFlag;
	}

	public void setPopOwtsFlag(char popOwtsFlag) {
		this.popOwtsFlag = popOwtsFlag;
	}

	public char getPopClusteredFlag() {
		return this.popClusteredFlag;
	}

	public void setPopClusteredFlag(char popClusteredFlag) {
		this.popClusteredFlag = popClusteredFlag;
	}

	public char getFederalNeedsForPrivateFlag() {
		return this.federalNeedsForPrivateFlag;
	}

	public void setFederalNeedsForPrivateFlag(char federalNeedsForPrivateFlag) {
		this.federalNeedsForPrivateFlag = federalNeedsForPrivateFlag;
	}

	public byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityTypes() {
		return this.facilityTypes;
	}

	public void setFacilityTypes(Set facilityTypes) {
		this.facilityTypes = facilityTypes;
	}

	public Set getFacilityTypeRuleRefsForFacilityTypeId2() {
		return this.facilityTypeRuleRefsForFacilityTypeId2;
	}

	public void setFacilityTypeRuleRefsForFacilityTypeId2(
			Set facilityTypeRuleRefsForFacilityTypeId2) {
		this.facilityTypeRuleRefsForFacilityTypeId2 = facilityTypeRuleRefsForFacilityTypeId2;
	}

	public Set getFacilityTypeChangeRefs() {
		return this.facilityTypeChangeRefs;
	}

	public void setFacilityTypeChangeRefs(Set facilityTypeChangeRefs) {
		this.facilityTypeChangeRefs = facilityTypeChangeRefs;
	}

	public Set getFacilityTypeDischargeRefs() {
		return this.facilityTypeDischargeRefs;
	}

	public void setFacilityTypeDischargeRefs(Set facilityTypeDischargeRefs) {
		this.facilityTypeDischargeRefs = facilityTypeDischargeRefs;
	}

	public Set getFacilityTypeCategoryRefs() {
		return this.facilityTypeCategoryRefs;
	}

	public void setFacilityTypeCategoryRefs(Set facilityTypeCategoryRefs) {
		this.facilityTypeCategoryRefs = facilityTypeCategoryRefs;
	}

	public Set getFacilityTypeRuleRefsForFacilityTypeId1() {
		return this.facilityTypeRuleRefsForFacilityTypeId1;
	}

	public void setFacilityTypeRuleRefsForFacilityTypeId1(
			Set facilityTypeRuleRefsForFacilityTypeId1) {
		this.facilityTypeRuleRefsForFacilityTypeId1 = facilityTypeRuleRefsForFacilityTypeId1;
	}

}
