package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * FacilityPopulationUnit generated by hbm2java
 */
public class FacilityPopulationUnit implements java.io.Serializable {

	// Fields    

	private FacilityPopulationUnitId id;

	private PopulationRef populationRef;

	private Facility facility;

	private Integer presentUnitsCount;

	private Integer projectedUnitsCount;

	private BigDecimal populationPerUnit;

	private Short projectedYear;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityPopulationUnit() {
	}

	/** minimal constructor */
	public FacilityPopulationUnit(FacilityPopulationUnitId id,
			PopulationRef populationRef, Facility facility,
			BigDecimal populationPerUnit, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.populationRef = populationRef;
		this.facility = facility;
		this.populationPerUnit = populationPerUnit;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityPopulationUnit(FacilityPopulationUnitId id,
			PopulationRef populationRef, Facility facility,
			Integer presentUnitsCount, Integer projectedUnitsCount,
			BigDecimal populationPerUnit, Short projectedYear,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.populationRef = populationRef;
		this.facility = facility;
		this.presentUnitsCount = presentUnitsCount;
		this.projectedUnitsCount = projectedUnitsCount;
		this.populationPerUnit = populationPerUnit;
		this.projectedYear = projectedYear;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityPopulationUnitId getId() {
		return this.id;
	}

	public void setId(FacilityPopulationUnitId id) {
		this.id = id;
	}

	public PopulationRef getPopulationRef() {
		return this.populationRef;
	}

	public void setPopulationRef(PopulationRef populationRef) {
		this.populationRef = populationRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public Integer getPresentUnitsCount() {
		return this.presentUnitsCount;
	}

	public void setPresentUnitsCount(Integer presentUnitsCount) {
		this.presentUnitsCount = presentUnitsCount;
	}

	public Integer getProjectedUnitsCount() {
		return this.projectedUnitsCount;
	}

	public void setProjectedUnitsCount(Integer projectedUnitsCount) {
		this.projectedUnitsCount = projectedUnitsCount;
	}

	public BigDecimal getPopulationPerUnit() {
		return this.populationPerUnit;
	}

	public void setPopulationPerUnit(BigDecimal populationPerUnit) {
		this.populationPerUnit = populationPerUnit;
	}

	public Short getProjectedYear() {
		return this.projectedYear;
	}

	public void setProjectedYear(Short projectedYear) {
		this.projectedYear = projectedYear;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
