package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * FacilityFlow generated by hbm2java
 */
public class FacilityFlow implements java.io.Serializable {

	// Fields    

	private FacilityFlowId id;

	private FlowRef flowRef;

	private Facility facility;

	private BigDecimal existingFlowMsr;

	private BigDecimal presentFlowMsr;

	private BigDecimal projectedFlowMsr;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityFlow() {
	}

	/** minimal constructor */
	public FacilityFlow(FacilityFlowId id, FlowRef flowRef, Facility facility,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.flowRef = flowRef;
		this.facility = facility;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityFlow(FacilityFlowId id, FlowRef flowRef, Facility facility,
			BigDecimal existingFlowMsr, BigDecimal presentFlowMsr,
			BigDecimal projectedFlowMsr, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.flowRef = flowRef;
		this.facility = facility;
		this.existingFlowMsr = existingFlowMsr;
		this.presentFlowMsr = presentFlowMsr;
		this.projectedFlowMsr = projectedFlowMsr;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityFlowId getId() {
		return this.id;
	}

	public void setId(FacilityFlowId id) {
		this.id = id;
	}

	public FlowRef getFlowRef() {
		return this.flowRef;
	}

	public void setFlowRef(FlowRef flowRef) {
		this.flowRef = flowRef;
	}

	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	public BigDecimal getExistingFlowMsr() {
		return this.existingFlowMsr;
	}

	public void setExistingFlowMsr(BigDecimal existingFlowMsr) {
		this.existingFlowMsr = existingFlowMsr;
	}

	public BigDecimal getPresentFlowMsr() {
		return this.presentFlowMsr;
	}

	public void setPresentFlowMsr(BigDecimal presentFlowMsr) {
		this.presentFlowMsr = presentFlowMsr;
	}

	public BigDecimal getProjectedFlowMsr() {
		return this.projectedFlowMsr;
	}

	public void setProjectedFlowMsr(BigDecimal projectedFlowMsr) {
		this.projectedFlowMsr = projectedFlowMsr;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
