package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * FacilityDataAreaMessage generated by hbm2java
 */
public class FacilityDataAreaMessage implements java.io.Serializable {

	// Fields    

	private FacilityDataAreaMessageId id;

	private FacilityEntryStatus facilityEntryStatus;

	private Character globalFlag;

	private String sourceCode;

	private char messageCode;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public FacilityDataAreaMessage() {
	}

	/** minimal constructor */
	public FacilityDataAreaMessage(FacilityDataAreaMessageId id,
			FacilityEntryStatus facilityEntryStatus, String sourceCode,
			char messageCode, String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.facilityEntryStatus = facilityEntryStatus;
		this.sourceCode = sourceCode;
		this.messageCode = messageCode;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FacilityDataAreaMessage(FacilityDataAreaMessageId id,
			FacilityEntryStatus facilityEntryStatus, Character globalFlag,
			String sourceCode, char messageCode, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.id = id;
		this.facilityEntryStatus = facilityEntryStatus;
		this.globalFlag = globalFlag;
		this.sourceCode = sourceCode;
		this.messageCode = messageCode;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public FacilityDataAreaMessageId getId() {
		return this.id;
	}

	public void setId(FacilityDataAreaMessageId id) {
		this.id = id;
	}

	public FacilityEntryStatus getFacilityEntryStatus() {
		return this.facilityEntryStatus;
	}

	public void setFacilityEntryStatus(FacilityEntryStatus facilityEntryStatus) {
		this.facilityEntryStatus = facilityEntryStatus;
	}

	public Character getGlobalFlag() {
		return this.globalFlag;
	}

	public void setGlobalFlag(Character globalFlag) {
		this.globalFlag = globalFlag;
	}

	public String getSourceCode() {
		return this.sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public char getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(char messageCode) {
		this.messageCode = messageCode;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
