package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityTypeChangeId generated by hbm2java
 */
public class FacilityTypeChangeId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long facilityTypeId;

	private long changeTypeId;

	// Constructors

	/** default constructor */
	public FacilityTypeChangeId() {
	}

	/** full constructor */
	public FacilityTypeChangeId(long facilityId, long facilityTypeId,
			long changeTypeId) {
		this.facilityId = facilityId;
		this.facilityTypeId = facilityTypeId;
		this.changeTypeId = changeTypeId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(long facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public long getChangeTypeId() {
		return this.changeTypeId;
	}

	public void setChangeTypeId(long changeTypeId) {
		this.changeTypeId = changeTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityTypeChangeId))
			return false;
		FacilityTypeChangeId castOther = (FacilityTypeChangeId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getFacilityTypeId() == castOther
						.getFacilityTypeId())
				&& (this.getChangeTypeId() == castOther.getChangeTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getFacilityTypeId();
		result = 37 * result + (int) this.getChangeTypeId();
		return result;
	}

}
