package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityPermitId generated by hbm2java
 */
public class FacilityPermitId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long permitId;

	// Constructors

	/** default constructor */
	public FacilityPermitId() {
	}

	/** full constructor */
	public FacilityPermitId(long facilityId, long permitId) {
		this.facilityId = facilityId;
		this.permitId = permitId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getPermitId() {
		return this.permitId;
	}

	public void setPermitId(long permitId) {
		this.permitId = permitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityPermitId))
			return false;
		FacilityPermitId castOther = (FacilityPermitId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getPermitId() == castOther.getPermitId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getPermitId();
		return result;
	}

}
