package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * FacilityTypeId generated by hbm2java
 */
public class FacilityTypeId implements java.io.Serializable {

	// Fields

	private long facilityId;

	private long facilityTypeId;

	// Constructors

	/** default constructor */
	public FacilityTypeId() {
	}

	/** full constructor */
	public FacilityTypeId(long facilityId, long facilityTypeId) {
		this.facilityId = facilityId;
		this.facilityTypeId = facilityTypeId;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public long getFacilityTypeId() {
		return this.facilityTypeId;
	}

	public void setFacilityTypeId(long facilityTypeId) {
		this.facilityTypeId = facilityTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacilityTypeId))
			return false;
		FacilityTypeId castOther = (FacilityTypeId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& (this.getFacilityTypeId() == castOther
						.getFacilityTypeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result + (int) this.getFacilityTypeId();
		return result;
	}

}
