package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facility generated by hbm2java
 */
public class Facility implements java.io.Serializable {
	
	//constants
	public static final char TREATMENT_PLANT_TYPE_LAGOON = 'L';	
	public static final char TREATMENT_PLANT_TYPE_MECHANICAL = 'M';
	public static final char TREATMENT_PLANT_TYPE_NONE = 'N';	

	// Fields

	private long facilityId;

	private ReviewStatusRef reviewStatusRef;

	private System system;

	private char versionCode;

	private String locationId;

	private String cwnsNbr;

	private String name;

	private String description;

	private String ownerCode;

	private char militaryFlag;

	private Character tmdlFlag;

	private Character sourceWaterProtectionFlag;

	private char smallCommunityExceptionFlag;

	private Character presentTreatmentPlantType;

	private Character projectedTreatmentPlantType;

	private char localUserDoesUnitProcFlag;

	private char localUserDoesUtilMgmtFlag;

	private String npsTypeCode;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityAddresses = new HashSet(0);

	private Set combinedSewers = new HashSet(0);

	private Set facilityEntryStatuses = new HashSet(0);

	private Set facilityReviewStatuses = new HashSet(0);

	private Set facilityPointOfContacts = new HashSet(0);

	private Set facilityComments = new HashSet(0);

	private Set facilityFlows = new HashSet(0);

	private Set fundingSources = new HashSet(0);

	private Set facilityDischargesForFacilityIdDischargeTo = new HashSet(0);

	private Set facilityDischargesForFacilityId = new HashSet(0);

	private Set csoImperviousnesses = new HashSet(0);

	private Set reviewComments = new HashSet(0);

	private Set facilityEffluents = new HashSet(0);

	private Set operationAndMaintenanceCosts = new HashSet(0);

	private Set facilityPollutionProblems = new HashSet(0);

	private Set facilityUnitProcesses = new HashSet(0);

	private Set facilityUtilMgmtPractices = new HashSet(0);

	private Set facilityImpairedWaters = new HashSet(0);

	private Set facilityDocuments = new HashSet(0);

	private Set geographicAreas = new HashSet(0);

	private Set rainfalls = new HashSet(0);

	private Set facilityPopulations = new HashSet(0);

	private Set facilityPermits = new HashSet(0);

	private Set cwnsUserLocationFacilities = new HashSet(0);

	private Set federalReviewStatuses = new HashSet(0);

	private Set facilityTypes = new HashSet(0);

	private Set facilityPopulationUnits = new HashSet(0);

	// Constructors

	/** default constructor */
	public Facility() {
	}

	/** minimal constructor */
	public Facility(long facilityId, ReviewStatusRef reviewStatusRef,
			char versionCode, String locationId, String name,
			char militaryFlag, char smallCommunityExceptionFlag,
			char localUserDoesUnitProcFlag, char localUserDoesUtilMgmtFlag,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.facilityId = facilityId;
		this.reviewStatusRef = reviewStatusRef;
		this.versionCode = versionCode;
		this.locationId = locationId;
		this.name = name;
		this.militaryFlag = militaryFlag;
		this.smallCommunityExceptionFlag = smallCommunityExceptionFlag;
		this.localUserDoesUnitProcFlag = localUserDoesUnitProcFlag;
		this.localUserDoesUtilMgmtFlag = localUserDoesUtilMgmtFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public Facility(long facilityId, ReviewStatusRef reviewStatusRef,
			System system, char versionCode, String locationId, String cwnsNbr,
			String name, String description, String ownerCode,
			char militaryFlag, Character tmdlFlag,
			Character sourceWaterProtectionFlag,
			char smallCommunityExceptionFlag,
			Character presentTreatmentPlantType,
			Character projectedTreatmentPlantType,
			char localUserDoesUnitProcFlag, char localUserDoesUtilMgmtFlag,
			String npsTypeCode, String lastUpdateUserid, Date lastUpdateTs,
			Set facilityAddresses, Set combinedSewers,
			Set facilityEntryStatuses, Set facilityReviewStatuses,
			Set facilityPointOfContacts, Set facilityComments,
			Set facilityFlows, Set fundingSources,
			Set facilityDischargesForFacilityIdDischargeTo,
			Set facilityDischargesForFacilityId, Set csoImperviousnesses,
			Set reviewComments, Set facilityEffluents,
			Set operationAndMaintenanceCosts, Set facilityPollutionProblems,
			Set facilityUnitProcesses, Set facilityUtilMgmtPractices,
			Set facilityImpairedWaters, Set facilityDocuments,
			Set geographicAreas, Set rainfalls, Set facilityPopulations,
			Set facilityPermits, Set cwnsUserLocationFacilities,
			Set federalReviewStatuses, Set facilityTypes,
			Set facilityPopulationUnits) {
		this.facilityId = facilityId;
		this.reviewStatusRef = reviewStatusRef;
		this.system = system;
		this.versionCode = versionCode;
		this.locationId = locationId;
		this.cwnsNbr = cwnsNbr;
		this.name = name;
		this.description = description;
		this.ownerCode = ownerCode;
		this.militaryFlag = militaryFlag;
		this.tmdlFlag = tmdlFlag;
		this.sourceWaterProtectionFlag = sourceWaterProtectionFlag;
		this.smallCommunityExceptionFlag = smallCommunityExceptionFlag;
		this.presentTreatmentPlantType = presentTreatmentPlantType;
		this.projectedTreatmentPlantType = projectedTreatmentPlantType;
		this.localUserDoesUnitProcFlag = localUserDoesUnitProcFlag;
		this.localUserDoesUtilMgmtFlag = localUserDoesUtilMgmtFlag;
		this.npsTypeCode = npsTypeCode;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityAddresses = facilityAddresses;
		this.combinedSewers = combinedSewers;
		this.facilityEntryStatuses = facilityEntryStatuses;
		this.facilityReviewStatuses = facilityReviewStatuses;
		this.facilityPointOfContacts = facilityPointOfContacts;
		this.facilityComments = facilityComments;
		this.facilityFlows = facilityFlows;
		this.fundingSources = fundingSources;
		this.facilityDischargesForFacilityIdDischargeTo = facilityDischargesForFacilityIdDischargeTo;
		this.facilityDischargesForFacilityId = facilityDischargesForFacilityId;
		this.csoImperviousnesses = csoImperviousnesses;
		this.reviewComments = reviewComments;
		this.facilityEffluents = facilityEffluents;
		this.operationAndMaintenanceCosts = operationAndMaintenanceCosts;
		this.facilityPollutionProblems = facilityPollutionProblems;
		this.facilityUnitProcesses = facilityUnitProcesses;
		this.facilityUtilMgmtPractices = facilityUtilMgmtPractices;
		this.facilityImpairedWaters = facilityImpairedWaters;
		this.facilityDocuments = facilityDocuments;
		this.geographicAreas = geographicAreas;
		this.rainfalls = rainfalls;
		this.facilityPopulations = facilityPopulations;
		this.facilityPermits = facilityPermits;
		this.cwnsUserLocationFacilities = cwnsUserLocationFacilities;
		this.federalReviewStatuses = federalReviewStatuses;
		this.facilityTypes = facilityTypes;
		this.facilityPopulationUnits = facilityPopulationUnits;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public ReviewStatusRef getReviewStatusRef() {
		return this.reviewStatusRef;
	}

	public void setReviewStatusRef(ReviewStatusRef reviewStatusRef) {
		this.reviewStatusRef = reviewStatusRef;
	}

	public System getSystem() {
		return this.system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	public char getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(char versionCode) {
		this.versionCode = versionCode;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getCwnsNbr() {
		return this.cwnsNbr;
	}

	public void setCwnsNbr(String cwnsNbr) {
		this.cwnsNbr = cwnsNbr;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getOwnerCode() {
		return this.ownerCode;
	}

	public void setOwnerCode(String ownerCode) {
		this.ownerCode = ownerCode;
	}

	public char getMilitaryFlag() {
		return this.militaryFlag;
	}

	public void setMilitaryFlag(char militaryFlag) {
		this.militaryFlag = militaryFlag;
	}

	public Character getTmdlFlag() {
		return this.tmdlFlag;
	}

	public void setTmdlFlag(Character tmdlFlag) {
		this.tmdlFlag = tmdlFlag;
	}

	public Character getSourceWaterProtectionFlag() {
		return this.sourceWaterProtectionFlag;
	}

	public void setSourceWaterProtectionFlag(Character sourceWaterProtectionFlag) {
		this.sourceWaterProtectionFlag = sourceWaterProtectionFlag;
	}

	public char getSmallCommunityExceptionFlag() {
		return this.smallCommunityExceptionFlag;
	}

	public void setSmallCommunityExceptionFlag(char smallCommunityExceptionFlag) {
		this.smallCommunityExceptionFlag = smallCommunityExceptionFlag;
	}

	public Character getPresentTreatmentPlantType() {
		return this.presentTreatmentPlantType;
	}

	public void setPresentTreatmentPlantType(Character presentTreatmentPlantType) {
		this.presentTreatmentPlantType = presentTreatmentPlantType;
	}

	public Character getProjectedTreatmentPlantType() {
		return this.projectedTreatmentPlantType;
	}

	public void setProjectedTreatmentPlantType(
			Character projectedTreatmentPlantType) {
		this.projectedTreatmentPlantType = projectedTreatmentPlantType;
	}

	public char getLocalUserDoesUnitProcFlag() {
		return this.localUserDoesUnitProcFlag;
	}

	public void setLocalUserDoesUnitProcFlag(char localUserDoesUnitProcFlag) {
		this.localUserDoesUnitProcFlag = localUserDoesUnitProcFlag;
	}

	public char getLocalUserDoesUtilMgmtFlag() {
		return this.localUserDoesUtilMgmtFlag;
	}

	public void setLocalUserDoesUtilMgmtFlag(char localUserDoesUtilMgmtFlag) {
		this.localUserDoesUtilMgmtFlag = localUserDoesUtilMgmtFlag;
	}

	public String getNpsTypeCode() {
		return this.npsTypeCode;
	}

	public void setNpsTypeCode(String npsTypeCode) {
		this.npsTypeCode = npsTypeCode;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityAddresses() {
		return this.facilityAddresses;
	}

	public void setFacilityAddresses(Set facilityAddresses) {
		this.facilityAddresses = facilityAddresses;
	}

	public Set getCombinedSewers() {
		return this.combinedSewers;
	}

	public void setCombinedSewers(Set combinedSewers) {
		this.combinedSewers = combinedSewers;
	}

	public Set getFacilityEntryStatuses() {
		return this.facilityEntryStatuses;
	}

	public void setFacilityEntryStatuses(Set facilityEntryStatuses) {
		this.facilityEntryStatuses = facilityEntryStatuses;
	}

	public Set getFacilityReviewStatuses() {
		return this.facilityReviewStatuses;
	}

	public void setFacilityReviewStatuses(Set facilityReviewStatuses) {
		this.facilityReviewStatuses = facilityReviewStatuses;
	}

	public Set getFacilityPointOfContacts() {
		return this.facilityPointOfContacts;
	}

	public void setFacilityPointOfContacts(Set facilityPointOfContacts) {
		this.facilityPointOfContacts = facilityPointOfContacts;
	}

	public Set getFacilityComments() {
		return this.facilityComments;
	}

	public void setFacilityComments(Set facilityComments) {
		this.facilityComments = facilityComments;
	}

	public Set getFacilityFlows() {
		return this.facilityFlows;
	}

	public void setFacilityFlows(Set facilityFlows) {
		this.facilityFlows = facilityFlows;
	}

	public Set getFundingSources() {
		return this.fundingSources;
	}

	public void setFundingSources(Set fundingSources) {
		this.fundingSources = fundingSources;
	}

	public Set getFacilityDischargesForFacilityIdDischargeTo() {
		return this.facilityDischargesForFacilityIdDischargeTo;
	}

	public void setFacilityDischargesForFacilityIdDischargeTo(
			Set facilityDischargesForFacilityIdDischargeTo) {
		this.facilityDischargesForFacilityIdDischargeTo = facilityDischargesForFacilityIdDischargeTo;
	}

	public Set getFacilityDischargesForFacilityId() {
		return this.facilityDischargesForFacilityId;
	}

	public void setFacilityDischargesForFacilityId(
			Set facilityDischargesForFacilityId) {
		this.facilityDischargesForFacilityId = facilityDischargesForFacilityId;
	}

	public Set getCsoImperviousnesses() {
		return this.csoImperviousnesses;
	}

	public void setCsoImperviousnesses(Set csoImperviousnesses) {
		this.csoImperviousnesses = csoImperviousnesses;
	}

	public Set getReviewComments() {
		return this.reviewComments;
	}

	public void setReviewComments(Set reviewComments) {
		this.reviewComments = reviewComments;
	}

	public Set getFacilityEffluents() {
		return this.facilityEffluents;
	}

	public void setFacilityEffluents(Set facilityEffluents) {
		this.facilityEffluents = facilityEffluents;
	}

	public Set getOperationAndMaintenanceCosts() {
		return this.operationAndMaintenanceCosts;
	}

	public void setOperationAndMaintenanceCosts(Set operationAndMaintenanceCosts) {
		this.operationAndMaintenanceCosts = operationAndMaintenanceCosts;
	}

	public Set getFacilityPollutionProblems() {
		return this.facilityPollutionProblems;
	}

	public void setFacilityPollutionProblems(Set facilityPollutionProblems) {
		this.facilityPollutionProblems = facilityPollutionProblems;
	}

	public Set getFacilityUnitProcesses() {
		return this.facilityUnitProcesses;
	}

	public void setFacilityUnitProcesses(Set facilityUnitProcesses) {
		this.facilityUnitProcesses = facilityUnitProcesses;
	}

	public Set getFacilityUtilMgmtPractices() {
		return this.facilityUtilMgmtPractices;
	}

	public void setFacilityUtilMgmtPractices(Set facilityUtilMgmtPractices) {
		this.facilityUtilMgmtPractices = facilityUtilMgmtPractices;
	}

	public Set getFacilityImpairedWaters() {
		return this.facilityImpairedWaters;
	}

	public void setFacilityImpairedWaters(Set facilityImpairedWaters) {
		this.facilityImpairedWaters = facilityImpairedWaters;
	}

	public Set getFacilityDocuments() {
		return this.facilityDocuments;
	}

	public void setFacilityDocuments(Set facilityDocuments) {
		this.facilityDocuments = facilityDocuments;
	}

	public Set getGeographicAreas() {
		return this.geographicAreas;
	}

	public void setGeographicAreas(Set geographicAreas) {
		this.geographicAreas = geographicAreas;
	}

	public Set getRainfalls() {
		return this.rainfalls;
	}

	public void setRainfalls(Set rainfalls) {
		this.rainfalls = rainfalls;
	}

	public Set getFacilityPopulations() {
		return this.facilityPopulations;
	}

	public void setFacilityPopulations(Set facilityPopulations) {
		this.facilityPopulations = facilityPopulations;
	}

	public Set getFacilityPermits() {
		return this.facilityPermits;
	}

	public void setFacilityPermits(Set facilityPermits) {
		this.facilityPermits = facilityPermits;
	}

	public Set getCwnsUserLocationFacilities() {
		return this.cwnsUserLocationFacilities;
	}

	public void setCwnsUserLocationFacilities(Set cwnsUserLocationFacilities) {
		this.cwnsUserLocationFacilities = cwnsUserLocationFacilities;
	}

	public Set getFederalReviewStatuses() {
		return this.federalReviewStatuses;
	}

	public void setFederalReviewStatuses(Set federalReviewStatuses) {
		this.federalReviewStatuses = federalReviewStatuses;
	}

	public Set getFacilityTypes() {
		return this.facilityTypes;
	}

	public void setFacilityTypes(Set facilityTypes) {
		this.facilityTypes = facilityTypes;
	}

	public Set getFacilityPopulationUnits() {
		return this.facilityPopulationUnits;
	}

	public void setFacilityPopulationUnits(Set facilityPopulationUnits) {
		this.facilityPopulationUnits = facilityPopulationUnits;
	}

}
