package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacilityDischarge generated by hbm2java
 */
public class FacilityDischarge implements java.io.Serializable {

	// Fields

	private long facilityDischargeId;

	private Facility facilityByFacilityId;

	private Facility facilityByFacilityIdDischargeTo;

	private DischargeMethodRef dischargeMethodRef;

	private char presentFlag;

	private char projectedFlag;

	private Short presentFlowPortionPersent;

	private Short projectedFlowPortionPersent;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private char feedbackDeleteFlag;

	private Set geographicAreas = new HashSet(0);

	// Constructors

	/** default constructor */
	public FacilityDischarge() {
	}

	/** minimal constructor */
	public FacilityDischarge(long facilityDischargeId,
			Facility facilityByFacilityId,
			DischargeMethodRef dischargeMethodRef, char presentFlag,
			char projectedFlag, String lastUpdateUserid, Date lastUpdateTs,
			char feedbackDeleteFlag) {
		this.facilityDischargeId = facilityDischargeId;
		this.facilityByFacilityId = facilityByFacilityId;
		this.dischargeMethodRef = dischargeMethodRef;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	/** full constructor */
	public FacilityDischarge(long facilityDischargeId,
			Facility facilityByFacilityId,
			Facility facilityByFacilityIdDischargeTo,
			DischargeMethodRef dischargeMethodRef, char presentFlag,
			char projectedFlag, Short presentFlowPortionPersent,
			Short projectedFlowPortionPersent, String lastUpdateUserid,
			Date lastUpdateTs, char feedbackDeleteFlag, Set geographicAreas) {
		this.facilityDischargeId = facilityDischargeId;
		this.facilityByFacilityId = facilityByFacilityId;
		this.facilityByFacilityIdDischargeTo = facilityByFacilityIdDischargeTo;
		this.dischargeMethodRef = dischargeMethodRef;
		this.presentFlag = presentFlag;
		this.projectedFlag = projectedFlag;
		this.presentFlowPortionPersent = presentFlowPortionPersent;
		this.projectedFlowPortionPersent = projectedFlowPortionPersent;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.feedbackDeleteFlag = feedbackDeleteFlag;
		this.geographicAreas = geographicAreas;
	}

	// Property accessors
	public long getFacilityDischargeId() {
		return this.facilityDischargeId;
	}

	public void setFacilityDischargeId(long facilityDischargeId) {
		this.facilityDischargeId = facilityDischargeId;
	}

	public Facility getFacilityByFacilityId() {
		return this.facilityByFacilityId;
	}

	public void setFacilityByFacilityId(Facility facilityByFacilityId) {
		this.facilityByFacilityId = facilityByFacilityId;
	}

	public Facility getFacilityByFacilityIdDischargeTo() {
		return this.facilityByFacilityIdDischargeTo;
	}

	public void setFacilityByFacilityIdDischargeTo(
			Facility facilityByFacilityIdDischargeTo) {
		this.facilityByFacilityIdDischargeTo = facilityByFacilityIdDischargeTo;
	}

	public DischargeMethodRef getDischargeMethodRef() {
		return this.dischargeMethodRef;
	}

	public void setDischargeMethodRef(DischargeMethodRef dischargeMethodRef) {
		this.dischargeMethodRef = dischargeMethodRef;
	}

	public char getPresentFlag() {
		return this.presentFlag;
	}

	public void setPresentFlag(char presentFlag) {
		this.presentFlag = presentFlag;
	}

	public char getProjectedFlag() {
		return this.projectedFlag;
	}

	public void setProjectedFlag(char projectedFlag) {
		this.projectedFlag = projectedFlag;
	}

	public Short getPresentFlowPortionPersent() {
		return this.presentFlowPortionPersent;
	}

	public void setPresentFlowPortionPersent(Short presentFlowPortionPersent) {
		this.presentFlowPortionPersent = presentFlowPortionPersent;
	}

	public Short getProjectedFlowPortionPersent() {
		return this.projectedFlowPortionPersent;
	}

	public void setProjectedFlowPortionPersent(Short projectedFlowPortionPersent) {
		this.projectedFlowPortionPersent = projectedFlowPortionPersent;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public char getFeedbackDeleteFlag() {
		return this.feedbackDeleteFlag;
	}

	public void setFeedbackDeleteFlag(char feedbackDeleteFlag) {
		this.feedbackDeleteFlag = feedbackDeleteFlag;
	}

	public Set getGeographicAreas() {
		return this.geographicAreas;
	}

	public void setGeographicAreas(Set geographicAreas) {
		this.geographicAreas = geographicAreas;
	}

}
