package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FundingAgencyRef generated by hbm2java
 */
public class FundingAgencyRef implements java.io.Serializable {

	// Fields    

	private String fundingAgencyId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set fundingSources = new HashSet(0);

	// Constructors

	/** default constructor */
	public FundingAgencyRef() {
	}

	/** minimal constructor */
	public FundingAgencyRef(String fundingAgencyId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.fundingAgencyId = fundingAgencyId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public FundingAgencyRef(String fundingAgencyId, String name,
			String lastUpdateUserid, Date lastUpdateTs, Set fundingSources) {
		this.fundingAgencyId = fundingAgencyId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.fundingSources = fundingSources;
	}

	// Property accessors
	public String getFundingAgencyId() {
		return this.fundingAgencyId;
	}

	public void setFundingAgencyId(String fundingAgencyId) {
		this.fundingAgencyId = fundingAgencyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFundingSources() {
		return this.fundingSources;
	}

	public void setFundingSources(Set fundingSources) {
		this.fundingSources = fundingSources;
	}

}
