package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * ImportCbrLoaninformation generated by hbm2java
 */
public class ImportCbrLoaninformation implements java.io.Serializable {

	// Fields    

	private ImportCbrLoaninformationId id;

	// Constructors

	/** default constructor */
	public ImportCbrLoaninformation() {
	}

	/** full constructor */
	public ImportCbrLoaninformation(ImportCbrLoaninformationId id) {
		this.id = id;
	}

	// Property accessors
	public ImportCbrLoaninformationId getId() {
		return this.id;
	}

	public void setId(ImportCbrLoaninformationId id) {
		this.id = id;
	}

}
