package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;

/**
 * ImportCbrProjectinformatnId generated by hbm2java
 */
public class ImportCbrProjectinformatnId implements java.io.Serializable {

	// Fields    

	private String projectkey;

	private Integer projectrecordnumber;

	private String loankey;

	private String cwnsnumber;

	private String description;

	private String facilityname;

	private String category1;

	private String category2;

	private String category3;

	private String category4;

	private String category5;

	private String category6;

	private String category7;

	private BigDecimal amount1;

	private BigDecimal amount2;

	private BigDecimal amount3;

	private BigDecimal amount4;

	private BigDecimal amount5;

	private BigDecimal amount6;

	private BigDecimal amount7;

	private String npdespermitnumber;

	private String nonpdespermit;

	private String permittype;

	private String permitnumber;

	// Constructors

	/** default constructor */
	public ImportCbrProjectinformatnId() {
	}

	/** full constructor */
	public ImportCbrProjectinformatnId(String projectkey,
			Integer projectrecordnumber, String loankey, String cwnsnumber,
			String description, String facilityname, String category1,
			String category2, String category3, String category4,
			String category5, String category6, String category7,
			BigDecimal amount1, BigDecimal amount2, BigDecimal amount3,
			BigDecimal amount4, BigDecimal amount5, BigDecimal amount6,
			BigDecimal amount7, String npdespermitnumber, String nonpdespermit,
			String permittype, String permitnumber) {
		this.projectkey = projectkey;
		this.projectrecordnumber = projectrecordnumber;
		this.loankey = loankey;
		this.cwnsnumber = cwnsnumber;
		this.description = description;
		this.facilityname = facilityname;
		this.category1 = category1;
		this.category2 = category2;
		this.category3 = category3;
		this.category4 = category4;
		this.category5 = category5;
		this.category6 = category6;
		this.category7 = category7;
		this.amount1 = amount1;
		this.amount2 = amount2;
		this.amount3 = amount3;
		this.amount4 = amount4;
		this.amount5 = amount5;
		this.amount6 = amount6;
		this.amount7 = amount7;
		this.npdespermitnumber = npdespermitnumber;
		this.nonpdespermit = nonpdespermit;
		this.permittype = permittype;
		this.permitnumber = permitnumber;
	}

	// Property accessors
	public String getProjectkey() {
		return this.projectkey;
	}

	public void setProjectkey(String projectkey) {
		this.projectkey = projectkey;
	}

	public Integer getProjectrecordnumber() {
		return this.projectrecordnumber;
	}

	public void setProjectrecordnumber(Integer projectrecordnumber) {
		this.projectrecordnumber = projectrecordnumber;
	}

	public String getLoankey() {
		return this.loankey;
	}

	public void setLoankey(String loankey) {
		this.loankey = loankey;
	}

	public String getCwnsnumber() {
		return this.cwnsnumber;
	}

	public void setCwnsnumber(String cwnsnumber) {
		this.cwnsnumber = cwnsnumber;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFacilityname() {
		return this.facilityname;
	}

	public void setFacilityname(String facilityname) {
		this.facilityname = facilityname;
	}

	public String getCategory1() {
		return this.category1;
	}

	public void setCategory1(String category1) {
		this.category1 = category1;
	}

	public String getCategory2() {
		return this.category2;
	}

	public void setCategory2(String category2) {
		this.category2 = category2;
	}

	public String getCategory3() {
		return this.category3;
	}

	public void setCategory3(String category3) {
		this.category3 = category3;
	}

	public String getCategory4() {
		return this.category4;
	}

	public void setCategory4(String category4) {
		this.category4 = category4;
	}

	public String getCategory5() {
		return this.category5;
	}

	public void setCategory5(String category5) {
		this.category5 = category5;
	}

	public String getCategory6() {
		return this.category6;
	}

	public void setCategory6(String category6) {
		this.category6 = category6;
	}

	public String getCategory7() {
		return this.category7;
	}

	public void setCategory7(String category7) {
		this.category7 = category7;
	}

	public BigDecimal getAmount1() {
		return this.amount1;
	}

	public void setAmount1(BigDecimal amount1) {
		this.amount1 = amount1;
	}

	public BigDecimal getAmount2() {
		return this.amount2;
	}

	public void setAmount2(BigDecimal amount2) {
		this.amount2 = amount2;
	}

	public BigDecimal getAmount3() {
		return this.amount3;
	}

	public void setAmount3(BigDecimal amount3) {
		this.amount3 = amount3;
	}

	public BigDecimal getAmount4() {
		return this.amount4;
	}

	public void setAmount4(BigDecimal amount4) {
		this.amount4 = amount4;
	}

	public BigDecimal getAmount5() {
		return this.amount5;
	}

	public void setAmount5(BigDecimal amount5) {
		this.amount5 = amount5;
	}

	public BigDecimal getAmount6() {
		return this.amount6;
	}

	public void setAmount6(BigDecimal amount6) {
		this.amount6 = amount6;
	}

	public BigDecimal getAmount7() {
		return this.amount7;
	}

	public void setAmount7(BigDecimal amount7) {
		this.amount7 = amount7;
	}

	public String getNpdespermitnumber() {
		return this.npdespermitnumber;
	}

	public void setNpdespermitnumber(String npdespermitnumber) {
		this.npdespermitnumber = npdespermitnumber;
	}

	public String getNonpdespermit() {
		return this.nonpdespermit;
	}

	public void setNonpdespermit(String nonpdespermit) {
		this.nonpdespermit = nonpdespermit;
	}

	public String getPermittype() {
		return this.permittype;
	}

	public void setPermittype(String permittype) {
		this.permittype = permittype;
	}

	public String getPermitnumber() {
		return this.permitnumber;
	}

	public void setPermitnumber(String permitnumber) {
		this.permitnumber = permitnumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImportCbrProjectinformatnId))
			return false;
		ImportCbrProjectinformatnId castOther = (ImportCbrProjectinformatnId) other;

		return ((this.getProjectkey() == castOther.getProjectkey()) || (this
				.getProjectkey() != null
				&& castOther.getProjectkey() != null && this.getProjectkey()
				.equals(castOther.getProjectkey())))
				&& ((this.getProjectrecordnumber() == castOther
						.getProjectrecordnumber()) || (this
						.getProjectrecordnumber() != null
						&& castOther.getProjectrecordnumber() != null && this
						.getProjectrecordnumber().equals(
								castOther.getProjectrecordnumber())))
				&& ((this.getLoankey() == castOther.getLoankey()) || (this
						.getLoankey() != null
						&& castOther.getLoankey() != null && this.getLoankey()
						.equals(castOther.getLoankey())))
				&& ((this.getCwnsnumber() == castOther.getCwnsnumber()) || (this
						.getCwnsnumber() != null
						&& castOther.getCwnsnumber() != null && this
						.getCwnsnumber().equals(castOther.getCwnsnumber())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getFacilityname() == castOther.getFacilityname()) || (this
						.getFacilityname() != null
						&& castOther.getFacilityname() != null && this
						.getFacilityname().equals(castOther.getFacilityname())))
				&& ((this.getCategory1() == castOther.getCategory1()) || (this
						.getCategory1() != null
						&& castOther.getCategory1() != null && this
						.getCategory1().equals(castOther.getCategory1())))
				&& ((this.getCategory2() == castOther.getCategory2()) || (this
						.getCategory2() != null
						&& castOther.getCategory2() != null && this
						.getCategory2().equals(castOther.getCategory2())))
				&& ((this.getCategory3() == castOther.getCategory3()) || (this
						.getCategory3() != null
						&& castOther.getCategory3() != null && this
						.getCategory3().equals(castOther.getCategory3())))
				&& ((this.getCategory4() == castOther.getCategory4()) || (this
						.getCategory4() != null
						&& castOther.getCategory4() != null && this
						.getCategory4().equals(castOther.getCategory4())))
				&& ((this.getCategory5() == castOther.getCategory5()) || (this
						.getCategory5() != null
						&& castOther.getCategory5() != null && this
						.getCategory5().equals(castOther.getCategory5())))
				&& ((this.getCategory6() == castOther.getCategory6()) || (this
						.getCategory6() != null
						&& castOther.getCategory6() != null && this
						.getCategory6().equals(castOther.getCategory6())))
				&& ((this.getCategory7() == castOther.getCategory7()) || (this
						.getCategory7() != null
						&& castOther.getCategory7() != null && this
						.getCategory7().equals(castOther.getCategory7())))
				&& ((this.getAmount1() == castOther.getAmount1()) || (this
						.getAmount1() != null
						&& castOther.getAmount1() != null && this.getAmount1()
						.equals(castOther.getAmount1())))
				&& ((this.getAmount2() == castOther.getAmount2()) || (this
						.getAmount2() != null
						&& castOther.getAmount2() != null && this.getAmount2()
						.equals(castOther.getAmount2())))
				&& ((this.getAmount3() == castOther.getAmount3()) || (this
						.getAmount3() != null
						&& castOther.getAmount3() != null && this.getAmount3()
						.equals(castOther.getAmount3())))
				&& ((this.getAmount4() == castOther.getAmount4()) || (this
						.getAmount4() != null
						&& castOther.getAmount4() != null && this.getAmount4()
						.equals(castOther.getAmount4())))
				&& ((this.getAmount5() == castOther.getAmount5()) || (this
						.getAmount5() != null
						&& castOther.getAmount5() != null && this.getAmount5()
						.equals(castOther.getAmount5())))
				&& ((this.getAmount6() == castOther.getAmount6()) || (this
						.getAmount6() != null
						&& castOther.getAmount6() != null && this.getAmount6()
						.equals(castOther.getAmount6())))
				&& ((this.getAmount7() == castOther.getAmount7()) || (this
						.getAmount7() != null
						&& castOther.getAmount7() != null && this.getAmount7()
						.equals(castOther.getAmount7())))
				&& ((this.getNpdespermitnumber() == castOther
						.getNpdespermitnumber()) || (this
						.getNpdespermitnumber() != null
						&& castOther.getNpdespermitnumber() != null && this
						.getNpdespermitnumber().equals(
								castOther.getNpdespermitnumber())))
				&& ((this.getNonpdespermit() == castOther.getNonpdespermit()) || (this
						.getNonpdespermit() != null
						&& castOther.getNonpdespermit() != null && this
						.getNonpdespermit()
						.equals(castOther.getNonpdespermit())))
				&& ((this.getPermittype() == castOther.getPermittype()) || (this
						.getPermittype() != null
						&& castOther.getPermittype() != null && this
						.getPermittype().equals(castOther.getPermittype())))
				&& ((this.getPermitnumber() == castOther.getPermitnumber()) || (this
						.getPermitnumber() != null
						&& castOther.getPermitnumber() != null && this
						.getPermitnumber().equals(castOther.getPermitnumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProjectkey() == null ? 0 : this.getProjectkey()
						.hashCode());
		result = 37
				* result
				+ (getProjectrecordnumber() == null ? 0 : this
						.getProjectrecordnumber().hashCode());
		result = 37 * result
				+ (getLoankey() == null ? 0 : this.getLoankey().hashCode());
		result = 37
				* result
				+ (getCwnsnumber() == null ? 0 : this.getCwnsnumber()
						.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37
				* result
				+ (getFacilityname() == null ? 0 : this.getFacilityname()
						.hashCode());
		result = 37 * result
				+ (getCategory1() == null ? 0 : this.getCategory1().hashCode());
		result = 37 * result
				+ (getCategory2() == null ? 0 : this.getCategory2().hashCode());
		result = 37 * result
				+ (getCategory3() == null ? 0 : this.getCategory3().hashCode());
		result = 37 * result
				+ (getCategory4() == null ? 0 : this.getCategory4().hashCode());
		result = 37 * result
				+ (getCategory5() == null ? 0 : this.getCategory5().hashCode());
		result = 37 * result
				+ (getCategory6() == null ? 0 : this.getCategory6().hashCode());
		result = 37 * result
				+ (getCategory7() == null ? 0 : this.getCategory7().hashCode());
		result = 37 * result
				+ (getAmount1() == null ? 0 : this.getAmount1().hashCode());
		result = 37 * result
				+ (getAmount2() == null ? 0 : this.getAmount2().hashCode());
		result = 37 * result
				+ (getAmount3() == null ? 0 : this.getAmount3().hashCode());
		result = 37 * result
				+ (getAmount4() == null ? 0 : this.getAmount4().hashCode());
		result = 37 * result
				+ (getAmount5() == null ? 0 : this.getAmount5().hashCode());
		result = 37 * result
				+ (getAmount6() == null ? 0 : this.getAmount6().hashCode());
		result = 37 * result
				+ (getAmount7() == null ? 0 : this.getAmount7().hashCode());
		result = 37
				* result
				+ (getNpdespermitnumber() == null ? 0 : this
						.getNpdespermitnumber().hashCode());
		result = 37
				* result
				+ (getNonpdespermit() == null ? 0 : this.getNonpdespermit()
						.hashCode());
		result = 37
				* result
				+ (getPermittype() == null ? 0 : this.getPermittype()
						.hashCode());
		result = 37
				* result
				+ (getPermitnumber() == null ? 0 : this.getPermitnumber()
						.hashCode());
		return result;
	}

}
