package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoanTypeRef generated by hbm2java
 */
public class LoanTypeRef implements java.io.Serializable {

	// Fields    

	private String loanTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set cbrLoanInformations = new HashSet(0);

	private Set fundingSources = new HashSet(0);

	// Constructors

	/** default constructor */
	public LoanTypeRef() {
	}

	/** minimal constructor */
	public LoanTypeRef(String loanTypeId, String name, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.loanTypeId = loanTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public LoanTypeRef(String loanTypeId, String name, String lastUpdateUserid,
			Date lastUpdateTs, Set cbrLoanInformations, Set fundingSources) {
		this.loanTypeId = loanTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.cbrLoanInformations = cbrLoanInformations;
		this.fundingSources = fundingSources;
	}

	// Property accessors
	public String getLoanTypeId() {
		return this.loanTypeId;
	}

	public void setLoanTypeId(String loanTypeId) {
		this.loanTypeId = loanTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCbrLoanInformations() {
		return this.cbrLoanInformations;
	}

	public void setCbrLoanInformations(Set cbrLoanInformations) {
		this.cbrLoanInformations = cbrLoanInformations;
	}

	public Set getFundingSources() {
		return this.fundingSources;
	}

	public void setFundingSources(Set fundingSources) {
		this.fundingSources = fundingSources;
	}

}
