package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LocationDescriptionRef generated by hbm2java
 */
public class LocationDescriptionRef implements java.io.Serializable {

	// Fields    

	private String locationDescriptionId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set absoluteLocationPoints = new HashSet(0);

	private Set efPermits = new HashSet(0);

	// Constructors

	/** default constructor */
	public LocationDescriptionRef() {
	}

	/** minimal constructor */
	public LocationDescriptionRef(String locationDescriptionId, String name,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.locationDescriptionId = locationDescriptionId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public LocationDescriptionRef(String locationDescriptionId, String name,
			String lastUpdateUserid, Date lastUpdateTs,
			Set absoluteLocationPoints, Set efPermits) {
		this.locationDescriptionId = locationDescriptionId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.absoluteLocationPoints = absoluteLocationPoints;
		this.efPermits = efPermits;
	}

	// Property accessors
	public String getLocationDescriptionId() {
		return this.locationDescriptionId;
	}

	public void setLocationDescriptionId(String locationDescriptionId) {
		this.locationDescriptionId = locationDescriptionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getAbsoluteLocationPoints() {
		return this.absoluteLocationPoints;
	}

	public void setAbsoluteLocationPoints(Set absoluteLocationPoints) {
		this.absoluteLocationPoints = absoluteLocationPoints;
	}

	public Set getEfPermits() {
		return this.efPermits;
	}

	public void setEfPermits(Set efPermits) {
		this.efPermits = efPermits;
	}

}
