package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LocationRef generated by hbm2java
 */
public class LocationRef implements java.io.Serializable {

	// Fields    

	private String locationId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set roleRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public LocationRef() {
	}

	/** minimal constructor */
	public LocationRef(String locationId, String name, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public LocationRef(String locationId, String name, String lastUpdateUserid,
			Date lastUpdateTs, Set roleRefs) {
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.roleRefs = roleRefs;
	}

	// Property accessors
	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getRoleRefs() {
		return this.roleRefs;
	}

	public void setRoleRefs(Set roleRefs) {
		this.roleRefs = roleRefs;
	}

}
