package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LocationTypeRef generated by hbm2java
 */
public class LocationTypeRef implements java.io.Serializable {

	// Fields    

	private String locationTypeId;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set accessLevelAppliesToRefs = new HashSet(0);

	private Set accessLevelAssignedByRefs = new HashSet(0);

	private Set roleRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public LocationTypeRef() {
	}

	/** minimal constructor */
	public LocationTypeRef(String locationTypeId, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.locationTypeId = locationTypeId;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public LocationTypeRef(String locationTypeId, String lastUpdateUserid,
			Date lastUpdateTs, Set accessLevelAppliesToRefs,
			Set accessLevelAssignedByRefs, Set roleRefs) {
		this.locationTypeId = locationTypeId;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.accessLevelAppliesToRefs = accessLevelAppliesToRefs;
		this.accessLevelAssignedByRefs = accessLevelAssignedByRefs;
		this.roleRefs = roleRefs;
	}

	// Property accessors
	public String getLocationTypeId() {
		return this.locationTypeId;
	}

	public void setLocationTypeId(String locationTypeId) {
		this.locationTypeId = locationTypeId;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getAccessLevelAppliesToRefs() {
		return this.accessLevelAppliesToRefs;
	}

	public void setAccessLevelAppliesToRefs(Set accessLevelAppliesToRefs) {
		this.accessLevelAppliesToRefs = accessLevelAppliesToRefs;
	}

	public Set getAccessLevelAssignedByRefs() {
		return this.accessLevelAssignedByRefs;
	}

	public void setAccessLevelAssignedByRefs(Set accessLevelAssignedByRefs) {
		this.accessLevelAssignedByRefs = accessLevelAssignedByRefs;
	}

	public Set getRoleRefs() {
		return this.roleRefs;
	}

	public void setRoleRefs(Set roleRefs) {
		this.roleRefs = roleRefs;
	}

}
