package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NeedTypeRef generated by hbm2java
 */
public class NeedTypeRef implements java.io.Serializable {

	// Fields    

	private String needTypeId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set costs = new HashSet(0);

	// Constructors

	/** default constructor */
	public NeedTypeRef() {
	}

	/** minimal constructor */
	public NeedTypeRef(String needTypeId, String name, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.needTypeId = needTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public NeedTypeRef(String needTypeId, String name, String lastUpdateUserid,
			Date lastUpdateTs, Set costs) {
		this.needTypeId = needTypeId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.costs = costs;
	}

	// Property accessors
	public String getNeedTypeId() {
		return this.needTypeId;
	}

	public void setNeedTypeId(String needTypeId) {
		this.needTypeId = needTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getCosts() {
		return this.costs;
	}

	public void setCosts(Set costs) {
		this.costs = costs;
	}

}
