package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OperAndMaintCategoryRef generated by hbm2java
 */
public class OperAndMaintCategoryRef implements java.io.Serializable {

	// Fields    

	private long operAndMaintCategoryId;

	private String name;

	private String description;

	private byte sortSequence;

	private Date lastUpdateTs;

	private String lastUpdateUserid;

	private Set operationAndMaintenanceCosts = new HashSet(0);

	// Constructors

	/** default constructor */
	public OperAndMaintCategoryRef() {
	}

	/** minimal constructor */
	public OperAndMaintCategoryRef(long operAndMaintCategoryId, String name,
			byte sortSequence, Date lastUpdateTs, String lastUpdateUserid) {
		this.operAndMaintCategoryId = operAndMaintCategoryId;
		this.name = name;
		this.sortSequence = sortSequence;
		this.lastUpdateTs = lastUpdateTs;
		this.lastUpdateUserid = lastUpdateUserid;
	}

	/** full constructor */
	public OperAndMaintCategoryRef(long operAndMaintCategoryId, String name,
			String description, byte sortSequence, Date lastUpdateTs,
			String lastUpdateUserid, Set operationAndMaintenanceCosts) {
		this.operAndMaintCategoryId = operAndMaintCategoryId;
		this.name = name;
		this.description = description;
		this.sortSequence = sortSequence;
		this.lastUpdateTs = lastUpdateTs;
		this.lastUpdateUserid = lastUpdateUserid;
		this.operationAndMaintenanceCosts = operationAndMaintenanceCosts;
	}

	// Property accessors
	public long getOperAndMaintCategoryId() {
		return this.operAndMaintCategoryId;
	}

	public void setOperAndMaintCategoryId(long operAndMaintCategoryId) {
		this.operAndMaintCategoryId = operAndMaintCategoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte getSortSequence() {
		return this.sortSequence;
	}

	public void setSortSequence(byte sortSequence) {
		this.sortSequence = sortSequence;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Set getOperationAndMaintenanceCosts() {
		return this.operationAndMaintenanceCosts;
	}

	public void setOperationAndMaintenanceCosts(Set operationAndMaintenanceCosts) {
		this.operationAndMaintenanceCosts = operationAndMaintenanceCosts;
	}

}
