package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsEffluentLimitQty generated by hbm2java
 */
public class PcsEffluentLimitQty implements java.io.Serializable {

	// Fields    

	private PcsEffluentLimitQtyId id;

	private PcsEffluentLimit pcsEffluentLimit;

	private String qtyMaxLimit;

	private String qtyAvgLimit;

	private String qtyUnitCode;

	private String qtyAvgLimStatBase;

	private String qtyMaxLimStatBase;

	// Constructors

	/** default constructor */
	public PcsEffluentLimitQty() {
	}

	/** minimal constructor */
	public PcsEffluentLimitQty(PcsEffluentLimitQtyId id,
			PcsEffluentLimit pcsEffluentLimit) {
		this.id = id;
		this.pcsEffluentLimit = pcsEffluentLimit;
	}

	/** full constructor */
	public PcsEffluentLimitQty(PcsEffluentLimitQtyId id,
			PcsEffluentLimit pcsEffluentLimit, String qtyMaxLimit,
			String qtyAvgLimit, String qtyUnitCode, String qtyAvgLimStatBase,
			String qtyMaxLimStatBase) {
		this.id = id;
		this.pcsEffluentLimit = pcsEffluentLimit;
		this.qtyMaxLimit = qtyMaxLimit;
		this.qtyAvgLimit = qtyAvgLimit;
		this.qtyUnitCode = qtyUnitCode;
		this.qtyAvgLimStatBase = qtyAvgLimStatBase;
		this.qtyMaxLimStatBase = qtyMaxLimStatBase;
	}

	// Property accessors
	public PcsEffluentLimitQtyId getId() {
		return this.id;
	}

	public void setId(PcsEffluentLimitQtyId id) {
		this.id = id;
	}

	public PcsEffluentLimit getPcsEffluentLimit() {
		return this.pcsEffluentLimit;
	}

	public void setPcsEffluentLimit(PcsEffluentLimit pcsEffluentLimit) {
		this.pcsEffluentLimit = pcsEffluentLimit;
	}

	public String getQtyMaxLimit() {
		return this.qtyMaxLimit;
	}

	public void setQtyMaxLimit(String qtyMaxLimit) {
		this.qtyMaxLimit = qtyMaxLimit;
	}

	public String getQtyAvgLimit() {
		return this.qtyAvgLimit;
	}

	public void setQtyAvgLimit(String qtyAvgLimit) {
		this.qtyAvgLimit = qtyAvgLimit;
	}

	public String getQtyUnitCode() {
		return this.qtyUnitCode;
	}

	public void setQtyUnitCode(String qtyUnitCode) {
		this.qtyUnitCode = qtyUnitCode;
	}

	public String getQtyAvgLimStatBase() {
		return this.qtyAvgLimStatBase;
	}

	public void setQtyAvgLimStatBase(String qtyAvgLimStatBase) {
		this.qtyAvgLimStatBase = qtyAvgLimStatBase;
	}

	public String getQtyMaxLimStatBase() {
		return this.qtyMaxLimStatBase;
	}

	public void setQtyMaxLimStatBase(String qtyMaxLimStatBase) {
		this.qtyMaxLimStatBase = qtyMaxLimStatBase;
	}

}
