package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsPipeSchedId generated by hbm2java
 */
public class PcsPipeSchedId implements java.io.Serializable {

	// Fields    

	private String npdes;

	private String dischargeNum;

	private String reportDesig;

	private char pipeSetQualifier;

	// Constructors

	/** default constructor */
	public PcsPipeSchedId() {
	}

	/** full constructor */
	public PcsPipeSchedId(String npdes, String dischargeNum,
			String reportDesig, char pipeSetQualifier) {
		this.npdes = npdes;
		this.dischargeNum = dischargeNum;
		this.reportDesig = reportDesig;
		this.pipeSetQualifier = pipeSetQualifier;
	}

	// Property accessors
	public String getNpdes() {
		return this.npdes;
	}

	public void setNpdes(String npdes) {
		this.npdes = npdes;
	}

	public String getDischargeNum() {
		return this.dischargeNum;
	}

	public void setDischargeNum(String dischargeNum) {
		this.dischargeNum = dischargeNum;
	}

	public String getReportDesig() {
		return this.reportDesig;
	}

	public void setReportDesig(String reportDesig) {
		this.reportDesig = reportDesig;
	}

	public char getPipeSetQualifier() {
		return this.pipeSetQualifier;
	}

	public void setPipeSetQualifier(char pipeSetQualifier) {
		this.pipeSetQualifier = pipeSetQualifier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PcsPipeSchedId))
			return false;
		PcsPipeSchedId castOther = (PcsPipeSchedId) other;

		return ((this.getNpdes() == castOther.getNpdes()) || (this.getNpdes() != null
				&& castOther.getNpdes() != null && this.getNpdes().equals(
				castOther.getNpdes())))
				&& ((this.getDischargeNum() == castOther.getDischargeNum()) || (this
						.getDischargeNum() != null
						&& castOther.getDischargeNum() != null && this
						.getDischargeNum().equals(castOther.getDischargeNum())))
				&& ((this.getReportDesig() == castOther.getReportDesig()) || (this
						.getReportDesig() != null
						&& castOther.getReportDesig() != null && this
						.getReportDesig().equals(castOther.getReportDesig())))
				&& (this.getPipeSetQualifier() == castOther
						.getPipeSetQualifier());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNpdes() == null ? 0 : this.getNpdes().hashCode());
		result = 37
				* result
				+ (getDischargeNum() == null ? 0 : this.getDischargeNum()
						.hashCode());
		result = 37
				* result
				+ (getReportDesig() == null ? 0 : this.getReportDesig()
						.hashCode());
		result = 37 * result + this.getPipeSetQualifier();
		return result;
	}

}
