package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsPermitFacilityErrorsId generated by hbm2java
 */
public class PcsPermitFacilityErrorsId implements java.io.Serializable {

	// Fields    

	private String npdes;

	private String sqlErrm;

	// Constructors

	/** default constructor */
	public PcsPermitFacilityErrorsId() {
	}

	/** full constructor */
	public PcsPermitFacilityErrorsId(String npdes, String sqlErrm) {
		this.npdes = npdes;
		this.sqlErrm = sqlErrm;
	}

	// Property accessors
	public String getNpdes() {
		return this.npdes;
	}

	public void setNpdes(String npdes) {
		this.npdes = npdes;
	}

	public String getSqlErrm() {
		return this.sqlErrm;
	}

	public void setSqlErrm(String sqlErrm) {
		this.sqlErrm = sqlErrm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PcsPermitFacilityErrorsId))
			return false;
		PcsPermitFacilityErrorsId castOther = (PcsPermitFacilityErrorsId) other;

		return ((this.getNpdes() == castOther.getNpdes()) || (this.getNpdes() != null
				&& castOther.getNpdes() != null && this.getNpdes().equals(
				castOther.getNpdes())))
				&& ((this.getSqlErrm() == castOther.getSqlErrm()) || (this
						.getSqlErrm() != null
						&& castOther.getSqlErrm() != null && this.getSqlErrm()
						.equals(castOther.getSqlErrm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNpdes() == null ? 0 : this.getNpdes().hashCode());
		result = 37 * result
				+ (getSqlErrm() == null ? 0 : this.getSqlErrm().hashCode());
		return result;
	}

}
