package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

/**
 * PcsPermitFacilityErrors generated by hbm2java
 */
public class PcsPermitFacilityErrors implements java.io.Serializable {

	// Fields    

	private PcsPermitFacilityErrorsId id;

	// Constructors

	/** default constructor */
	public PcsPermitFacilityErrors() {
	}

	/** full constructor */
	public PcsPermitFacilityErrors(PcsPermitFacilityErrorsId id) {
		this.id = id;
	}

	// Property accessors
	public PcsPermitFacilityErrorsId getId() {
		return this.id;
	}

	public void setId(PcsPermitFacilityErrorsId id) {
		this.id = id;
	}

}
