package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PcsPermitFacility generated by hbm2java
 */
public class PcsPermitFacility implements java.io.Serializable {

	// Fields    

	private String npdes;

	private Long permitTypeId;

	private String name1;

	private String name2;

	private String majorDischargeIndicator;

	private String region;

	private String cityCode;

	private String cityName;

	private String countyCode;

	private String countyName;

	private String sicCode;

	private String locationName;

	private String locationStreet1;

	private String locationStreet2;

	private String locationCity;

	private String locationState;

	private String locationZipCode;

	private Long locationTelephoneNumber;

	private String mailingName;

	private String mailingStreet1;

	private String mailingStreet2;

	private String mailingCity;

	private String mailingState;

	private String mailingZipCode;

	private String inactiveCode;

	private Date permitExpiredDate;

	private Date permitIssuedDate;

	private Date draftPermPubNotifDate;

	private Date applReceivedDate;

	private Date inactiveDate;

	private String typeOfOwnership;

	private String cognOfficial;

	private String cognOfficialTeleNumber;

	private String industryClass;

	private Date originlPermitIssueDate;

	private String typeOfPermitIssued;

	private String riverBasin;

	private String receivingWaters;

	private String currYearManlQncrStat;

	private String currYearAutoQncrStat;

	private String prevYearManlQncrStat;

	private String prevYearAutoQncrStat;

	private String federalGrantInd;

	private String finalLimitsInd;

	private BigDecimal flowRate;

	private String pretreatmentCode;

	private String nmpFinanStatCode;

	private String nmpFinalSched;

	private String nmpQuarter;

	private String latitude;

	private String longitude;

	private String codeOfAccuracy;

	private String method;

	private String datum;

	private String scale;

	private String descript;

	private String usgsHydroBasinCode;

	private String streamSegment;

	private String mileageInd;

	private String recvngStreamClassCode;

	private Set pcsPipeScheds = new HashSet(0);

	// Constructors

	/** default constructor */
	public PcsPermitFacility() {
	}

	/** minimal constructor */
	public PcsPermitFacility(String npdes) {
		this.npdes = npdes;
	}

	/** full constructor */
	public PcsPermitFacility(String npdes, Long permitTypeId, String name1,
			String name2, String majorDischargeIndicator, String region,
			String cityCode, String cityName, String countyCode,
			String countyName, String sicCode, String locationName,
			String locationStreet1, String locationStreet2,
			String locationCity, String locationState, String locationZipCode,
			Long locationTelephoneNumber, String mailingName,
			String mailingStreet1, String mailingStreet2, String mailingCity,
			String mailingState, String mailingZipCode, String inactiveCode,
			Date permitExpiredDate, Date permitIssuedDate,
			Date draftPermPubNotifDate, Date applReceivedDate,
			Date inactiveDate, String typeOfOwnership, String cognOfficial,
			String cognOfficialTeleNumber, String industryClass,
			Date originlPermitIssueDate, String typeOfPermitIssued,
			String riverBasin, String receivingWaters,
			String currYearManlQncrStat, String currYearAutoQncrStat,
			String prevYearManlQncrStat, String prevYearAutoQncrStat,
			String federalGrantInd, String finalLimitsInd, BigDecimal flowRate,
			String pretreatmentCode, String nmpFinanStatCode,
			String nmpFinalSched, String nmpQuarter, String latitude,
			String longitude, String codeOfAccuracy, String method,
			String datum, String scale, String descript,
			String usgsHydroBasinCode, String streamSegment, String mileageInd,
			String recvngStreamClassCode, Set pcsPipeScheds) {
		this.npdes = npdes;
		this.permitTypeId = permitTypeId;
		this.name1 = name1;
		this.name2 = name2;
		this.majorDischargeIndicator = majorDischargeIndicator;
		this.region = region;
		this.cityCode = cityCode;
		this.cityName = cityName;
		this.countyCode = countyCode;
		this.countyName = countyName;
		this.sicCode = sicCode;
		this.locationName = locationName;
		this.locationStreet1 = locationStreet1;
		this.locationStreet2 = locationStreet2;
		this.locationCity = locationCity;
		this.locationState = locationState;
		this.locationZipCode = locationZipCode;
		this.locationTelephoneNumber = locationTelephoneNumber;
		this.mailingName = mailingName;
		this.mailingStreet1 = mailingStreet1;
		this.mailingStreet2 = mailingStreet2;
		this.mailingCity = mailingCity;
		this.mailingState = mailingState;
		this.mailingZipCode = mailingZipCode;
		this.inactiveCode = inactiveCode;
		this.permitExpiredDate = permitExpiredDate;
		this.permitIssuedDate = permitIssuedDate;
		this.draftPermPubNotifDate = draftPermPubNotifDate;
		this.applReceivedDate = applReceivedDate;
		this.inactiveDate = inactiveDate;
		this.typeOfOwnership = typeOfOwnership;
		this.cognOfficial = cognOfficial;
		this.cognOfficialTeleNumber = cognOfficialTeleNumber;
		this.industryClass = industryClass;
		this.originlPermitIssueDate = originlPermitIssueDate;
		this.typeOfPermitIssued = typeOfPermitIssued;
		this.riverBasin = riverBasin;
		this.receivingWaters = receivingWaters;
		this.currYearManlQncrStat = currYearManlQncrStat;
		this.currYearAutoQncrStat = currYearAutoQncrStat;
		this.prevYearManlQncrStat = prevYearManlQncrStat;
		this.prevYearAutoQncrStat = prevYearAutoQncrStat;
		this.federalGrantInd = federalGrantInd;
		this.finalLimitsInd = finalLimitsInd;
		this.flowRate = flowRate;
		this.pretreatmentCode = pretreatmentCode;
		this.nmpFinanStatCode = nmpFinanStatCode;
		this.nmpFinalSched = nmpFinalSched;
		this.nmpQuarter = nmpQuarter;
		this.latitude = latitude;
		this.longitude = longitude;
		this.codeOfAccuracy = codeOfAccuracy;
		this.method = method;
		this.datum = datum;
		this.scale = scale;
		this.descript = descript;
		this.usgsHydroBasinCode = usgsHydroBasinCode;
		this.streamSegment = streamSegment;
		this.mileageInd = mileageInd;
		this.recvngStreamClassCode = recvngStreamClassCode;
		this.pcsPipeScheds = pcsPipeScheds;
	}

	// Property accessors
	public String getNpdes() {
		return this.npdes;
	}

	public void setNpdes(String npdes) {
		this.npdes = npdes;
	}

	public Long getPermitTypeId() {
		return this.permitTypeId;
	}

	public void setPermitTypeId(Long permitTypeId) {
		this.permitTypeId = permitTypeId;
	}

	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	public String getMajorDischargeIndicator() {
		return this.majorDischargeIndicator;
	}

	public void setMajorDischargeIndicator(String majorDischargeIndicator) {
		this.majorDischargeIndicator = majorDischargeIndicator;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCountyCode() {
		return this.countyCode;
	}

	public void setCountyCode(String countyCode) {
		this.countyCode = countyCode;
	}

	public String getCountyName() {
		return this.countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	public String getSicCode() {
		return this.sicCode;
	}

	public void setSicCode(String sicCode) {
		this.sicCode = sicCode;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getLocationStreet1() {
		return this.locationStreet1;
	}

	public void setLocationStreet1(String locationStreet1) {
		this.locationStreet1 = locationStreet1;
	}

	public String getLocationStreet2() {
		return this.locationStreet2;
	}

	public void setLocationStreet2(String locationStreet2) {
		this.locationStreet2 = locationStreet2;
	}

	public String getLocationCity() {
		return this.locationCity;
	}

	public void setLocationCity(String locationCity) {
		this.locationCity = locationCity;
	}

	public String getLocationState() {
		return this.locationState;
	}

	public void setLocationState(String locationState) {
		this.locationState = locationState;
	}

	public String getLocationZipCode() {
		return this.locationZipCode;
	}

	public void setLocationZipCode(String locationZipCode) {
		this.locationZipCode = locationZipCode;
	}

	public Long getLocationTelephoneNumber() {
		return this.locationTelephoneNumber;
	}

	public void setLocationTelephoneNumber(Long locationTelephoneNumber) {
		this.locationTelephoneNumber = locationTelephoneNumber;
	}

	public String getMailingName() {
		return this.mailingName;
	}

	public void setMailingName(String mailingName) {
		this.mailingName = mailingName;
	}

	public String getMailingStreet1() {
		return this.mailingStreet1;
	}

	public void setMailingStreet1(String mailingStreet1) {
		this.mailingStreet1 = mailingStreet1;
	}

	public String getMailingStreet2() {
		return this.mailingStreet2;
	}

	public void setMailingStreet2(String mailingStreet2) {
		this.mailingStreet2 = mailingStreet2;
	}

	public String getMailingCity() {
		return this.mailingCity;
	}

	public void setMailingCity(String mailingCity) {
		this.mailingCity = mailingCity;
	}

	public String getMailingState() {
		return this.mailingState;
	}

	public void setMailingState(String mailingState) {
		this.mailingState = mailingState;
	}

	public String getMailingZipCode() {
		return this.mailingZipCode;
	}

	public void setMailingZipCode(String mailingZipCode) {
		this.mailingZipCode = mailingZipCode;
	}

	public String getInactiveCode() {
		return this.inactiveCode;
	}

	public void setInactiveCode(String inactiveCode) {
		this.inactiveCode = inactiveCode;
	}

	public Date getPermitExpiredDate() {
		return this.permitExpiredDate;
	}

	public void setPermitExpiredDate(Date permitExpiredDate) {
		this.permitExpiredDate = permitExpiredDate;
	}

	public Date getPermitIssuedDate() {
		return this.permitIssuedDate;
	}

	public void setPermitIssuedDate(Date permitIssuedDate) {
		this.permitIssuedDate = permitIssuedDate;
	}

	public Date getDraftPermPubNotifDate() {
		return this.draftPermPubNotifDate;
	}

	public void setDraftPermPubNotifDate(Date draftPermPubNotifDate) {
		this.draftPermPubNotifDate = draftPermPubNotifDate;
	}

	public Date getApplReceivedDate() {
		return this.applReceivedDate;
	}

	public void setApplReceivedDate(Date applReceivedDate) {
		this.applReceivedDate = applReceivedDate;
	}

	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public String getTypeOfOwnership() {
		return this.typeOfOwnership;
	}

	public void setTypeOfOwnership(String typeOfOwnership) {
		this.typeOfOwnership = typeOfOwnership;
	}

	public String getCognOfficial() {
		return this.cognOfficial;
	}

	public void setCognOfficial(String cognOfficial) {
		this.cognOfficial = cognOfficial;
	}

	public String getCognOfficialTeleNumber() {
		return this.cognOfficialTeleNumber;
	}

	public void setCognOfficialTeleNumber(String cognOfficialTeleNumber) {
		this.cognOfficialTeleNumber = cognOfficialTeleNumber;
	}

	public String getIndustryClass() {
		return this.industryClass;
	}

	public void setIndustryClass(String industryClass) {
		this.industryClass = industryClass;
	}

	public Date getOriginlPermitIssueDate() {
		return this.originlPermitIssueDate;
	}

	public void setOriginlPermitIssueDate(Date originlPermitIssueDate) {
		this.originlPermitIssueDate = originlPermitIssueDate;
	}

	public String getTypeOfPermitIssued() {
		return this.typeOfPermitIssued;
	}

	public void setTypeOfPermitIssued(String typeOfPermitIssued) {
		this.typeOfPermitIssued = typeOfPermitIssued;
	}

	public String getRiverBasin() {
		return this.riverBasin;
	}

	public void setRiverBasin(String riverBasin) {
		this.riverBasin = riverBasin;
	}

	public String getReceivingWaters() {
		return this.receivingWaters;
	}

	public void setReceivingWaters(String receivingWaters) {
		this.receivingWaters = receivingWaters;
	}

	public String getCurrYearManlQncrStat() {
		return this.currYearManlQncrStat;
	}

	public void setCurrYearManlQncrStat(String currYearManlQncrStat) {
		this.currYearManlQncrStat = currYearManlQncrStat;
	}

	public String getCurrYearAutoQncrStat() {
		return this.currYearAutoQncrStat;
	}

	public void setCurrYearAutoQncrStat(String currYearAutoQncrStat) {
		this.currYearAutoQncrStat = currYearAutoQncrStat;
	}

	public String getPrevYearManlQncrStat() {
		return this.prevYearManlQncrStat;
	}

	public void setPrevYearManlQncrStat(String prevYearManlQncrStat) {
		this.prevYearManlQncrStat = prevYearManlQncrStat;
	}

	public String getPrevYearAutoQncrStat() {
		return this.prevYearAutoQncrStat;
	}

	public void setPrevYearAutoQncrStat(String prevYearAutoQncrStat) {
		this.prevYearAutoQncrStat = prevYearAutoQncrStat;
	}

	public String getFederalGrantInd() {
		return this.federalGrantInd;
	}

	public void setFederalGrantInd(String federalGrantInd) {
		this.federalGrantInd = federalGrantInd;
	}

	public String getFinalLimitsInd() {
		return this.finalLimitsInd;
	}

	public void setFinalLimitsInd(String finalLimitsInd) {
		this.finalLimitsInd = finalLimitsInd;
	}

	public BigDecimal getFlowRate() {
		return this.flowRate;
	}

	public void setFlowRate(BigDecimal flowRate) {
		this.flowRate = flowRate;
	}

	public String getPretreatmentCode() {
		return this.pretreatmentCode;
	}

	public void setPretreatmentCode(String pretreatmentCode) {
		this.pretreatmentCode = pretreatmentCode;
	}

	public String getNmpFinanStatCode() {
		return this.nmpFinanStatCode;
	}

	public void setNmpFinanStatCode(String nmpFinanStatCode) {
		this.nmpFinanStatCode = nmpFinanStatCode;
	}

	public String getNmpFinalSched() {
		return this.nmpFinalSched;
	}

	public void setNmpFinalSched(String nmpFinalSched) {
		this.nmpFinalSched = nmpFinalSched;
	}

	public String getNmpQuarter() {
		return this.nmpQuarter;
	}

	public void setNmpQuarter(String nmpQuarter) {
		this.nmpQuarter = nmpQuarter;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getCodeOfAccuracy() {
		return this.codeOfAccuracy;
	}

	public void setCodeOfAccuracy(String codeOfAccuracy) {
		this.codeOfAccuracy = codeOfAccuracy;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getDatum() {
		return this.datum;
	}

	public void setDatum(String datum) {
		this.datum = datum;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public String getUsgsHydroBasinCode() {
		return this.usgsHydroBasinCode;
	}

	public void setUsgsHydroBasinCode(String usgsHydroBasinCode) {
		this.usgsHydroBasinCode = usgsHydroBasinCode;
	}

	public String getStreamSegment() {
		return this.streamSegment;
	}

	public void setStreamSegment(String streamSegment) {
		this.streamSegment = streamSegment;
	}

	public String getMileageInd() {
		return this.mileageInd;
	}

	public void setMileageInd(String mileageInd) {
		this.mileageInd = mileageInd;
	}

	public String getRecvngStreamClassCode() {
		return this.recvngStreamClassCode;
	}

	public void setRecvngStreamClassCode(String recvngStreamClassCode) {
		this.recvngStreamClassCode = recvngStreamClassCode;
	}

	public Set getPcsPipeScheds() {
		return this.pcsPipeScheds;
	}

	public void setPcsPipeScheds(Set pcsPipeScheds) {
		this.pcsPipeScheds = pcsPipeScheds;
	}

}
