package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PcsPipeSched generated by hbm2java
 */
public class PcsPipeSched implements java.io.Serializable {

	// Fields    

	private PcsPipeSchedId id;

	private PcsPermitFacility pcsPermitFacility;

	private String outfallTypeCode;

	private Date initLimitsStartDate;

	private Date initLimitsEndDate;

	private Date interimLimitsStartDate;

	private Date interimLimitsEndDate;

	private Date finalLimitsStartDate;

	private Date finalLimitsEndDate;

	private String pipeDesc;

	private Date initRptDate;

	private Short unitsInRptPeriod;

	private String reportingUnits;

	private String pipeInactiveCode;

	private Date pipeInactiveDate;

	private Date initEpaSubmissionDate;

	private Short unitsInEpaStateSubmPeriod;

	private String stateSubmissionUnits;

	private Set pcsEffluentLimits = new HashSet(0);

	// Constructors

	/** default constructor */
	public PcsPipeSched() {
	}

	/** minimal constructor */
	public PcsPipeSched(PcsPipeSchedId id, PcsPermitFacility pcsPermitFacility) {
		this.id = id;
		this.pcsPermitFacility = pcsPermitFacility;
	}

	/** full constructor */
	public PcsPipeSched(PcsPipeSchedId id, PcsPermitFacility pcsPermitFacility,
			String outfallTypeCode, Date initLimitsStartDate,
			Date initLimitsEndDate, Date interimLimitsStartDate,
			Date interimLimitsEndDate, Date finalLimitsStartDate,
			Date finalLimitsEndDate, String pipeDesc, Date initRptDate,
			Short unitsInRptPeriod, String reportingUnits,
			String pipeInactiveCode, Date pipeInactiveDate,
			Date initEpaSubmissionDate, Short unitsInEpaStateSubmPeriod,
			String stateSubmissionUnits, Set pcsEffluentLimits) {
		this.id = id;
		this.pcsPermitFacility = pcsPermitFacility;
		this.outfallTypeCode = outfallTypeCode;
		this.initLimitsStartDate = initLimitsStartDate;
		this.initLimitsEndDate = initLimitsEndDate;
		this.interimLimitsStartDate = interimLimitsStartDate;
		this.interimLimitsEndDate = interimLimitsEndDate;
		this.finalLimitsStartDate = finalLimitsStartDate;
		this.finalLimitsEndDate = finalLimitsEndDate;
		this.pipeDesc = pipeDesc;
		this.initRptDate = initRptDate;
		this.unitsInRptPeriod = unitsInRptPeriod;
		this.reportingUnits = reportingUnits;
		this.pipeInactiveCode = pipeInactiveCode;
		this.pipeInactiveDate = pipeInactiveDate;
		this.initEpaSubmissionDate = initEpaSubmissionDate;
		this.unitsInEpaStateSubmPeriod = unitsInEpaStateSubmPeriod;
		this.stateSubmissionUnits = stateSubmissionUnits;
		this.pcsEffluentLimits = pcsEffluentLimits;
	}

	// Property accessors
	public PcsPipeSchedId getId() {
		return this.id;
	}

	public void setId(PcsPipeSchedId id) {
		this.id = id;
	}

	public PcsPermitFacility getPcsPermitFacility() {
		return this.pcsPermitFacility;
	}

	public void setPcsPermitFacility(PcsPermitFacility pcsPermitFacility) {
		this.pcsPermitFacility = pcsPermitFacility;
	}

	public String getOutfallTypeCode() {
		return this.outfallTypeCode;
	}

	public void setOutfallTypeCode(String outfallTypeCode) {
		this.outfallTypeCode = outfallTypeCode;
	}

	public Date getInitLimitsStartDate() {
		return this.initLimitsStartDate;
	}

	public void setInitLimitsStartDate(Date initLimitsStartDate) {
		this.initLimitsStartDate = initLimitsStartDate;
	}

	public Date getInitLimitsEndDate() {
		return this.initLimitsEndDate;
	}

	public void setInitLimitsEndDate(Date initLimitsEndDate) {
		this.initLimitsEndDate = initLimitsEndDate;
	}

	public Date getInterimLimitsStartDate() {
		return this.interimLimitsStartDate;
	}

	public void setInterimLimitsStartDate(Date interimLimitsStartDate) {
		this.interimLimitsStartDate = interimLimitsStartDate;
	}

	public Date getInterimLimitsEndDate() {
		return this.interimLimitsEndDate;
	}

	public void setInterimLimitsEndDate(Date interimLimitsEndDate) {
		this.interimLimitsEndDate = interimLimitsEndDate;
	}

	public Date getFinalLimitsStartDate() {
		return this.finalLimitsStartDate;
	}

	public void setFinalLimitsStartDate(Date finalLimitsStartDate) {
		this.finalLimitsStartDate = finalLimitsStartDate;
	}

	public Date getFinalLimitsEndDate() {
		return this.finalLimitsEndDate;
	}

	public void setFinalLimitsEndDate(Date finalLimitsEndDate) {
		this.finalLimitsEndDate = finalLimitsEndDate;
	}

	public String getPipeDesc() {
		return this.pipeDesc;
	}

	public void setPipeDesc(String pipeDesc) {
		this.pipeDesc = pipeDesc;
	}

	public Date getInitRptDate() {
		return this.initRptDate;
	}

	public void setInitRptDate(Date initRptDate) {
		this.initRptDate = initRptDate;
	}

	public Short getUnitsInRptPeriod() {
		return this.unitsInRptPeriod;
	}

	public void setUnitsInRptPeriod(Short unitsInRptPeriod) {
		this.unitsInRptPeriod = unitsInRptPeriod;
	}

	public String getReportingUnits() {
		return this.reportingUnits;
	}

	public void setReportingUnits(String reportingUnits) {
		this.reportingUnits = reportingUnits;
	}

	public String getPipeInactiveCode() {
		return this.pipeInactiveCode;
	}

	public void setPipeInactiveCode(String pipeInactiveCode) {
		this.pipeInactiveCode = pipeInactiveCode;
	}

	public Date getPipeInactiveDate() {
		return this.pipeInactiveDate;
	}

	public void setPipeInactiveDate(Date pipeInactiveDate) {
		this.pipeInactiveDate = pipeInactiveDate;
	}

	public Date getInitEpaSubmissionDate() {
		return this.initEpaSubmissionDate;
	}

	public void setInitEpaSubmissionDate(Date initEpaSubmissionDate) {
		this.initEpaSubmissionDate = initEpaSubmissionDate;
	}

	public Short getUnitsInEpaStateSubmPeriod() {
		return this.unitsInEpaStateSubmPeriod;
	}

	public void setUnitsInEpaStateSubmPeriod(Short unitsInEpaStateSubmPeriod) {
		this.unitsInEpaStateSubmPeriod = unitsInEpaStateSubmPeriod;
	}

	public String getStateSubmissionUnits() {
		return this.stateSubmissionUnits;
	}

	public void setStateSubmissionUnits(String stateSubmissionUnits) {
		this.stateSubmissionUnits = stateSubmissionUnits;
	}

	public Set getPcsEffluentLimits() {
		return this.pcsEffluentLimits;
	}

	public void setPcsEffluentLimits(Set pcsEffluentLimits) {
		this.pcsEffluentLimits = pcsEffluentLimits;
	}

}
