package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PollutionCategoryGroupRef generated by hbm2java
 */
public class PollutionCategoryGroupRef implements java.io.Serializable {

	// Fields    

	private long pollutionCategoryGroupId;

	private String locationId;

	private String name;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set pollutionProblemRefs = new HashSet(0);

	// Constructors

	/** default constructor */
	public PollutionCategoryGroupRef() {
	}

	/** minimal constructor */
	public PollutionCategoryGroupRef(long pollutionCategoryGroupId,
			String locationId, String name, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.pollutionCategoryGroupId = pollutionCategoryGroupId;
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public PollutionCategoryGroupRef(long pollutionCategoryGroupId,
			String locationId, String name, String lastUpdateUserid,
			Date lastUpdateTs, Set pollutionProblemRefs) {
		this.pollutionCategoryGroupId = pollutionCategoryGroupId;
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.pollutionProblemRefs = pollutionProblemRefs;
	}

	// Property accessors
	public long getPollutionCategoryGroupId() {
		return this.pollutionCategoryGroupId;
	}

	public void setPollutionCategoryGroupId(long pollutionCategoryGroupId) {
		this.pollutionCategoryGroupId = pollutionCategoryGroupId;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getPollutionProblemRefs() {
		return this.pollutionProblemRefs;
	}

	public void setPollutionProblemRefs(Set pollutionProblemRefs) {
		this.pollutionProblemRefs = pollutionProblemRefs;
	}

}
