package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PollutionProblemRef generated by hbm2java
 */
public class PollutionProblemRef implements java.io.Serializable {

	// Fields    

	private long pollutionProblemId;

	private PollutionCategoryGroupRef pollutionCategoryGroupRef;

	private String locationId;

	private String name;

	private String description;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityPollutionProblems = new HashSet(0);

	// Constructors

	/** default constructor */
	public PollutionProblemRef() {
	}

	/** minimal constructor */
	public PollutionProblemRef(long pollutionProblemId,
			PollutionCategoryGroupRef pollutionCategoryGroupRef,
			String locationId, String name, String lastUpdateUserid,
			Date lastUpdateTs) {
		this.pollutionProblemId = pollutionProblemId;
		this.pollutionCategoryGroupRef = pollutionCategoryGroupRef;
		this.locationId = locationId;
		this.name = name;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public PollutionProblemRef(long pollutionProblemId,
			PollutionCategoryGroupRef pollutionCategoryGroupRef,
			String locationId, String name, String description,
			String lastUpdateUserid, Date lastUpdateTs,
			Set facilityPollutionProblems) {
		this.pollutionProblemId = pollutionProblemId;
		this.pollutionCategoryGroupRef = pollutionCategoryGroupRef;
		this.locationId = locationId;
		this.name = name;
		this.description = description;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityPollutionProblems = facilityPollutionProblems;
	}

	// Property accessors
	public long getPollutionProblemId() {
		return this.pollutionProblemId;
	}

	public void setPollutionProblemId(long pollutionProblemId) {
		this.pollutionProblemId = pollutionProblemId;
	}

	public PollutionCategoryGroupRef getPollutionCategoryGroupRef() {
		return this.pollutionCategoryGroupRef;
	}

	public void setPollutionCategoryGroupRef(
			PollutionCategoryGroupRef pollutionCategoryGroupRef) {
		this.pollutionCategoryGroupRef = pollutionCategoryGroupRef;
	}

	public String getLocationId() {
		return this.locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityPollutionProblems() {
		return this.facilityPollutionProblems;
	}

	public void setFacilityPollutionProblems(Set facilityPollutionProblems) {
		this.facilityPollutionProblems = facilityPollutionProblems;
	}

}
