package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * TreatmentPlantCcFormulaRef generated by hbm2java
 */
public class TreatmentPlantCcFormulaRef implements java.io.Serializable {

	// Fields    

	private TreatmentPlantCcFormulaRefId id;

	private BigDecimal coeffAValue;

	private BigDecimal coeffBValue;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	// Constructors

	/** default constructor */
	public TreatmentPlantCcFormulaRef() {
	}

	/** full constructor */
	public TreatmentPlantCcFormulaRef(TreatmentPlantCcFormulaRefId id,
			BigDecimal coeffAValue, BigDecimal coeffBValue,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.coeffAValue = coeffAValue;
		this.coeffBValue = coeffBValue;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	// Property accessors
	public TreatmentPlantCcFormulaRefId getId() {
		return this.id;
	}

	public void setId(TreatmentPlantCcFormulaRefId id) {
		this.id = id;
	}

	public BigDecimal getCoeffAValue() {
		return this.coeffAValue;
	}

	public void setCoeffAValue(BigDecimal coeffAValue) {
		this.coeffAValue = coeffAValue;
	}

	public BigDecimal getCoeffBValue() {
		return this.coeffBValue;
	}

	public void setCoeffBValue(BigDecimal coeffBValue) {
		this.coeffBValue = coeffBValue;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
