package gov.epa.owm.mtb.cwns.model;

// Generated Oct 31, 2007 10:35:21 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TreatmentTypeUnitprocessRef generated by hbm2java
 */
public class TreatmentTypeUnitprocessRef implements java.io.Serializable {

	// Fields    

	private TreatmentTypeUnitprocessRefId id;

	private TreatmentTypeRef treatmentTypeRef;

	private UnitProcessRef unitProcessRef;

	private String lastUpdateUserid;

	private Date lastUpdateTs;

	private Set facilityUnitProcesses = new HashSet(0);

	// Constructors

	/** default constructor */
	public TreatmentTypeUnitprocessRef() {
	}

	/** minimal constructor */
	public TreatmentTypeUnitprocessRef(TreatmentTypeUnitprocessRefId id,
			TreatmentTypeRef treatmentTypeRef, UnitProcessRef unitProcessRef,
			String lastUpdateUserid, Date lastUpdateTs) {
		this.id = id;
		this.treatmentTypeRef = treatmentTypeRef;
		this.unitProcessRef = unitProcessRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
	}

	/** full constructor */
	public TreatmentTypeUnitprocessRef(TreatmentTypeUnitprocessRefId id,
			TreatmentTypeRef treatmentTypeRef, UnitProcessRef unitProcessRef,
			String lastUpdateUserid, Date lastUpdateTs,
			Set facilityUnitProcesses) {
		this.id = id;
		this.treatmentTypeRef = treatmentTypeRef;
		this.unitProcessRef = unitProcessRef;
		this.lastUpdateUserid = lastUpdateUserid;
		this.lastUpdateTs = lastUpdateTs;
		this.facilityUnitProcesses = facilityUnitProcesses;
	}

	// Property accessors
	public TreatmentTypeUnitprocessRefId getId() {
		return this.id;
	}

	public void setId(TreatmentTypeUnitprocessRefId id) {
		this.id = id;
	}

	public TreatmentTypeRef getTreatmentTypeRef() {
		return this.treatmentTypeRef;
	}

	public void setTreatmentTypeRef(TreatmentTypeRef treatmentTypeRef) {
		this.treatmentTypeRef = treatmentTypeRef;
	}

	public UnitProcessRef getUnitProcessRef() {
		return this.unitProcessRef;
	}

	public void setUnitProcessRef(UnitProcessRef unitProcessRef) {
		this.unitProcessRef = unitProcessRef;
	}

	public String getLastUpdateUserid() {
		return this.lastUpdateUserid;
	}

	public void setLastUpdateUserid(String lastUpdateUserid) {
		this.lastUpdateUserid = lastUpdateUserid;
	}

	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	public Set getFacilityUnitProcesses() {
		return this.facilityUnitProcesses;
	}

	public void setFacilityUnitProcesses(Set facilityUnitProcesses) {
		this.facilityUnitProcesses = facilityUnitProcesses;
	}

}
