package gov.epa.owm.mtb.cwns.model;

// Generated Sep 17, 2007 10:44:47 AM by Hibernate Tools 3.2.0.beta8

/**
 * VFacilityId generated by hbm2java
 */
public class VFacilityId implements java.io.Serializable {

	// Fields    

	private long facilityId;

	private String cwnsNbr;

	private String facilityName;

	private String reviewStatusName;

	private String county;

	private String feedbackReviewStatusName;
	
	private String authority;

	// Constructors

	/** default constructor */
	public VFacilityId() {
	}

	/** minimal constructor */
	public VFacilityId(long facilityId, String facilityName) {
		this.facilityId = facilityId;
		this.facilityName = facilityName;
	}

	/** full constructor */
	public VFacilityId(long facilityId, String cwnsNbr, String facilityName,
			String reviewStatusName, String county,
			String feedbackReviewStatusName, String authority) {
		this.facilityId = facilityId;
		this.cwnsNbr = cwnsNbr;
		this.facilityName = facilityName;
		this.reviewStatusName = reviewStatusName;
		this.county = county;
		this.feedbackReviewStatusName = feedbackReviewStatusName;
		this.authority = authority;
	}

	// Property accessors
	public long getFacilityId() {
		return this.facilityId;
	}

	public void setFacilityId(long facilityId) {
		this.facilityId = facilityId;
	}

	public String getCwnsNbr() {
		return this.cwnsNbr;
	}

	public void setCwnsNbr(String cwnsNbr) {
		this.cwnsNbr = cwnsNbr;
	}

	public String getFacilityName() {
		return this.facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getReviewStatusName() {
		return this.reviewStatusName;
	}

	public void setReviewStatusName(String reviewStatusName) {
		this.reviewStatusName = reviewStatusName;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getFeedbackReviewStatusName() {
		return this.feedbackReviewStatusName;
	}

	public void setFeedbackReviewStatusName(String feedbackReviewStatusName) {
		this.feedbackReviewStatusName = feedbackReviewStatusName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VFacilityId))
			return false;
		VFacilityId castOther = (VFacilityId) other;

		return (this.getFacilityId() == castOther.getFacilityId())
				&& ((this.getCwnsNbr() == castOther.getCwnsNbr()) || (this
						.getCwnsNbr() != null
						&& castOther.getCwnsNbr() != null && this.getCwnsNbr()
						.equals(castOther.getCwnsNbr())))
				&& ((this.getFacilityName() == castOther.getFacilityName()) || (this
						.getFacilityName() != null
						&& castOther.getFacilityName() != null && this
						.getFacilityName().equals(castOther.getFacilityName())))
				&& ((this.getReviewStatusName() == castOther
						.getReviewStatusName()) || (this.getReviewStatusName() != null
						&& castOther.getReviewStatusName() != null && this
						.getReviewStatusName().equals(
								castOther.getReviewStatusName())))
				&& ((this.getCounty() == castOther.getCounty()) || (this
						.getCounty() != null
						&& castOther.getCounty() != null && this.getCounty()
						.equals(castOther.getCounty())))
				&& ((this.getFeedbackReviewStatusName() == castOther
						.getFeedbackReviewStatusName()) || (this
						.getFeedbackReviewStatusName() != null
						&& castOther.getFeedbackReviewStatusName() != null && this
						.getFeedbackReviewStatusName().equals(
								castOther.getFeedbackReviewStatusName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getFacilityId();
		result = 37 * result
				+ (getCwnsNbr() == null ? 0 : this.getCwnsNbr().hashCode());
		result = 37
				* result
				+ (getFacilityName() == null ? 0 : this.getFacilityName()
						.hashCode());
		result = 37
				* result
				+ (getReviewStatusName() == null ? 0 : this
						.getReviewStatusName().hashCode());
		result = 37 * result
				+ (getCounty() == null ? 0 : this.getCounty().hashCode());
		result = 37
				* result
				+ (getFeedbackReviewStatusName() == null ? 0 : this
						.getFeedbackReviewStatusName().hashCode());
		return result;
	}

	public String getAuthority() {
		return authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
